### ISSUE TITLE
chargeScripts may raise KeyError, `"name"`, if external programs are unavailable

### ISSUE THREAD

**Issue by e-kwsm** [OpenChemistry/avogadrolibs#1034]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.96.0-175-g10a7a97f2e46
 - Qt: 5.15.5

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Version: rolling
 - Compiler (if you built from source)

**Describe the bug**
If `avogadro/qtplugins/scriptcharges/chargeScripts/{antechamber,xtb}.py` take  option `--display-name`, they access `"name"` of `getMetaData()`:

https://github.com/OpenChemistry/avogadrolibs/blob/10a7a97f2e465dfc66770c47a84f4f560fb8255d/avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py#L146-L147
https://github.com/OpenChemistry/avogadrolibs/blob/10a7a97f2e465dfc66770c47a84f4f560fb8255d/avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py#L95-L96

However, the functions return empty dict if `antechamber`/`xtb` is unavailable, respectively:

https://github.com/OpenChemistry/avogadrolibs/blob/10a7a97f2e465dfc66770c47a84f4f560fb8255d/avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py#L16-L19
https://github.com/OpenChemistry/avogadrolibs/blob/10a7a97f2e465dfc66770c47a84f4f560fb8255d/avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py#L13-L16

Consequently `getMetaData()["name"]` may raise `KeyError`.
This does not terminate execution, though.

**To Reproduce**
1. Prepare `He.xyz`:
```
1

He 0.0 0.0 0.0
```
2. Open the file in a terminal: `avogadro2 He.xyz`
3. See stderr:
```
...
Checking for  "charges"  scripts in "/usr/bin/../lib/avogadro2/scripts/charges"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/usr/lib/avogadro2/scripts/charges/antechamber.py" ; "Error running script '/usr/bin/python /usr/lib/avogadro2/scripts/charges/antechamber.py --display-name --lang C': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/usr/lib/avogadro2/scripts/charges/antechamber.py\", line 147, in <module>\n    print(getMetaData()[\"name\"])\nKeyError: 'name'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/usr/lib/avogadro2/scripts/charges/xtb.py" ; "Error running script '/usr/bin/python /usr/lib/avogadro2/scripts/charges/xtb.py --display-name --lang C': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/usr/lib/avogadro2/scripts/charges/xtb.py\", line 96, in <module>\n    print(getMetaData()[\"name\"])\nKeyError: 'name'\n"
Open Babel formats ready:  145
```

Or, run 
```
which antechamber || python avogadro/qtplugins/scriptcharges/chargeScripts/antechamber.py --display-name
which xtb         || python avogadro/qtplugins/scriptcharges/chargeScripts/xtb.py         --display-name
```

**Expected behavior**
No exception is raised.

**Screenshots**

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
Okay, but that's by design. If you don't have the programs available, the scripts should fail and Avogadro won't show the methods as options.

What would you like to happen? You want the scripts to fail silently?
