### ISSUE TITLE
Remove trailing colon `:` so `&Reference:` becomes `&Reference`

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#1041]
![image](https://user-images.githubusercontent.com/17465872/180179765-fffbc906-5c8d-459e-bc7c-c3137ef3b1c2.png)

What do you think?

Thank you

**Comment by ghutchis** [comment]
This would be a bug with the `en_GB` localization.

**Comment by ovari** [comment]
Updated `English (Australia)`, `English (Canada)` and `English (United Kingdom)` in [avogadrolibs](https://hosted.weblate.org/projects/avogadro/avogadrolibs/).
