### ISSUE TITLE
Remove colon `:` to change `Amino Acids:` to `Amino Acids` in Menu Bar > View > Colour by Residue

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#1043]
![image](https://user-images.githubusercontent.com/17465872/180181801-a169ec82-2a52-49c0-9cc2-199c98d8f619.png)

Thank you

**Comment by ghutchis** [comment]
This is a bug in the `en_GB` localization.

<img width="360" alt="Screen Shot 2022-07-21 at 10 28 26 AM" src="https://user-images.githubusercontent.com/41128/180239296-54df00a1-6f24-4423-94c1-8744a848ab71.png">

**Comment by ovari** [comment]
Updated `English (Australia)`, `English (Canada)` and `English (United Kingdom)` in [avogadrolibs](https://hosted.weblate.org/projects/avogadro/avogadrolibs/).
