### ISSUE TITLE
i18n: Quantum Chemical Input Generators may raise `KeyError: 'Theory'`

### ISSUE THREAD

**Issue by e-kwsm** [OpenChemistry/avogadrolibs#1052]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.96.0-218-g40daa16afe60
 - Qt: 5.15.5

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Version: rolling 
 - Compiler: GCC 12.1.0

**Describe the bug**
The `Theory` key is necessary for input generators that supports ab initio calculations to perform `generateInput`,  but it is accidentally translated in some locales, resulting in `KeyError`.

**To Reproduce**
1. Prepare `He.xyz`
```
1

He 0.0 0.0 0.0
```
2. Open the file with `LANG` where `Theory` is translated, e.g., German: `LANG=de_DE.UTF-8 avogadro2 He.xyz`
3. Select `Eingabe` (`Input`) and then `DALTON...`
4. `An error has occurred:`
```
Error running script '/usr/bin/python3 /usr/lib/avogadro2/scripts/inputGenerators/dalton.py --generate-input --lang de_DE': Abnormal exit status 1 (Unbekannter Fehler.: Unbekannter Fehler)

Output:
Traceback (most recent call last):
  File "/usr/lib/avogadro2/scripts/inputGenerators/dalton.py", line 198, in <module>
    print(json.dumps(generateInput()))
  File "/usr/lib/avogadro2/scripts/inputGenerators/dalton.py", line 156, in generateInput
    inp = generateInputFile(opts['cjson'], opts['options'])
  File "/usr/lib/avogadro2/scripts/inputGenerators/dalton.py", line 87, in generateInputFile
    theory = opts['Theory']
KeyError: 'Theory'
```

Here, JSON like below is passed to the generator, in which `Theory` is translated to `Theorie`:
```json
{
  "Basis": "cc-pVDZ",
  "Calculation Type": "Optimize + Frequencies",
  "Filename Base": "job",
  "Functional": "B3LYP",
  "Theorie": "SCF",
  "Title": "job"
}
```

`Debug Script…` is not helpful because `debug_info` tab does not appear.
It works as expected under a locale where `Theory` is not translated, e.g., `sv_SE.UTF-8`.

The following generators have the issue:
- DALTON
- GAMESS-UK
- Gaussian
- MOLPRO
- NWChem
- ORCA
- PYSCF
- Psi
- Q-Chem
- TeraChem

MOPAC has `Theory` but is successful.

**Expected behavior**
Generators works without error.

**Screenshots**
![de_DE DALTON](https://user-images.githubusercontent.com/11627708/180642741-ddf0fc0e-14f7-4367-934f-fc39fdc02473.png)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
This should be fixed by #1037 - which is part of 1.97 release. Can you please try 1.97 release or a newer source / AppImage?

Thanks.

**Comment by e-kwsm** [comment]
I try https://github.com/OpenChemistry/avogadrolibs/releases/download/1.97.0/Avogadro2-x86_64.AppImage but it still has the issue.

**Comment by e-kwsm** [comment]
`Basis` is also translated under `ja_JP.UTF-8`.

**Comment by laitvo** [comment]
Hello, 

I am experiencing the same issues. Would you please mind sharing the fixed AppImage files with me? Apparently I cannot access the artifacts any longer.

Many thanks!

**Comment by ghutchis** [comment]
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip

**Comment by laitvo** [comment]
> https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip

Wonderful, it works perfect! Many thanks!
