### ISSUE TITLE
Total Charge / Spin Multiplicity

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1059]
File import / export and input generators need better support for total charge / spin multiplicity.

If I read in a calculation, the program should know *throughout* that the total charge / spin is set (e.g., H3O+ or OH-, etc.)

PR #1058 gets things started
- [x] `quantumio` readers need update
- [x] input generator scripts should get total charge and spin through JSON

**Comment by matterhorn103** [comment]
We will also need a way for the user to actually set the total charge/spin for a molecule somewhere in the GUI, outside of an input generator script.

Just mentioning it here so that we don't forget :)

**Comment by ghutchis** [comment]
@matterhorn103 - coming back to this now - should the new Molecular Properties table always show the total charge and spin to allow them to be edited?

**Comment by matterhorn103** [comment]
Yes, definitely.

**Comment by ghutchis** [comment]
See #1810 - still need to update the input generators accordingly (sigh)

**Comment by ghutchis** [comment]
Actually, that was easier than I thought - the input generators will now auto-update.
