### ISSUE TITLE
inconsistent mouse scrolling in one direction

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1064]
**Avogadro version: 1.97.0**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.4

**Desktop version: (please complete the following information):**
 - OS: Debian Linux
 - Version debian unstable (linux 5.18.14-1)
 - Compiler g++ 12.1.0

**Describe the bug**

The action of the mouse scroll button is inconsistent.  When I scroll in one direction, the molecule moves smoothly "downwards" (further away into the screen) as expected. But when I scroll in the opposite direction, the molecule jumps placing the central atom right on your nose (i.e. only half the molecule shows, as if you zoomed right into the centre of the molecule).

The toggle switch "Reverse Direction of Zoom on Scroll" is working as expected.  i.e. whether scroll-down is normal scroll-up is broken, or the other way around, can be swapped with the toggle switch.

**To Reproduce**
1. Create a molecule
2. Use the mouse scroll button to move the molecule "far away"
3. Use the mouse scroll button to pull the molecule back close again
4. See error: molecule jumps to centre instead of scrolling back.

**Expected behavior**

Mouse scroll button should push and pull the molecule out and back again smoothly with no jump.

**Screenshots**

Molecule scrolled outwards to "far away"

![image](https://user-images.githubusercontent.com/26508288/181716451-c0c10e44-2d70-4765-9dde-788e7460c273.png)

Molecule scrolled back one step in the opposite direction

![image](https://user-images.githubusercontent.com/26508288/181716630-dd9d088f-18b0-4cee-ba7b-38acd902d767.png)

**Additional context**

debian build 1.97.0-1

**Comment by aerkiaga** [comment]
Hi, thanks for the detailed report. I'd like to ask for some more info, since I can't reproduce the issue:

* What Desktop Environment are you using? Are you on X or Wayland?
* What brand and model is your mouse?
* Did you build from source? If so, does this happen on older versions, or on pre-packaged Avogadro 2?
* Does this happen with other programs or just Avo2? E.g. if you install Krita (which uses Qt), does this happen when zooming out the canvas?

**Comment by drew-parsons** [comment]
I'm using Gnome on  X11 (since video conferencing tools - skype, Teams -  don't yet support Wayland).
Mouse is Logitech Performance MX (a little old by now).
I've only noticed the problem with Avo2. Krita zooms in and out smoothly in the normal way.

**Comment by aerkiaga** [comment]
Let me test it on Gnome on X... Did you encounter this issue before?

**Comment by drew-parsons** [comment]
I didn't notice this error before.  I can now reproduce the same problem in the previous version though, if I install the1.96.0-2 build.  Might be a month or so since I last accessed Avogadro.

**Comment by aerkiaga** [comment]
Unfortunately, I can't reproduce it on either GNOME 3.36.8 X.org or GNOME 42.3 Wayland... Do you get the same behavior if you check out 1.95.1 and build from source?

**Comment by drew-parsons** [comment]
debian unstable has Gnome 42.3.1.  In principle that shouldn't affect Qt operation though. If I understand correctly USB events are managed via DBUS, which is 1.14.0-2 here.

**Comment by drew-parsons** [comment]
I didn't rebuild 1.95.1, but I installed the old builds for avogadro 1.95.1-2 and avogadrolibs 1.95.1-9.

Avo2 1.95.1 scrolls smoothly back and forth, it doesn't show the erroneous jump.

**Comment by aerkiaga** [comment]
There was indeed some work on zoom between the two tags. Let's see...

**Comment by aerkiaga** [comment]
@drew-parsons here's a possible fix (#1065). You can check out the branch or wait for the binary artifacts produced by the CI. Either way, please tell us if it fixes the issue!

**Comment by drew-parsons** [comment]
Looks like the fix should show up in the nightly appstream, so I'll wait for that.

**Comment by drew-parsons** [comment]
It's fixed in the nightly AppImage now
