### ISSUE TITLE
Gaussian .log files are not read nor can create Gaussian input files - Avogadro 2 

### ISSUE THREAD

**Issue by scoopchem** [OpenChemistry/avogadrolibs#1069]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadro 2 - 1.95.0
**Desktop version: (please complete the following information):**
 - OS: Windows 11
 -

**Describe the bug**
I am unable to read in Gaussian ".log" files and to create Gaussian input files!

Help here would be great appreciated!

**Comment by ghutchis** [comment]
We will need an example .log file that doesn't work for you and a bit more details about your problems creating input.

Input => Gaussian .. (modify some options) .. "Save Input..."

**Comment by scoopchem** [comment]
Sincere Apologies - I am not the most computer savvy.  The initial download of Avogadro 2 does not have Gaussian within extension.  I am not able to change python pathways, nor do I understand how to download the Gaussian code to be read by Avogadro.
Here's a video of the issue I am experiencing --> https://youtu.be/34OOO9sMNTk
Thank you in advance for any assistance!

**Comment by scoopchem** [comment]
here are the gaussian file
[BF2-benzaldehydeimine_AAPMe-MeOH.log](https://github.com/OpenChemistry/avogadrolibs/files/9242725/BF2-benzaldehydeimine_AAPMe-MeOH.log)

**Comment by ghutchis** [comment]
>I am not able to change python pathways

Again, I'm not sure what you mean. Did you try Extensions => Set Python Path and it did not work?

**Comment by scoopchem** [comment]
I do not know how to "change python pathways".  I did not attempt to set the path. I read that correctly changing the python pathways, could be a potential solution to getting Gaussian extension to appear in Avogadro 2; and I wanted to clarity that I am unable to do this.

**Comment by ghutchis** [comment]
Do you have Python installed? If so, how did you install it?

**Comment by ghutchis** [comment]
For the Python input generators like Gaussian, yes.

Try Mambaforge: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe

It installs Python and some commonly used science packages (e.g., `numpy`)

**Comment by scoopchem** [comment]
Thank you - installing now

**Comment by ghutchis** [comment]
Does the Python install work for you as far as the input generator?

(I've flagged that there should be a dialog to indicate some features may be disabled without Python.)

**Comment by scoopchem** [comment]
I installed Python (via Mambaforge) but have gained no new features with Avogadro 2.  I am still unable to use Gaussian files.

**Comment by scoopchem** [comment]
Any advice on how to proceed after downloading Python? Any specific instructions on how to set the Python Path after downloading?

**Comment by ghutchis** [comment]
Please post to the forum https://discuss.avogadro.cc/ - this is not a great place for extended discussions.

**Comment by scoopchem** [comment]
Thank you, I installed but have no new features in Avogrado 2. I am still unable to use Gaussian files.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
