### ISSUE TITLE
Avogadrolibs fails to build because of unresolved symbols from AvogadroCalc.

### ISSUE THREAD

**Issue by Antikapitalista** [OpenChemistry/avogadrolibs#1070]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.97.0)
 - Qt: (5.15.5)

**Desktop version: (please complete the following information):**
 - OS: GNU/Linux
 - Compiler (if you built from source): gcc (Gentoo Hardened 12.1.1_p20220625 p8)

**Describe the bug**
Avogadrolibs fails to build because of unresolved symbols from AvogadroCalc.

**Expected behavior**
I expect it to compile and link successfully.
[Surfaces.patch.zip](https://github.com/OpenChemistry/avogadrolibs/files/9237576/Surfaces.patch.zip)

**Comment by ghutchis** [comment]
Weird - we've got continual builds through GitHub which should have flagged this.

Can you submit the patch as a pull request?
