### ISSUE TITLE
enable copy&paste from dialog boxes (molecular properties)

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1071]
avogadro provides a neat summary of molecular properties in Analytic→Properties→Molecular...

It could be handy to be able to access the properties reported, in the sense of copy&paste.
In particular the Molecular Weight could be copied and used in some calculations elsewhere (e.g. for determining quantities when preparing samples at the lab bench)

At the moment the dialog box is locked so that the text in it can't be copied.

This issue could be relevant also to Issue #329 , depending on how those other extended properties are presented.

**Comment by ghutchis** [comment]
Yes, I'd like to switch this to something more like a table view and agree 100% on copy/paste (for all of them)

**Comment by drew-parsons** [comment]
TableView is already used for bond and angle properties.  To be honest I think the molecular properties is "nicer looking" as it is, the TableView use for the bonds and angles is a little more ugly. Perhaps it's just a question of the style configuration used for the Tables. Or a question of taste, of course.

**Comment by ghutchis** [comment]
Related question.. I just implemented the network molecule => name option using PubChem.

I'm able to get an HTML version that includes nice formatting. Do you think this should copy the text version or the HTML version? (I'd probably lean towards text.)

<img width="398" alt="Screen Shot 2022-08-16 at 5 49 31 PM" src="https://user-images.githubusercontent.com/41128/184991715-b7965831-b51d-415f-8194-c5a8c93bdb31.png">

**Comment by drew-parsons** [comment]
Interesting question.  Can sometimes be useful to have the subscripts formatted, though maybe less useful to have them in html format.  For myself I'd mainly use plain text, e.g. copying into scripts and programs.

The use-case for the HTML format would be for copying into a document (Word or OpenOffice format) when preparing a manuscript for publication.

That C10H10 snippet, can you copy it here in formatted html text format? Then I could check how it looks after copying into LibreOffice and copying into a text file.

**Comment by ghutchis** [comment]
That's just C<sub>10</sub>H<sub>10</sub>

**Comment by ghutchis** [comment]
For the formulas, we can also use Unicode subscript numbers: C₁₀H₁₀

**Comment by drew-parsons** [comment]
> That's just C10H10

Ah good. that seems to copy just fine as it is, at least from the rendering you gave here.  That is, copying to text (e.g. at the unix command line), it simple copies C10H10 without HTML formating.  Copying to LibreOffice, it copies the formatted subscripts.  i.e. seems to get interpreted as such (formatted subscript), not as "HTML". Maybe it converts formatting automatically.  

If it copies from the app the same way it copies from here then it looks like a good solution to me.

> For the formulas, we can also use Unicode subscript numbers: C₁₀H₁₀

I'm not so sure this is the best solution. I mean, it makes simple text files look better, but I worry it might break ascii-only programs.  Maybe there aren't an ascii-only programs around any more so might not be a problem in practice.

**Comment by ghutchis** [comment]
I'll look to put together a "copy HTML" prototype this week and we'll see how it goes. I'm sure LibreOffice converts HTML to subscript / superscript automatically.

IIRC, I can add both to the clipboard with Qt.
