### ISSUE TITLE
Clicking the "Scissors" causes a crash

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#11]
If you start with an empty molecule and then click the "scissors" to clear it, the whole app crashes after a few seconds.

**Comment by cryos** [comment]
Forgot about this, will get to it and finish cleaning this up.

**Comment by cryos** [comment]
Pull request OpenChemistry/avogadroapp#22 should fix this, and I will get a better icon too. I think a cross would be easier to understand.
