### ISSUE TITLE
VTK plots do not work

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1107]
Open a crystal (either File => Import => Crystal or Open a CIF, etc.)

Go to Crystal => Plot PDF

No plot window appears .. the console prints:
2022-08-16 19:31:32.826 ( 137.243s) [         3F11AFB] vtkContextDevice2D.cxx:32    WARN| Error: no override found for 'vtkContextDevice2D'.

**Comment by cryos** [comment]
I just see a vtkMath issue now,

2023-04-02 16:08:50.516 ( 181.482s) [        4F5E4D40]            vtkMath.cxx:799   WARN| vtkMath::Jacobi: Error extracting eigenfunctions

That is clicking on Crystal -> Plot Pair Distribution Function and accepting the defaults. I am able to view vtkCharts in the 3D rendering view when editing color maps etc. So I think it is built correctly with my latest updates.

**Comment by ghutchis** [comment]
I can probably track that part down .. but I don't see anything when I choose the Plot PDF command. Shouldn't there be a new window?

**Comment by cryos** [comment]
I can take another look at where that is failing, I am not very familiar with the PDF plotting. Let me dig into that part of it and see what I can discover. I would like to revisit some of this code, and am looking at VTK-based plots in C++/Qt for another project too.

**Comment by cryos** [comment]
The no override warning you saw happens when the implementation library wasn't linked properly, I don't see that warning and it is more at the build level. Seeing charts in the other dialog means that VTK is built and linked correctly, at least in that plugin. I just need to look into what this plugin is up to.

**Comment by cryos** [comment]
OK, I spent a while looking at this, it is really the fact that we are using a widget as a window, and relying on the render window width/height. I will make a PR that is just a few lines of code so that you can test on Mac, but I would like to address this properly soon.

**Comment by cryos** [comment]
The immediate issue has been resolved, marking this as closed. More to come with charts.
