### ISSUE TITLE
Saving and loading empty file prompts error

### ISSUE THREAD

**Issue by bryancheny** [OpenChemistry/avogadrolibs#1109]
**Desktop version: (please complete the following information):**
 - OS: Linux Manjaro

**Describe the bug**

Saving an empty cjson file and opening it results in the error message "Error while reading file '[filepath].cjson': Malformed array for in atoms.element.number"

**To Reproduce**

  1. Open Application
  2. Save as cjson
  3. Open cjson

**Expected behavior**

Should not display error message when loading empty chemical file

![image](https://user-images.githubusercontent.com/68541293/185073811-7e743f47-ac52-4244-b3b3-546f0fd5022d.png)

**Comment by ghutchis** [comment]
Yes, the CJSON reader clearly needs to do more error-checking. Thanks.
