### ISSUE TITLE
Optimize geometry with Force Field | Error interpreting Open Babel output

### ISSUE THREAD

**Issue by DavidCdeB** [OpenChemistry/avogadrolibs#1110]
**Versions:**
 - Avogadro2:  1.97.0.r837.8ec3eb4-1
 - Avogadrolibs: 1.97.0.r2930.d610df7a-1
 - Openbabel: openbabel 3.1.1-4

**Desktop version:**
distro: Manjaro Linux
base: Arch Linux
kernel: 5.10.136-1
arch: x86_64
desktop: GNOME v: 42.4 

**Description of the bug:**
I get this error when trying to optimize geometry with a Force Field:
"Error interpreting Open Babel output."

![error_babel](https://user-images.githubusercontent.com/18029016/185096500-8aea55a0-e7b5-486d-9df3-61831ebd8b47.png)

**To Reproduce:**
Steps to reproduce the behaviour:
1. launch `avogadro2`
2. Click on "Draw tool"
3. In the left panel menu, "Element", select "Carbon (6)", and draw a CH4 molecule.
4. Click on "Extensions" > "Open Babel" > "Configure Force Field" 
Select "UFF" Force field, "Conjugate Gradient", "Simple" technique,
Select "Energy convergence to 10 ^-6 units" and 
"Step limit to 100000 steps"

5. Click "Ok".
6. Click on "Extensions" > "Open Babel" > "Optimize Geometry" 
7. The error appears (above screenshot).

### 1. When launching avogadro2:
```
$ avogadro2 
Using locale:  "en_DK"
Extension plugins dynamically found… 40
OBProcess::executeObabel: Running "obabel" "-L formats read"
OBProcess::executeObabel: Running "obabel" "-L formats write"
OBProcess::executeObabel: Running "obabel" "-L forcefields"
OBProcess::executeObabel: Running "obabel" "-L charges"
OBProcess::executeObabel: Running "obabel" "-V"
"obabel"  found:  "obabel: Open Babel 3.1.0 -- Jul  7 2022 -- 17:58:53"
Checking for  "commands"  scripts in "/home/david/.local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/home/david/.local/share/flatpak/exports/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/var/lib/flatpak/exports/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/bin/../lib/avogadro2/scripts/commands"
Checking for  "inputGenerators"  scripts in "/home/david/.local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/home/david/.local/share/flatpak/exports/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/var/lib/flatpak/exports/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for  "formatScripts"  scripts in "/home/david/.local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/home/david/.local/share/flatpak/exports/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/var/lib/flatpak/exports/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/bin/../lib/avogadro2/scripts/formatScripts"
Checking for  "charges"  scripts in "/home/david/.local/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/home/david/.local/share/flatpak/exports/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/var/lib/flatpak/exports/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/usr/local/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/usr/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/usr/bin/../lib/avogadro2/scripts/charges"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/usr/lib/avogadro2/scripts/charges/antechamber.py" ; "Error running script '/usr/bin/python /usr/lib/avogadro2/scripts/charges/antechamber.py --display-name --lang en_DK': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/usr/lib/avogadro2/scripts/charges/antechamber.py\", line 151, in <module>\n    raise RuntimeError(\"antechamber is unavailable\")\nRuntimeError: antechamber is unavailable\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/usr/lib/avogadro2/scripts/charges/xtb.py" ; "Error running script '/usr/bin/python /usr/lib/avogadro2/scripts/charges/xtb.py --display-name --lang en_DK': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/usr/lib/avogadro2/scripts/charges/xtb.py\", line 100, in <module>\n    raise RuntimeError(\"xtb is unavailable\")\nRuntimeError: xtb is unavailable\n"
Open Babel formats ready:  145
```

### b) When performing steps 1-7 above:
```
OBProcess::executeObabel: Running "obabel" "-icml -ocml --minimize --noh --log --crit 1e-06 --ff UFF --steps 100000 --rvdw 10 --rele 10 --freq 10"
```
### c) When clicking "OK" in the above screenshot:
```
Open Babel: ""
Process encountered an error, and did not execute correctly.
	Exit code: 6
	Exit status: QProcess::CrashExit
	Exit output: ""
```
The error message appears again. If I click "OK" again, terminal window prints:
```
Open Babel: ""
```

**Comment by ghutchis** [comment]
A few quick questions .. 

It looks like you built this from source? Or is the Open Babel from your distro package?

If you Export a file to `.cif` or `.mopin` (which force Open Babel use) does that work?

If you draw a molecule and then go to View => Color => By Partial Charge .. what do you see?

I'm trying to figure out if your Open Babel install isn't working or if there's another issue.

**Comment by DavidCdeB** [comment]
@ghutchis Many thanks for your reply. 
Please find detailed answers to your questions below.

> It looks like you built this from source? Or is the Open Babel from your distro package?

So, `avogadrolibs` and `avogadro2` were built using Arch Linux AUR repositories, respectively:

1. `avogadrolibs-git` here: https://aur.archlinux.org/packages?O=0&K=avogadrolibs
2. `avogadro2-git` here: https://aur.archlinux.org/packages?O=0&K=avogadro2

And the way I built those was through the standalone Arch Linux Aur package manager - there are several available, and a very good one is `yay`, i.e. simply:

`yay -S avogadrolibs-git`
`yay -S avogadro2-git`

commands that essentially grab the packages from the links above, and then they do the building automatically.

Regarding Open Babel, I used  the `openbabel 3.1.1-4` available in Arch Linux, in the section for "Packages": 
https://archlinux.org/packages/extra/x86_64/openbabel/ 
And I installed it following the same command as before:
`yay -S openbabel`

> If you Export a file to .cif or .mopin (which force Open Babel use) does that work?

So, 
1. Launch avogadro2
2. Click on "Draw tool"
3. In the left panel menu, "Element", select "Carbon (6)", and draw a CH4 molecule.
4. In the top panel menu, I click on "Molecule" and save as `ch4.cif`

The terminal window prints:

```
writing to  cml
OBProcess::executeObabel: Running "obabel" "-icml -ocif"
```
And the file is generated successfully.

Similarly, if I save as `ch4.mopin`, the terminal window prints:

```
 writing to  cml
OBProcess::executeObabel: Running "obabel" "-icml -omopin"
```
And the file is generated successfully.

> If you draw a molecule and then go to View => Color => By Partial Charge .. what do you see?

So,
1. Launch avogadro2
2. Click on "Draw tool"
3. In the left panel menu, "Element", select "Carbon (6)", and draw a CH4 molecule.
4. "View" > "Color Atoms" > "By Partial Charge" prompts this window:

![window](https://user-images.githubusercontent.com/18029016/185190053-e5969700-ecab-434c-9e0c-1f59ad74ed12.png)

If I click "OK" I get this:
![this](https://user-images.githubusercontent.com/18029016/185190166-9bff909e-7622-4624-90f3-2a12d7cab76a.png)

And the terminal window prints:
```
OBProcess::executeObabel: Running "obabel" "-icml -onul --partialcharge eem --print"
```

**Comment by ghutchis** [comment]
Okay, so it seems like it's specific to the optimization. I'll look into it. I assume it happens with any molecule and it's not just limited to methane.

(I'm working on a new optimization framework, so that's probably the long-term solution.)

**Comment by DavidCdeB** [comment]
@ghutchis 
Thanks a lot for your reply, truly.-

>  I assume it happens with any molecule and it's not just limited to methane.

It's good to assume, but I think we can rule out many things if one does steps 1-7: do you reproduce the error in your installation?

> **To Reproduce:**
> Steps to reproduce the behaviour:
> 1. launch `avogadro2`
> 2. Click on "Draw tool"
> 3. In the left panel menu, "Element", select "Carbon (6)", and draw a CH4 molecule.
> 4. Click on "Extensions" > "Open Babel" > "Configure Force Field" 
> Select "UFF" Force field, "Conjugate Gradient", "Simple" technique,
> Select "Energy convergence to 10 ^-6 units" and 
> "Step limit to 100000 steps"
> 
> 5. Click "Ok".
> 6. Click on "Extensions" > "Open Babel" > "Optimize Geometry" 
> 7. The error appears (above screenshot).
>

**Comment by ghutchis** [comment]
No, it works for me in current versions. But I'm not running on your computer, which is why I'm trying to troubleshoot with you.

**Comment by DavidCdeB** [comment]
@ghutchis  Perfect, thanks a lot (didn't mean to be rude; my sincere apologies if I gave that impression).

**Comment by ghutchis** [comment]
I'm still a bit stumped. If you change the locale to `en_US` does it work then?

If not, I'll put up a debugging version for you that should leave the output file around so we can figure out the bug.

**Comment by DavidCdeB** [comment]
@ghutchis Thank you for your reply. 

> If you change the locale to en_US does it work then?

I'm afraid it doesn't.

**Comment by ghutchis** [comment]
Okay, I'm a bit busy today, but I'll put up a debugging version that should leave the files around and we can look for the error.

Thanks for persevering - definitely want to fix this one.

**Comment by ghutchis** [comment]
I was looking at the Avogadro side of the code just now - it should actually print the output when that happens. But your console just shows `""` which indicates that `obabel` crashed with no output. (!)

So I think that's the step I mentioned above. Check that running `obabel` for a geometry optimization works for you.

**Comment by DavidCdeB** [comment]
@ghutchis Thanks.

> One other weird question. Let's say you save a CML file (e.g., create methane, save to CML).

1. Launch `avogadro2` from a terminal window
2. Click on "Draw tool"
3. In the left panel menu, "Element", select "Carbon (6)", and draw a CH4 molecule.
4. Click on "Molecule" > Save as `methane.cml` 

A window appears saying:

```
Multiple writers found that can write this format. Which should be used?
Avogadro: CML
OpenBabel: Chemical Markup Language
```
I choose the second, `OpenBabel: Chemical Markup Language`.

The file methane.cml is saved and looks like:

```
<?xml version="1.0"?>
<molecule xmlns="http://www.xml-cml.org/schema">
 <atomArray>
  <atom id="a1" elementType="C" hydrogenCount="4" x3="-1.828270" y3="3.549740" z3="0.000000"/>
  <atom id="a2" elementType="H" hydrogenCount="0" x3="-1.028280" y3="3.301370" z3="0.665745"/>
  <atom id="a3" elementType="H" hydrogenCount="0" x3="-1.505670" y3="4.314070" z3="-0.675742"/>
  <atom id="a4" elementType="H" hydrogenCount="0" x3="-2.113560" y3="2.680390" z3="-0.554751"/>
  <atom id="a5" elementType="H" hydrogenCount="0" x3="-2.665580" y3="3.903120" z3="0.564748"/>
 </atomArray>
 <bondArray>
  <bond atomRefs2="a1 a2" order="1"/>
  <bond atomRefs2="a1 a3" order="1"/>
  <bond atomRefs2="a1 a4" order="1"/>
  <bond atomRefs2="a1 a5" order="1"/>
 </bondArray>
</molecule>
```
Up to here, the terminal window from which I've launched `avogadro2` reads like:

```
Open Babel formats ready:  145
 writing to  cml
OBProcess::executeObabel: Running "obabel" "-icml -ocml"
```
I open another terminal, `cd` to the folder where I saved `methane.cml` and do:

```
$ obabel methane.cml -ocml --minimize --noh --log --crit 1e-06 --ff UFF --steps 100000 --rvdw 10 --rele 10 --freq 10
/usr/include/c++/12.1.0/bits/basic_string.h:1221: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

**Comment by ghutchis** [comment]
Thanks! That explains your problem - for some reason your `obabel` is crashing during the optimization (but not other tasks).

I haven't worked with `yay` - is it possible to build packages with debugging symbols? That should make it easier to run `obabel` inside of the debugger and find the bug.

**Comment by ghutchis** [comment]
I'm going to close this. It seems like a bug in your Open Babel install, not Avogadro. If you have further problems, please open a new issue, thanks.
