### ISSUE TITLE
Error generating ORCA and Gaussian files

### ISSUE THREAD

**Issue by juan0603-chem** [OpenChemistry/avogadrolibs#1124]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (e.g. 1.90.0-316-g6d14770)
 - Qt: (e.g., 5.9.5)

**Desktop version: (please complete the following information):**
 - OS: [popOS]
 - Version [22.04 LTS]
 - Compiler (if you built from source)

**Describe the bug**
Avogadro shows an error while generating an input file for ORCA and Gaussian, simply doesn't let generate that 
**To Reproduce**
1. Draw a molecule
2. Clck on "Entradas"
3. Select ORCA or Gaussian

**Expected behavior**
Let me generate an inp file for geometry optimization with ORCA
**Screenshots**
![image](https://user-images.githubusercontent.com/82042088/185850379-c022aac4-a92f-43d9-bdca-3345adafc950.png)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by e-kwsm** [comment]
Duplicate of #1052?

**Comment by ghutchis** [comment]
@e-kwsm - looks like it, yes. Still not sure why that fix didn't work, but I'll investigate this week.

**Comment by ghutchis** [comment]
@juan0603-chem - can you provide a screenshot of the ORCA input window. Is some of it translated?
