### ISSUE TITLE
Select atoms does not work when only wireframe is displayed

### ISSUE THREAD

**Issue by mkgilson** [OpenChemistry/avogadrolibs#1127]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 
 - Version 10.0.19044 Build 19044
 - Compiler: N/A

**Describe the bug**
Mouse selection of atoms does not work for the wireframe molecular representation. (It does work for e.g. ball and stick.)

**To Reproduce**
1. Load a molecule as a PDB file
2. Click on Selection Tool
3. Use left mouse button to drag and in principle select some atoms onscreen
4. No atoms are highlighted. Clicking the Delete key does not delete the atoms that should have been selected

**Expected behavior**
Selection of atoms with mouse should work in wireframe representation

**Screenshots**
Non

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
Thanks, I can confirm. Wireframe will show selected atoms (e.g., select by element or residue commands) but not the selection tool.

I'll look into this soon.

**Comment by mkgilson** [comment]
Thanks for looking into this!

**Comment by ghutchis** [comment]
This was an easy one. Seeing the issue pop up, I knew where the bug would be.

On the other hand, it exposed a much weirder selection bug (#1129).
