### ISSUE TITLE
Half orbital in 1.97

### ISSUE THREAD

**Issue by maciekofficial** [OpenChemistry/avogadrolibs#1178]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 10 x64 and Linux Ubuntu x64
 - Version: Pro Education 20H2 and 20.04.5, respectively
 - Compiler: N/A (AppImage for Ubuntu)

**Describe the bug**
Only the positive half of orbitals and spin densities is shown.

**To Reproduce**
Bug happens if:
- orbital and densities are read from cube files
- orbitals read/calculated from molden files

**Screenshots**
![avo2_bug](https://user-images.githubusercontent.com/114766651/193324701-459d1643-aa31-4e69-9451-50411deb71e3.png)

**Comment by ghutchis** [comment]
Yes, it's a known bug and fixed in HEAD. Try a nightly build, for example: https://two.avogadro.cc/
