### ISSUE TITLE
Coordinate Editor Window size bug

### ISSUE THREAD

**Issue by GeorgiyKosolapov** [OpenChemistry/avogadrolibs#1182]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 10
 - Version 1607

If there is not enough space to enter the coordinates of atoms, the program wraps the lines and perceives it as a paragraph. Because of this, the input is not read. If you enlarge the Coordinate Editor, the coordinates are read correctly.

**To Reproduce**
1. Go to 'Build'
2. Click on 'Coordinate Editor'
3. Paste coordinates
4. Click "Apply"
5. See error
6. Click "Ok"
7. Increase "Coordinate Editor" window size
8. The coordinates are in place.
9. Press "Apply"

**Expected behavior**
The coordinate reading should not be affected by the window size.
Bug:
![image](https://user-images.githubusercontent.com/114881185/193648848-691649af-32a6-4e66-b076-80063c7ea27c.png)
Window resized:
![image](https://user-images.githubusercontent.com/114881185/193650717-0813c312-14ad-4c0d-a35f-279304c0692c.png)
Tnx You for Avogadro!

**Comment by ghutchis** [comment]
Huh. That's weird... I'll take a look - thanks for the bug report!
