### ISSUE TITLE
Please make genXrdPattern a git submodule

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#1186]
**Is your feature request related to a problem? Please describe.**
Downloading files during build isn't supported by package managers for security reasons.
There is git submodule mechanism that should be used instead, that pre-downloads required files.

**Describe the solution you'd like**
See subject.

The VTK option can't be made default because of this problem.

FreeBSD 13.1 STABLE

**Comment by cryos** [comment]
The binary is independent of the project, I never really liked the default download of a static binary as part of our build process. Defaulting it to off, and then our build process can turn it on if we prefer, as can developers. I think this is reasonable, we use submodules in the supoerbuild where it could move, but this is just static binaries, so not sure if that is aided with a submodule in this case.
