### ISSUE TITLE
Please add FreeBSD to the Install section on the website

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#1195]
The "Install" section [here](https://two.avogadro.cc/) can offer users to install Avogadro2 on FreeBSD:
Command: ```pkg install avogadro2```.
FreeBSD port's page: https://www.freshports.org/science/avogadro2/

**Comment by ghutchis** [comment]
To confirm, is this an acceptable icon:
https://fontawesome.com/icons/freebsd?s=&f=brands

**Comment by yurivict** [comment]
[This](https://cdn3.iconfinder.com/data/icons/logos-and-brands-adobe/512/137_Freebsd-512.png) one has a more recognizable color.

**Comment by ghutchis** [comment]
Sorry for the delay - I made sure to add it before the 1.98 release:
https://two.avogadro.cc/install

I'm also looking at some options to auto-detect the OS like https://www.blender.org/download/ 
(I really like the button + drown-down to select other options.)

**Comment by yurivict** [comment]
Thank you!
