### ISSUE TITLE
Two project websites?

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#1196]
These two websites independently and differently describe Avogadro2:
* https://two.avogadro.cc/
* https://www.openchemistry.org/projects/avogadro2/

This makes it unclear which one is the main website.
Maybe one can point or redirect to another one?

**Comment by ghutchis** [comment]
I have no control over openchemistry.org.

**Comment by cryos** [comment]
Refer two the top one, I have control of the second and will be updating it soon.
