### ISSUE TITLE
No `Build` > `Insert` > `Peptide` option

### ISSUE THREAD

**Issue by DavidCdeB** [OpenChemistry/avogadrolibs#1199]
I cannot seem to find the `Build` > `Insert` > `Peptide` option:

Is it possible to include it?
Many thanks
![build](https://user-images.githubusercontent.com/18029016/203601110-a6d9202a-4ddf-4eb5-be8a-485d3f8c0337.png)

**Comment by ghutchis** [comment]
At the moment, the peptide builder has not been implemented in Avogadro2 (i.e., #910) - I'm going to close this as a duplicate - you can follow that issue if you want updates.
