### ISSUE TITLE
Wrong N valence

### ISSUE THREAD

**Issue by fmentink** [OpenChemistry/avogadrolibs#1201]
**Avogadro version: 1.95.1 Deb package and 1.97 AppImage

**Desktop version: (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04

**Describe the bug**
Description: wrong N valence when drawing.

**To Reproduce**
Open Avogadro, draw a molecule with just single bonds attached to a nitrogen, e.g. N(CH3)3. Later add one double bond in between N and one C. The nitrogen then obtains 5 bonds. See attached screenshot

**Screenshots**
![Screenshot from 2022-12-01 09-33-01](https://user-images.githubusercontent.com/75385132/205163163-355d6159-c85e-4bcf-8090-05f9f2e2d526.png)

**Comment by shashwat-chawla** [comment]
Nitrogen should have 5 bonds in that case ?
But in image it is showing 4 bonds ,Is it the Bug ?

**Comment by adityaomar3** [comment]
@fmentink @ghutchis can you please help me understanding the bug in more detail by telling what should be the correct o/p and current o/p

**Comment by ghutchis** [comment]
I'm not sure this is a good first issue. The problem is that the code has an exception for "hypervalent" nitro groups, e.g -N(=O)=O (i.e., it will accept a nitrogen valence of 5). 

Trying to find a good solution for this bug is a bit tricky (e.g., the draw tool should potentially change the formal charge).

**Comment by adityaomar3** [comment]
You mean to say that this is an exceptional case so we can add it as cases like for which it shows valency of 5 and for others as 3?

**Comment by ghutchis** [comment]
@adityaomar3 - I mean to say that these are tricky bugs for new contributors because the "right" answer is not always clear.

**Comment by adityaomar3** [comment]
Ok but I suggest a solution if you find it worthy lets work on it, create some cases where it can be 5 and else wise other valency.
