### ISSUE TITLE
Jumpiness when dragging new atom

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1204]
**Avogadro version: (please complete the following information from the About box):**
- Flatpak of version 1.97.0 
- Avogadrolibs: 1.97.0
 - Qt: 5.15.7

**Desktop version: (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Version 20221201

**Describe the bug**
When the pencil/Draw Tool is used to add an atom by clicking and dragging from an existing atom, the bond length increases in steps of roughly 0.5 A, making the dragging jumpy rather than smooth. I believe this is also the same on my Windows version of Avo, but it certainly didn't used to be like that. I definitely remember it at one point being smooth, identical to the smooth dragging when using the Manipulation Tool.

**Comment by ghutchis** [comment]
This was fixed by #1157 - there should be an AppImage linked there, or the [nightly AppImage](https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip)

**Comment by matterhorn103** [comment]
Ah yes, you are right, sorry. I was using the AppImage from the main page of two.avogadro.cc, which I wrongly assumed pointed at the nightly build. Of course it makes sense that it doesn't.
