### ISSUE TITLE
Ctrl+A shortcut is ambiguous

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1205]
**Avogadro version: (please complete the following information from the About box):**
- Flatpak of version 1.97.0 
- Avogadrolibs: 1.97.0
 - Qt: 5.15.7

**Desktop version: (please complete the following information):**
 - OS: OpenSUSE Tumbleweed, same behaviour observed on Windows 10 too though
 - Version 20221201

**Describe the bug**
Using the shortcut Ctrl+A gives me an error message that the shortcut is ambiguous and must be resolved by changing entries in the 'Configure Keyboard Shortcuts' menu. It is listed in the drop down menus as the shortcut for both **Edit > Graphics** and **Select > Select All**.

**Comment by matterhorn103** [comment]
In the nightly AppImage build, no error message appears but also nothing happens when ctrl+A is used

**Comment by ghutchis** [comment]
I can confirm this doesn't happen anymore - I think it was a weird localization issue.
