### ISSUE TITLE
Configuration of Label and Ball and Stick display types

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1208]
1. When `Label` is selected from the `Display types` window, the `View Configuration` options appear, and there are various options in the dropdown list "Atom Labels": Custom, Element, Element Name, Index, and None. I would expect Element Name to label the atoms with "carbon" etc., but actually it gives a combination of the element symbol and a number (that is however not the index). I suggest giving this option a different name, though I'm not sure what.
2. I also think "Element Symbol" would be better than simply "Element".
3. The option immediately above, to set the "Distance", is to me unclear about what this actually changes.
4. In the `View Configuration` for the `Ball and Stick` display type, the sliders are confusingly named. In my opinion, "Atom Style" would be better called "Atom Size" and "Bond Angle" is actually the "Bond Thickness"
5. Finally, the discoverability of the view configuration menu could be improved, as at the moment it is not obvious that clicking an entry in the `Display types` list will reveal the configuration menu. In fact, I only found out about its existence today, even after using Avogadro for a few years.

**Comment by ghutchis** [comment]
This is partly a language translation issue. What translation / localization are you using?

Labels (en_US):
<img width="303" alt="Screenshot 2022-12-04 at 7 20 48 PM" src="https://user-images.githubusercontent.com/41128/205524847-87eecb47-7192-4cc1-85be-5a17bf146a1d.png">

Ball and Stick (en_US):
<img width="251" alt="Screenshot 2022-12-04 at 7 19 49 PM" src="https://user-images.githubusercontent.com/41128/205524798-f357c1c3-6e1e-4a34-97b4-4494b1c6f25d.png">

**Comment by ghutchis** [comment]
Okay, I've fixed the UK localization through https://hosted.weblate.org/engage/avogadro/
