### ISSUE TITLE
An error occurred while retrieving the list of supported forcefields. 

### ISSUE THREAD

**Issue by AfnanAlsaati** [OpenChemistry/avogadrolibs#1221]
in Avogadro 1.95.1 (latest version), in linux Ubuntu

**Describe the bug**
When I click on optimize geometry or any button in extensions I get an error like this.
An error occurred while retrieving the list of supported forcefields. 

![image](https://user-images.githubusercontent.com/83760863/221196955-a6e0578e-eab1-48c1-9b71-e20a934f629b.png)

**Comment by ghutchis** [comment]
The latest release is 1.97: https://github.com/OpenChemistry/avogadrolibs/releases/tag/1.97.0

You can either try a newer package through DebiChem or an AppImage from the release page.

**Comment by AfnanAlsaati** [comment]
Ok thank you, 
For ubuntu I cannot download it. Can you tell me the good version for it ? 

Between:

Avogadro2-1.97.0-Darwin-arm64.dmg

Avogadro2-1.97.0-Darwin.dmg

Avogadro2-1.97.0-win64.exe

Avogadro2-x86_64.AppImage

**Comment by ghutchis** [comment]
It's the AppImage.
