### ISSUE TITLE
Connection Timeout Error when Cloning OpenChemistry Repository from GitHub

### ISSUE THREAD

**Issue by T-Arjun** [OpenChemistry/avogadrolibs#1223]
I was following the instructions provided on the Open Chemistry Wiki page titled "Build" (https://wiki.openchemistry.org/Build),

When trying to clone the Open Chemistry repository by running the command ``` git clone --recursive git://github.com/OpenChemistry/openchemistry.git ```,  an error occurred stating:
```
Cloning into 'openchemistry'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Connection timed out
```

**Comment by ghutchis** [comment]
Thanks for the heads-up, the current build instructions are at https://two.avogadro.cc/install/build.html

GitHub changed the protocol access so you want git@github.com/OpenChemistry/openchemistry.git (etc.) instead.

I'll see if I can edit the wiki for now.
