### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by njgoncalves** [OpenChemistry/avogadrolibs#1224]
**Avogadro version: 1.97.0**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - HP Laptop 15s-eq2xxx
 - OS: Win 11 Home
 - Version 22H2
 - Compiler (if you built from source)

**Describe the bug**
When using the search option in the File > Import > Search by name or other option, Avogadro show a Network Error : TLS initialization failed

**To Reproduce**
1. Go to 'File'
2. Scroll down to 'Import'
3. Chose 'Search PQR ...'
4. Search by name 

**Expected behavior**
In the table should appear de name of the compound, Formula, Mass.

Most probably there is a net configuration that we don't know how to solve.

**Screenshots**
![2023-03-21](https://user-images.githubusercontent.com/35661498/226563793-3d894d8e-f94a-41dd-b93e-38511e52cf96.png)

**Comment by ghutchis** [comment]
I apologize for the slow response. Would you be willing to try this build?
https://github.com/OpenChemistry/avogadrolibs/suites/12514745640/artifacts/668062077

I see that it has `libcrypto` installed, but I'm not sure if it has everything or solves the SSL issue.

If it does not, could you look at the About dialog - there is a new section for "SSL Version:" that would be helpful to fix the problem.

Thank you greatly!

**Comment by njgoncalves** [comment]
Thanks, I'll check it out.

A quinta, 27/04/2023, 13:50, Geoff Hutchison ***@***.***>
escreveu:

**Comment by Svk1190** [comment]
In Version 1.98.1 I am continuing to see the network error, as shown in the screenshot below. 

![image](https://github.com/OpenChemistry/avogadrolibs/assets/12389625/a72f2585-e2ec-48e6-9d41-a7593fa8e950)
