### ISSUE TITLE
No "Add center of mass" option in 1.97 Avogadro version

### ISSUE THREAD

**Issue by mloiz** [OpenChemistry/avogadrolibs#1265]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.97)
 - Qt: (Dont know)

**Desktop version: (please complete the following information):**
 - OS: [Ubuntu and Windows]
 - Version [22.04 and 10]

**Describe the bug**
It seems that in the new version 1.97 the "add center of mass" option does not appear. It should be found in the "Selection tools but only. 

**To Reproduce**
1. Go to Selection tools
2. Select a fragment with the rubber band.
3. Only Apply Colour and Change bond Order appear on the left

**Expected behavior**
To appear Add center of mass

**Screenshots**
![imagen](https://user-images.githubusercontent.com/131244622/233010348-6b9755f4-c0b2-4fb7-b17c-95d01d1b64e9.png)

**Comment by ghutchis** [comment]
I admit, I don't remember when I added the center of mass and centroid command (e.g., if they're in 1.97) - but they're under the Build / Construir menu.

<img width="280" alt="Screenshot 2023-04-19 at 9 57 20 AM" src="https://user-images.githubusercontent.com/41128/233098312-edc62b61-f0ab-44be-925e-72dea7050c83.png">

**Comment by ghutchis** [comment]
I'm closing this, since the feature exists in the latest development versions. Thanks for your question.
