### ISSUE TITLE
Openbabel error with Gaussian .log file

### ISSUE THREAD

**Issue by mloiz** [OpenChemistry/avogadrolibs#1266]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.97.0)
 - Qt: (dont know)

**Desktop version: (please complete the following information):**
 - OS: [Windows ]
 - Version [10]

**Describe the bug**
Gaussian .log filed is opened, openbabel: generic output reader is selected but unfortunately a conversion error appears. The .log file is correct and could be opened in a Ubuntu environment. And openbable is installed in windows.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/131244622/233011787-78b8d5a6-ce08-4cce-81a7-1a42337ce3e5.png)

**Comment by ghutchis** [comment]
Can you read other files through Open Babel (e.g., .mol files or .xyz)? It would help to know if it's a general Open Babel problem with the Avogadro install or specific to that file. Thanks.
