### ISSUE TITLE
Avogadro does not launch under Windows 10

### ISSUE THREAD

**Issue by MagicalDrizzle** [OpenChemistry/avogadrolibs#1291]
**Avogadro version: (please complete the following information from the About box):**
1.97.0 as downloaded from latest github release version 

**Desktop version: (please complete the following information):**
 - OS: Windows
 - Version: 10.0.19045.2846

**Describe the bug**
The application immediately exits when launched and does not display anything. Can be seen in immediately exiting in Task Manager.
Event Viewer documented the crash:
```
Faulting application name: avogadro2.exe, version: 0.0.0.0, time stamp: 0x62d9be79
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000001b90f945aa0
Faulting process id: 0x2ad4
Faulting application start time: 0x01d97f20cfbd46f6
Faulting application path: C:\Program Files\Avogadro2\bin\avogadro2.exe
Faulting module path: unknown
Report Id: bed04002-9a62-4a1e-83eb-300f7a7bf0ea
Faulting package full name: 
Faulting package-relative application ID: 
```
**To Reproduce**
Launch the application.

**Expected behavior**
Application should launch normally.

**Additional context**
Reproduced in Windows Sandbox (i.e fresh Windows 10 installation)

**Comment by ghutchis** [comment]
Thanks for the heads-up. We've been working on the build system and there also seem to be issues with the current Mac builds. I'll take a look next week.

**Comment by ghutchis** [comment]
I have asked multiple students with Windows, and the nightly builds work for them:
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

I'm going to close this. Please re-open if I'm wrong, or create a new issue.
