### ISSUE TITLE
Tool Plugins should have "Priority"

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#13]
We should be able to sort the toolbar by priority (e.g., draw, navigate, etc.) not just name.

**Comment by cryos** [comment]
Agreed

**Comment by ghutchis** [comment]
Can I merge all the tool plugins into one toolbar now? If you agree, I'm happy to go merge them and add priorities.

**Comment by cryos** [comment]
Yes, let's do that.
