### ISSUE TITLE
Closing a ring removes all hydrogens from the last atom

### ISSUE THREAD

**Issue by MagicalDrizzle** [OpenChemistry/avogadrolibs#1307]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.8

**Desktop version: (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.15.90.1-microsoft-standard-WSL2

**Describe the bug**
When drawing a bond to close a ring, all hydrogens will be removed from the atom from which you used to create the bond.

**To Reproduce**
1. Draw a carbon chain.
2. Make a bond between two terminal carbons to create a ring.
3. The carbon atom with you used to draw a bond will now have no hydrogen.

**Expected behavior**
Atoms should retain their correct number of hydrogens (in this case, minus one)

**Screenshots**
![bug](https://github.com/OpenChemistry/avogadrolibs/assets/49761211/56a5b026-80fd-4f15-8268-fe774ee3d712)

**Additional context**
Clicking a bond that is connected to the bugged atom (to change it to a double bond) will resolve the problem. (Atom will now have the correct number of hydrogens)
![bug2](https://github.com/OpenChemistry/avogadrolibs/assets/49761211/e68ec4eb-f2ef-4e46-b785-41f5d34df532)

**Comment by ghutchis** [comment]
This was fixed in the latest development HEAD. Any chance you can try an AppImage download or the Windows nightly build?

https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master

**Comment by MagicalDrizzle** [comment]
The Windows nightly build doesn't launch as per my last issue
May I ask how do you launch the latest AppImage build? It seems to be a tiny archive containing a bunch of files while the release AppImage is one large 90MB file

**Comment by ghutchis** [comment]
I'll take a look at both this afternoon. As I mentioned, we updated the build system, so clearly the builds are missing components.

**Comment by ghutchis** [comment]
Please try one of the more recent nightly builds - both AppImage and Windows are working now.
