### ISSUE TITLE
Unable to run any geometry optimization in Avogadro

### ISSUE THREAD

**Issue by kanechem** [OpenChemistry/avogadrolibs#1312]
- Avogadrolibs: not sure
 - Qt: 5.15.3

 - OS: Ubuntu linux
 - Version 22.04
 - Compiler qmake 3.1

I am unable to run any geometry optimization in Avogadro. If I try I get an error "Error interpreting Open Babel output"

I just make a new install of Avogadro building from source following the instructions at: https://two.avogadro.cc/install/build.html

I am not an expert in building software from source, but I still should be able to follow clear instructions.
Could anyone help me out with this Issue?
Thanks

**Comment by kanechem** [comment]
I acted too hastly: 
I just installed Open babel 3.1.1 and I still get the same error.

**Comment by ghutchis** [comment]
If you launch Avogadro from a Terminal, can you send me the output as you start to run it?

Open Babel is built as part of the `openchemistry` build, but whether those binaries are used depends on how you install it. (e.g., Windows, Mac, AppImage all include them in an app directory.)

**Comment by kanechem** [comment]
Here is the output you asked for:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Using locale:  "en_US"
Extension plugins dynamically found… 40
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-L formats read"
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-L formats write"
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-L forcefields"
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-L charges"
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-V"
"/home/cassio/Things/openchemistry-build/prefix/bin/obabel"  found:  "/home/cassio/Things/openchemistry-build/prefix/bin/obabel: Open Babel 3.1.1 -- Jun 20 2023 -- 12:47:33"
Checking for  "commands"  scripts in "/home/cassio/.local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/local/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/home/cassio/Things/openchemistry-build/prefix/bin/../lib/avogadro2/scripts/commands"
Checking for  "inputGenerators"  scripts in "/home/cassio/.local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/local/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/home/cassio/Things/openchemistry-build/prefix/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for  "charges"  scripts in "/home/cassio/.local/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/usr/local/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/usr/share/OpenChemistry/Avogadro/charges"
Checking for  "charges"  scripts in "/home/cassio/Things/openchemistry-build/prefix/bin/../lib/avogadro2/scripts/charges"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/antechamber.py" ; "Error running script '/usr/bin/python3 /home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/antechamber.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/antechamber.py\", line 151, in <module>\n    raise RuntimeError(\"antechamber is unavailable\")\nRuntimeError: antechamber is unavailable\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/xtb.py" ; "Error running script '/usr/bin/python3 /home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/xtb.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/cassio/Things/openchemistry-build/prefix/lib/avogadro2/scripts/charges/xtb.py\", line 100, in <module>\n    raise RuntimeError(\"xtb is unavailable\")\nRuntimeError: xtb is unavailable\n"
Checking for  "formatScripts"  scripts in "/home/cassio/.local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/local/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/home/cassio/Things/openchemistry-build/prefix/bin/../lib/avogadro2/scripts/formatScripts"
Open Babel formats ready:  145

**Comment by ghutchis** [comment]
Looks okay - it found formats, etc. When you run an optimization, it should print the command it tries to run, e.g. `obabel …`

**Comment by ghutchis** [comment]
I can certainly build up a debugging version. It's quite weird if you have `obabel` installed in your PATH.

**Comment by kanechem** [comment]
I tried running an optimization and in the terminal I get the following:
OBProcess::executeObabel: Running "/home/cassio/Things/openchemistry-build/prefix/bin/obabel" "-icjson -ocjson --minimize --noh --log --ff GAFF"
Open Babel: ""
Process encountered an error, and did not execute correctly.
	Exit code: 6
	Exit status: QProcess::CrashExit
	Exit output: ""
Open Babel: ""

Does this help you in any way to understand what's wrong?
Thanks again

**Comment by ghutchis** [comment]
Well, it tells me that `obabel` is crashing whenever you try to run an optimization.

Try saving a `file.cjson` and running that command line from the terminal?
`/home/cassio/Things/openchemistry-build/prefix/bin/obabel file.cjson -O opt.cjson --minimize --noh --log --ff GAFF`

I'd love to know why it's crashing. Presumably the `obabel` package installed on Ubuntu runs fine.

**Comment by kanechem** [comment]
Thank you for your patience.
I have done what you asked and I get the following:
/home/cassio/Things/openchemistry-build/prefix/bin/obabel file.cjson -O opt.cjson --minimize --noh --log --ff GAFF  
obabel: /home/cassio/Things/openchemistry-build/thirdparty/openbabel-prefix/src/openbabel/external/rapidjson-1.1.0/include/rapidjson/document.h:1053: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
[1]    2443 IOT instruction (core dumped)  /home/cassio/Things/openchemistry-build/prefix/bin/obabel file.cjson -O

**Comment by ghutchis** [comment]
Well, that's obviously the culprit. Can you attach the `file.cjson` for testing? Thanks.

**Comment by kanechem** [comment]
Here you go.
[file.zip](https://github.com/OpenChemistry/avogadrolibs/files/11855917/file.zip)

**Comment by ghutchis** [comment]
Thanks, I'll take a look. On my Mac, there's no problem, so I'll add it to the Ubuntu tests.

**Comment by ghutchis** [comment]
Okay, I think I finally found the Open Babel bug. I'll push a new Avogadro build soon.

**Comment by ghutchis** [comment]
Please try a recent nightly build, which should use a snapshot of Open Babel with the bugfix.

I need to release a new version of Open Babel, but this should work in the meantime.
