### ISSUE TITLE
Wrapping atoms to unit cell by default when exporting as .cif

### ISSUE THREAD

**Issue by Kantelope** [OpenChemistry/avogadrolibs#1318]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.97.0)
 - Qt: ()

**Desktop version: (please complete the following information):**
 - OS: [Ubuntu]
 - Version [22.04.2 LTS]
 - Using AppImage

**Describe the bug**
I am trying to modify .cif files to correct hydrogen placement. When exporting modified crystals back out to .cif files atoms are wrapped to the unit cell by default. 

**To Reproduce**
1. Find any .cif with a molecule that extends outside the unit cell
2. Click export and use .cif file extension
3. if you reopen the exported .cif you will see the wrapped atoms

**Expected behavior**
I simply don't want the atoms to wrap by default since that breaks the molecule and makes it unusable for calculations.

**Additional context**
I saw a blog post stating that this is an issue with open babel, they recommended using the most recent version of Avogadro. So far as I can tell I am using the most recent version available on linux and facing this problem.

**Comment by ghutchis** [comment]
Sorry for a slow reply to this. The catch is that "export to CIF" is handled through Open Babel. I'm not entirely sure the best way to make this happen, but agree it's a good idea.

**Comment by ghutchis** [comment]
This is now fixed in Open Babel, so I'm going to close this.
