### ISSUE TITLE
Menu Error: Orbital Numbering Error Gaussian Chk File Create Surfaces Dialouge

### ISSUE THREAD

**Issue by samuelpsmith** [OpenChemistry/avogadrolibs#1322]
**Avogadro version: 1.97.0**
 - Avogadrolibs: 1.97.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.3 LTS
 - Compiler (if you built from source) Did not build from source, using AppImage

**Describe the bug**
Drop down menu for create surfaces does not properly label the HOMO and LUMO. For example, labeling orbitals 166 and 167 as HOMO and LUMO when actually orbitals 169 and 170 are HOMO and LUMO. Upon further investigation, this appears to be due to the menu not being reset between the first use and subsequent uses. Then, the initial list of MO's maybe MOs 1-1066 will be listed, and then the next list of MO's for the second loaded file will be listed. Trying to create a surface from the second list will result in Avo2 crashing. 

**To Reproduce**

1. Open a Gaussian 16 .fchk file. 
2.  Choose Avogadro: FCHK reader.
3. Open Create surfaces dialogue.
4. Choose Molecular Orbital. You may see multiple Molecular Orbital Options here. (another bug)
5. Choose orbital MO 167 (LUMO)
6. Notice that this is the correct result. 
7. Open another Gaussian 16 .fchk file. When prompted, close current file without saving. 
8.  Choose Avogadro: FCHK reader.
9. Open Create surfaces dialogue.
10. Choose Molecular Orbital. You may see multiple Molecular Orbital Options here. (another bug)
11. Choose orbital MO 167 (LUMO)
12. Notice that this is not the result that you had previously, and does not match other literature results. Freak out for ten seconds about the paper you just published.
13. Check the Gaussian16 .log file to realize that MO 167 is not the correct LUMO, and in fact, it was MO 169 that was LUMO. 
14. Scroll down to see a list of correct MO's. 
15. Try to generate one of these surfaces to crash the app. 

**Expected behavior**
The HOMO should correspond to the highest occupied MO and the LUMO the lowest unoccupied MO. These should read from the .chk file. There should only be one menu of MO's

**Screenshots**
Menu problem:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/113487112/a8b893de-802c-44b3-9ddb-f3d10cf0b3e6)

Initial correct behavior:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/113487112/03d03e88-eb39-487c-bf5b-92c95f3197d2)

Follow-up bad behavior:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/113487112/9ab2ad2f-25e7-4d46-96c8-36d20db2a3a9)

![image](https://github.com/OpenChemistry/avogadrolibs/assets/113487112/7b0b2937-92a7-4abe-bd86-e76d555fe659)

**Additional context**
Sorry for the seperate archives, I had to stay under the 25mb limit. 

[test-file.zip](https://github.com/OpenChemistry/avogadrolibs/files/12297472/test-file.zip)

[test-file-2.zip](https://github.com/OpenChemistry/avogadrolibs/files/12297477/test-file-2.zip)

**Comment by samuelpsmith** [comment]
Left a comment about this here: https://discuss.avogadro.cc/t/create-surfaces-bug-duplicate-of-github/4768
I can delete that if we need to avoid duplication.

**Comment by ghutchis** [comment]
This should be fixed by #1404 finally. If you have a chance, could you take a look?
