### ISSUE TITLE
Trouble with MMFF94 and MMFF94s Optimizers

### ISSUE THREAD

**Issue by samuelpsmith** [OpenChemistry/avogadrolibs#1324]
Avogadro version: 1.97.0

Avogadrolibs: 1.97.0
Qt: 5.15.2

Desktop version: (please complete the following information):

OS: Ubuntu
Version: 22.04.3 LTS
Compiler (if you built from source) Did not build from source, using AppImage

**Describe the bug**
Attempt to use MMFF94 or MMFF94s optimizers leads to Error: Error interpreting Open Babel output.

**To Reproduce**
1. Load Iron-TrisPyridylEthene.cjson
2. In Extensions --> OpenBabel --> Configure Force Field, set force field as either Autodetect (MMFF94), as MMFF94, or as MMFF94s
3. Error: Error interpreting Open Babel output.

**Expected behavior**
I expect the molecule to be optimized.

**Screenshots**
![image](https://github.com/OpenChemistry/avogadrolibs/assets/113487112/9f61b077-dd7c-4710-9d45-f461e965b746)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

[Iron-TrisPyridylEthene.zip](https://github.com/OpenChemistry/avogadrolibs/files/12353406/Iron-TrisPyridylEthene.zip)

**Comment by ghutchis** [comment]
The error message could certainly be better, but MMFF94 doesn't have parameters for iron. (Why it doesn't work for "autodetect" is a separate question.)
