### ISSUE TITLE
Nightly Build does not run on debian

### ISSUE THREAD

**Issue by tillhanke** [OpenChemistry/avogadrolibs#1334]
**Desktop version: (please complete the following information):**
 - OS: Debian
 - Version Nightly Build from [496a592](https://github.com/OpenChemistry/avogadroapp/commit/496a592c365a9e9dffcaced5293607adb77f5270)

**Describe the bug**
If avogadro2 is run the following error message is reported:
`./bin/avogadro2: error while loading shared libraries: libMoleQueueServerCore.so: cannot open shared object file: No such file or directory
`
It sounds like some library is missing? But I can not find how to install the missing library. 

**To Reproduce**
1. Download nightly
2. Unpack
3. Run `./bin/avogadro2`

**Expected behavior**
The App should start

**Comment by ghutchis** [comment]
This should now be fixed by #1339 - I'm not sure when the nightly link updates, but artifacts from `avogadrolibs` look good.

**Comment by ghutchis** [comment]
I'm going to close this because AFAICT this now generates proper AppImage again https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip

If I'm wrong, please re-open or create a new issue. Thanks!
