### ISSUE TITLE
Extension Plugins need priorities

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#14]
Extensions should be sorted by priorities before going into menus. This ensures we can load the default menus in a coherent way, regardless of later (third-party) extensions.

Where priorities are the same, sorting should be alphabetical.

Perhaps a "plugin manager" GUI would also enable people to edit the priorities via settings.

**Comment by ghutchis** [comment]
Actually, I see that priorities exist, but they're pretty crazy. I can't easily bump "Cut" above "Copy" unless I set priorities for everything.

Maybe we should retain the order actions are added by the extension, but give the extension itself a priority? This is closer to the Avogadro v1 model and it seemed to work just fine.

**Comment by cryos** [comment]
For some reason I was not "watching" this project, and wasn't being notified about issues. Changed now, sorry about missing this, I will double check I am watching things I should be...
