### ISSUE TITLE
Cannot open vasp or cif file on windows 1q

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [OpenChemistry/avogadrolibs#1419]
Hello,

I downloaded tbe windows exdcutables and install on windows 11. When i open vasp contcar file it says not recognised. I install obabel latest version still cannot open any file. Why is that?

**Comment by ghutchis** [comment]
You mentioned that you installed Open Babel. Can you read the CONTCAR in the Open Babel GUI? Is it possible to post here (or a link to it)?

**Comment by ghutchis** [comment]
Also, what about the POSCAR? Does that work?

**Comment by Asif-Iqbal-Bhatti** [comment]
> Also, what about the POSCAR? Does that work?

yes it does open also CONTCAR. Here is the snapshot of it. 
<img width="1280" alt="image" src="https://github.com/OpenChemistry/avogadrolibs/assets/7361722/67650b73-5ffe-48f6-8d93-b70bb741daec">

but it does not convert to Gaussian format or to cif file.

**Comment by Asif-Iqbal-Bhatti** [comment]
> Thanks for opening your first issue here! Please try to include example files and screenshots if possible. If you're looking for support, please post on our forum: https://discuss.avogadro.cc/

Here is the screen shot when I open CONTCAR or cif file it says:
<img width="1280" alt="image" src="https://github.com/OpenChemistry/avogadrolibs/assets/7361722/1de8dadc-1638-4b23-9060-d4a7e2667139">

**Comment by ghutchis** [comment]
Yeah, it's a bug - someone else just reported this:
https://github.com/OpenChemistry/avogadrolibs/pull/1423

**Comment by ghutchis** [comment]
Have you been able to try a nightly build?
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

This should solve your issue - I'd like to confirm so I can make a 1.98.1 release. Thanks!

**Comment by Asif-Iqbal-Bhatti** [comment]
> Have you been able to try a nightly build? https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip
> 
> This should solve your issue - I'd like to confirm so I can make a 1.98.1 release. Thanks!

I will check now and will get abck to you

**Comment by ghutchis** [comment]
Many thanks!

**Comment by Asif-Iqbal-Bhatti** [comment]
It worked if obabel is installed.

**Comment by ghutchis** [comment]
Are you saying that the current nightly still had problems with `openbabel-3.dll`? Or I guess you don't now because you now have `obabel` installed.

Thanks - just trying to sort out what errors remain.

**Comment by ghutchis** [comment]
Okay, so that's weird. First off, Avogadro can't ready `.cif` files without `obabel`. So if it can read the `.cif` files, it's already using it.

But for your `.vasp` file, it might help to have a link to the file. Is that a POSCAR? It might very well be a bug in Open Babel.

**Comment by ghutchis** [comment]
I'm going to close this - if you have further issues, please open a new issue or ask on https://discuss.avogadro.cc/
