### ISSUE TITLE
Extension to select Python interpreter / environment

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1428]
Right now, the command to select the Python path is pretty basic.

Instead, it should allow user to choose through a widget which python interpreter to use (eg like in vscode).

![Image 23-10-2023 à 17 01](https://github.com/OpenChemistry/avogadrolibs/assets/146826974/cac25807-5dd2-4415-a752-d900912502b5)

_Originally posted by @research11111 in https://github.com/OpenChemistry/avogadrolibs/issues/1391#issuecomment-1775401977_

**Comment by ghutchis** [comment]
@adityaomar3 - this could use some help. Truthfully, I'm not sure how VS Code gets this list.

Basically, we want to build up a list of any copies of Python or environments on the computer for the user to select.

Some parts:
- Obviously, we can check PATH for multiple `python` and `python3` and check their versions.
- If the users has `conda` or `mamba` installed: `conda env list`
- For `virtualenv` if available: `lsvirtualenv` or `workon`

I'm not sure for `pipenv` or `venv` if there's a good way to list all the environments.
I don't know much about `pyenv` either.

**Comment by ghutchis** [comment]
Ideally, I'd like to know how to put together this list with shell commands, like:

`conda env list`
`lsvirtualenv`
etc.

**Comment by research11111** [comment]
`conda env list` is done in the:
  https://github.com/research11111/avogadrolibs/blob/dev-extensions/avogadro/qtplugins/plugindownloader/pythoncmdlineinterface.cpp#L96

**Comment by adityaomar3** [comment]
@research11111 can you help me figure out currently where this option is displayed on app

**Comment by research11111** [comment]
Currently it is only included on a failed merge request at https://github.com/OpenChemistry/avogadrolibs/pull/1417
with corresponding binary https://github.com/OpenChemistry/avogadrolibs/suites/17699467247/artifacts/1013285504
With commits of the merge request then the option is in menu Extensions/Manage.
Maybe if someone as time to include merge request work in main tree

**Comment by ghutchis** [comment]
I'm closing this based on #1562
