### ISSUE TITLE
Cannot run on Windows 10

### ISSUE THREAD

**Issue by lenhanpham** [OpenChemistry/avogadrolibs#1431]
Hi developers,

I've just downloaded the newest version (1.98) and installed it on my laptop (windows 10, AMD CPUs). It cannot start on my laptop. Can you guys check this error on your windows laptops?

Cheers,

**Comment by ghutchis** [comment]
I don't have a Windows laptop. Is there an error message? What precisely happens?

**Comment by lenhanpham** [comment]
Hi Ghutchis,

Nothing just happens when I click the avogadro icon. When I check task manager, Avogadro just run for 3 secs and then was killed. I have no ideas.
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/7d74a22c-6313-4ca7-ac6a-f1c95b0913a6)

**Comment by ghutchis** [comment]
Can you try a nightly build?
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

**Comment by lenhanpham** [comment]
Hi Ghutchis,

The same error happens. Avogadro2.exe is killed in 3 to 5 secs.
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/96abaacc-74e3-44f7-808b-a0e2c5dcdf54)

**Comment by ghutchis** [comment]
I would check the logs:

> Open Event Viewer.
> Click Windows Logs.
> Right-click Application
> Click "Save all events as"
> Select location, name the file, and click Save.
> Select "Display Information for these languages ", click English and click OK.
> Upload the saved log file to OneDrive and share the link

**Comment by ghutchis** [comment]
If you can launch it from a command prompt, that would also help, since Avogadro adds debugging messages to the console.

**Comment by lenhanpham** [comment]
Hi Ghutchis,

I think I have something here:

`Faulting application name: avogadro2.exe, version: 0.0.0.0, time stamp: 0x653aba8f
Faulting module name: atio6axx.dll, version: 27.20.11044.7, time stamp: 0x5f6d6b62
Exception code: 0xc0000005
Fault offset: 0x00000000012da065
Faulting process id: 0x2844
Faulting application start time: 0x01da0b9d3e9cd40e
Faulting application path: C:\Program Files\Avogadro2\bin\avogadro2.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0359349.inf_amd64_14a932a498cb67e4\B359612\atio6axx.dll
Report Id: 3f5f0faa-3b0b-4ef0-bd46-13a31a811e05
Faulting package full name: 
Faulting package-relative `

**EvenData**
`avogadro2.exe 
   0.0.0.0 
   653aba8f 
   atio6axx.dll 
   27.20.11044.7 
   5f6d6b62 
   c0000005 
   00000000012da065 
   2844 
   01da0b9d3e9cd40e 
   C:\Program Files\Avogadro2\bin\avogadro2.exe 
   C:\WINDOWS\System32\DriverStore\FileRepository\u0359349.inf_amd64_14a932a498cb67e4\B359612\atio6axx.dll 
   3f5f0faa-3b0b-4ef0-bd46-13a31a811e05 
`

**Comment by lenhanpham** [comment]
Note that everything is fine with the previous version 1.97

**Comment by ghutchis** [comment]
Doing a search for `atio6axx.dll` turns up:
https://community.amd.com/t5/drivers-software/amd-driver-problem/td-p/474097
https://community.amd.com/t5/opengl-vulkan/opengl-problem-maybe-with-atio6axx-dll/m-p/612056

It sounds like some versions of the AMD software, particularly Adrenaline are buggy with OpenGL programs.

**Comment by lenhanpham** [comment]
Thanks Ghutchis. I'll try to update the driver and see. But it is totally fine with the version 1.97. So, So something was changed in the new version.

**Comment by lenhanpham** [comment]
Thanks @ghutchis. It is working now but the performance is very slow in comparison to the 1.97 version.

This version 1.98 still cannot open Gaussian output log files or any files. I'll open a new ticket to report this error.

Errors:
Cannot open Gaussian log files with drag and drop:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/3eb60ee5-e675-4265-a087-cfb179c66113)

Cannot open Gaussian log file if using open from the menu:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/e2bb5db8-0a96-40f7-ba7a-87800925495d)

Even an xyz file, still has the same error.

In general, cannot open any file. 

I do not know what is happening now.

**Comment by ghutchis** [comment]
There's a bug. Use the nightly, which will shortly be released as 1.98.1

**Comment by ghutchis** [comment]
By the way, if your graphics card or driver are having problems with the real-time shading, you can turn it off in the View ⇒ Rendering dialog. 
<img width="415" alt="SetRenderingOptions" src="https://github.com/OpenChemistry/avogadrolibs/assets/41128/abe26bda-4337-4cdb-956c-96a5fdc8cc04">

**Comment by lenhanpham** [comment]
Thanks @ghutchis. The performance is improved a lot, but still cannot open any files.

Using Open menu:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/a426361f-c709-4e55-993a-f7f9334fe2da)

Drag and drop a file:
![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/55fee584-0e11-4d01-b4ae-7668bbc4ffff)

**Comment by lenhanpham** [comment]
Here I think Avogadro cannot handle the format of directory path on windows. On windows, a dir path should like this: E:\Projects\Sulfide-crossover\DMF.xyz, not E:/Projects/Sulfide-crossover/DMF.xyz

**Comment by lenhanpham** [comment]
Fortunately, the nightly version can open several file formats like mol, xyz, cif, pdb and so on, but not outputs generated by Gaussian.

![image](https://github.com/OpenChemistry/avogadrolibs/assets/69336081/e070986f-6b8b-4235-a765-50a1fd2711e8)

**Comment by ghutchis** [comment]
Can you send me or link to the file? I obviously have no problem when reading Gaussian files.

**Comment by ghutchis** [comment]
> Here I think Avogadro cannot handle the format of directory path on windows. On windows, a dir path should like this: E:\Projects\Sulfide-crossover\DMF.xyz, not E:/Projects/Sulfide-crossover/DMF.xyz

No. Avogadro (and many other programs) are capable of understanding that '/' and '\' are directory separators.

**Comment by lenhanpham** [comment]
Hi @ghutchis 

This is an example of gaussian output from my calculations.

Thanks for your work.

[DMF.log](https://github.com/OpenChemistry/avogadrolibs/files/13216725/DMF.log)

**Comment by ghutchis** [comment]
This works fine on my Mac. I suspect there may be an issue with Open Babel. For the nightly build, did you get an error about `openbabel-3.dll`?

Beyond that, you may wish to install `cclib` with Python (e.g., `pip install cclib` or `conda install -c conda-forge cclib`. You can then use the `avogadro-cclib` plugin through Extensions ⇒ Download Plugins to read files through cclib.

I would suggest that if you need additional help, it would be easier for others to make suggestions on the forum: https://discuss.avogadro.cc/

I'm closing this issue, because it resolved as:
- a driver bug
- issues with filenames resolved in the latest nightly
