### ISSUE TITLE
Imported target "spglib::spglib" includes non-existent path

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#1438]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.1
 - Qt: 5.15.1

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 13.2
 - Compiler clang-16

**Describe the bug**
Configure fails:
```
CMake Error in avogadro/core/CMakeLists.txt:
  Imported target "spglib::spglib" includes non-existent path

    "/usr/local/include/spglib"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

cmake/FindSPGLIB.cmake isn't necessary because spglib-2.1.0 provides cmake files.

**Comment by ghutchis** [comment]
I think this is also a request for "upgrade spglib to 2.x"

**Comment by yurivict** [comment]
Otherwise the latest avogadrolibs release isn't usable with spglib-2.1.0.

**Comment by ghutchis** [comment]
Yes, thanks for the report - I'll take care of it.
