### ISSUE TITLE
Mac builds for 1.98 have broken Open Babel

### ISSUE THREAD

**Issue by research11111** [OpenChemistry/avogadrolibs#1443]
**Avogadro version:**
 - Avogadrolibs: 1.98.1
 - Qt: 5.15.2

**Desktop version:**
 - OS: [e.g. MacOS]
 - Version [e.g. 14.0]

**Describe the bug**
When using Build/Insert/SMILES menu a popup show "No line format readers found!"

**To Reproduce**
1. Open avogadro
2. Click on 'Build' menu
3. Select 'Insert'
4. Click on 'SMILES...'

**Expected behavior**
The popup should show up with a qt line text box.

**Screenshots**
<img width="1385" alt="Capture d’écran 2023-11-05 à 12 20 45" src="https://github.com/OpenChemistry/avogadrolibs/assets/146826974/a330711e-f5bd-4fcf-a36d-a107b09cffa0">

**Additional context**
[Corresponding binary](https://github.com/OpenChemistry/avogadrolibs/releases/download/1.98.1/Avogadro2-1.98.1-Darwin-arm64.dmg)
Same behavirour for insert InChl
previous version have also that issue

**Comment by research11111** [comment]
Source of the issue: obabel not correctly finding shared libs
when running manually:

```
(base) bash-3.2$  "/Applications/Avogadro2.app/Contents/MacOS/obabel" "-L formats read"
dyld[5748]: Library not loaded: /Users/runner/work/avogadrolibs/build/prefix/lib/libopenbabel.7.dylib
  Referenced from: <D7A85E74-2639-3576-9A65-34776230618B> /Applications/Avogadro2.app/Contents/MacOS/obabel
  Reason: tried: '/Users/runner/work/avogadrolibs/build/prefix/lib/libopenbabel.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/avogadrolibs/build/prefix/lib/libopenbabel.7.dylib' (no such file), '/Users/runner/work/avogadrolibs/build/prefix/lib/libopenbabel.7.dylib' (no such file), '/usr/lib/libopenbabel.7.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

Avoagadro2.app package:  
./Contents/Frameworks/  
	do not contains this file libopenbabel.7.dylib  

also in the build pipeline the code responsible for changing the path has been disabled:  
https://github.com/OpenChemistry/avogadrolibs/blob/2d5c2d1fb26278e3742ccd27d5cb1db86f6d447f/.github/workflows/build_m1.yml#L107-L115

Solutions that can be applied:  
 
 On dev side:  
 
 	1. include libopenbabel in the Avoagadro2.app and modify the binary with install_name_tool so shared library gets from ./Contents/Frameworks/.
 
 	2. Allow DYLD_LIBRARY_PATH even with mac SIP 	https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables?language=objc
 
 	3. Add non standard location of libraries with homebrew : /opt/homebrew/ for apple and /usr/local/ intel
 
 On user side:
 
 	1. Copy needed libraries from homebrew location /opt/homebrew/ to /usr/lib/


otool add rpath is not an option because it invalidate signature of avogadro app

**Comment by research11111** [comment]
intel mac version do not search in the location "application directory"
```
(base) bash-3.2$ otool -L /Volumes/Avogadro2-1.98.1\ 2/Avogadro2.app/Contents/MacOS/obabel 
/Volumes/Avogadro2-1.98.1 2/Avogadro2.app/Contents/MacOS/obabel:
	/Users/runner/work/avogadrolibs/build/prefix/lib/libopenbabel.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```
as arm64 version does
```
/Applications/Avogadro2.app/Contents/MacOS/obabel:
	@executable_path/../Frameworks/libopenbabel.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.151.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```

**Comment by research11111** [comment]
As temp fix only for arm64 builds:
```bash
brew install open-babel
cp /opt/homebrew/lib/libopenbabel.* /Applications/Avogadro2.app/Contents/Frameworks/
```

**Comment by research11111** [comment]
Issue has been introduced in 1.98.0 build (1.97.0 is working)

**Comment by ghutchis** [comment]
Thanks for the bug report. Between 1.97 and 1.98 there were a bunch of changes to the build system, and it helps a lot (since I obviously have `libopenbabel` installed.

> Avoagadro2.app package: ./Contents/Frameworks/ do not contains this file libopenbabel.7.dylib

Huh. That happened on Windows too. Not sure why the Intel version also doesn't have the corrected path for `obabel` either.

**Comment by sulimovv** [comment]
> As temp fix only for arm64 builds:
> 
> ```shell
> brew install open-babel
> cp /opt/homebrew/lib/libopenbabel.* /Applications/Avogadro2.app/Contents/Frameworks/
> ```

Thank you very match!
That's works for me on Monterey 12.7.1 (ARM)
