### ISSUE TITLE
Exporting Gaussian .log file as a .cjson crashes avo 1.98.1

### ISSUE THREAD

**Issue by samuelpsmith** [OpenChemistry/avogadrolibs#1446]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.1

**Desktop version: (please complete the following information):**
-ubuntu jammy jellyfish

**Describe the bug**
When attempting to export a .log file as a .cjson, program crashes. 

**To Reproduce**
open .log attempt to export as .cjson. Crash Avo2

**Expected behavior**
Export geometry as a .cjson

**Screenshots**

**Additional context**
[
[Tyr-Phe_B3LYP6-311g.log](https://github.com/OpenChemistry/avogadrolibs/files/13274166/Tyr-Phe_B3LYP6-311g.log)
](url)

**Comment by ghutchis** [comment]
I think I just fixed this one. It turns out the CJSON writer was trying to write Raman intensities even if they didn't exist. Oops.

Can you check HEAD or a build from #1452 - I found that when I was working on the `cmpk` format.

**Comment by ghutchis** [comment]
I'm closing this - I'm pretty sure that fixed the crash. Please re-open or add a new issue if you still have the crash. Thanks!
