### ISSUE TITLE
Atom Properties should calculate Partial Charges or hide the column

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1471]
Right now, if no partial charges are calculated, the partial charge column is 0.0, which is incorrect.

I think there are possible solutions:
- hide the partial charge column if no charges have been calculated
- use the first possible charge model to display *something* (e.g., check when `setMolecule()` is called)
- (both) e.g., if no charges are calculated and no model is available

**Comment by Surajjalpun2002** [comment]
I did a weird fix where i moved the partial charge column to the last and when no charges have been calculated, the number of columns reduces to 7 from 8. But when it finds some type of partial charge is calculated it increases it back to 8 essentially rendering the partial charge column at the last.
![Screenshot from 2023-12-05 01-52-22](https://github.com/OpenChemistry/avogadrolibs/assets/107067085/16391e6e-c5d5-4285-bae1-daf1a5915941)
![Screenshot from 2023-12-05 01-53-12](https://github.com/OpenChemistry/avogadrolibs/assets/107067085/bb9336cd-9204-4d38-9b69-5973aee4e214)

**Comment by ghutchis** [comment]
It looks like it's adding partial charge number to the color column.

**Comment by Surajjalpun2002** [comment]
Yeah gotta fix that too.

**Comment by Surajjalpun2002** [comment]
Is it issue solved? or is there something still to be done here?

**Comment by ghutchis** [comment]
I think for now, this is fixed, thanks.
