### ISSUE TITLE
core contains inconsistent cmake header reference to Eigen3::Eigen3

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1475]
There is a cmake header reference to `Eigen3::Eigen3` at 
https://github.com/OpenChemistry/avogadrolibs/blob/204a4098f5f13202c3795367b5f4c2a2a5f7e7ff/avogadro/core/CMakeLists.txt#L29

I think this is incorrect, it should be `Eigen3::Eigen` instead, as used at https://github.com/OpenChemistry/avogadrolibs/blob/204a4098f5f13202c3795367b5f4c2a2a5f7e7ff/thirdparty/tinycolormap/CMakeLists.txt#L21

See also Eigen3 documentation at https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html
cf. https://gitlab.com/libeigen/eigen/-/blob/dd8c71e62852b2fe429edb6682ac91fd1c578a26/cmake/Eigen3Config.cmake.in

The same discrepant use of `Eigen3::Eigen3`  is also found in [FindEigen3.cmake](https://github.com/OpenChemistry/avogadrolibs/blob/master/cmake/FindEigen3.cmake)

The discrepant Eigen3 definition may be partially responsible for the runtime test problem reported at  https://github.com/OpenChemistry/avogadrolibs/issues/1430.

Separate from fixing `Eigen3::Eigen3`, is FindEigen3.cmake actually needed?  Eigen3 provides its own cmake config files, so [`find_package (Eigen3)`](https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html) ought to work without a separate FindEigen3.cmake script.

**Comment by ghutchis** [comment]
I dunno, but if I change `Eigen3::Eigen3` in that CMakeLists.txt it fails to build, even though it has a `find_package(Eigen3)` at the top of the file.

I've tried a few things to remove `cmake/FindEigen3.cmake` and it utterly fails.

If you have suggestions or a patch based on other packages, I'd be happy to fix this.

**Comment by drew-parsons** [comment]
This patch got it working for me (here without removing avogadrolibs' FindEigen3.cmake)

https://salsa.debian.org/debichem-team/avogadrolibs/-/blob/d866558eedf3d9d0ad96a1af34f9522ea2fadfac/debian/patches/tests_include_eigen.patch

**Comment by ghutchis** [comment]
Since I'm not near my laptop for most of the day, could you submit this as a pull request?

Thanks!

**Comment by drew-parsons** [comment]
I'll do it

**Comment by ghutchis** [comment]
If you have a better PR, please feel free to open it and I'll drop #1544

**Comment by drew-parsons** [comment]
It'd take more time to try the alternative of dropping FindEigen3.cmake, so go ahead with #1544
