### ISSUE TITLE
Need graph / plot widgets

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#148]
Discussing with @psavery that widgets for plotting are needed for the YAEHMOP interface (e.g., directly running extended Hückel on molecules and solids).

Alternatives:
* QWT (http://qwt.sourceforge.net/)
* VTK

**Comment by cryos** [comment]
My experience with Qwt has been pretty terrible. I want to resurrect the volume rendering, and if we use VTK for that then I would say the charts from there are basically for free. I know the API for them really well, and can get fixes in too.

**Comment by ghutchis** [comment]
I'm fine with VTK - I think @psavery just wants to know that something will get built in for graphs.

**Comment by psavery** [comment]
Yep! That sounds good to me!

**Comment by ghutchis** [comment]
I believe this was solved by #212 so I'm closing
