### ISSUE TITLE
suggest of an explicit dummy atom type

### ISSUE THREAD

**Issue by nbehrnd** [OpenChemistry/avogadrolibs#1483]
**Is your feature request related to a problem? Please describe.**

While preparing a ligand for the template library, the position of the eventually complexed / chelated ion can be indicated by a centroid to serve as a place holder.  If the ligand's structure requires additional edit (pen tool), the pull down menu displays the currently active atom type to add additional atoms/change a carbon by a nitrogen, etc.  It equally is possible to change the atom type of the dummy/place holder into a specific e.g., iron.  However, the pull-down menu does not yet hold an entry which would allow to (re)assign an iron (back) as a dummy atom.

**Describe the solution you'd like**

I would like to suggest the pull down menu to offer an atom type "place holder", for instance ahead of the entry about hydrogen.  Influenced by interfaces by other sketchers (e.g., Marvin JS) a symbolization by `A` and an entry `any atom` as element type appear suitable, too.

Because the suggestion is about a single additional "element" only, an additional tile very left/very right to the lanthanides/actinides displayed in the periodic table may complement the addition.

**Describe alternatives you've considered**

There are not yet.

**Additional context**

![pull_down_menu](https://github.com/OpenChemistry/avogadroapp/assets/19709084/b1c40330-4422-4945-8372-4382028d5051)

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
I'm not sure I want to add it to the draw tool, but I agree there's a need for a "change element" that includes dummy atoms.

In the meantime, you can use the coordinate editor (change atomic symbol to Xx) or edit the text of the CJSON file to make the element number 0.
