### ISSUE TITLE
does not import from PQR

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1489]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.1
 - Qt: 5.15.10

**Desktop version: (please complete the following information):**
 - OS: Linux (debian unstable)
 - Version 6.5.13
 - Compiler g++ 13.2.0

**Describe the bug**
I am trying to load the a molecule from PQR. The PQR search engine does find them, for instance searching "benzene" by name, there is only one entry, the PQR search box finds it and displays the preview image for the molecule. But when I click on Download, the screen remains blank.  The molecule is not imported.

Molecules do import successfully via the "Download by Name" search box. Actually there's something weird going on there. It was working, but after testing a few different molecules while writing this bug report, it stopped importing too. But with no error message written to console (the PQR error is consistent, see below) so it's probably a different issue.

I couldn't import anything from PDB but that I think that's a separate issue (I might not be using the right search term for pdb).

**To Reproduce**
1. Go to 'File' menu
2. Click on 'Import'-'Search PQR...'
3. Search by "benzene" (name).
4. Click 'Search'
5. Click on the found molecule, wait for the preview image to appear
6. Click 'Download'
7. See error

**Expected behavior**
Molecule should import successfully from PQR without an obabel error.

**Screenshots**
An error is printed to console
```
Reading to format:  "cjson" cjson
OBProcess::executeObabel: Running "obabel" "-imol2 -ocjson"
"obabel"  stderr:
 "obabel: cannot write output format!\n"
```

**Additional context**
Openbabel version is 3.1.1

**Comment by ghutchis** [comment]
Sounds like there might be an OpenSSL issue? Does the "Download Plugins" work show anything?

There's definitely an issue in some cases in which the OpenSSL version for Qt doesn't match the installed version of OpenSSL.

**Comment by ghutchis** [comment]
Oh, okay. I'm trying to switch to using `obabel` support for CJSON by default. In principle, the Avogadro code should detect that your `obabel` doesn't support CJSON and use CML instead.

That's definitely a bug.

**Comment by ghutchis** [comment]
Wait - you said you can't use PDB download either? That should directly read through native Avogadro code (MMTF) not Open Babel.

**Comment by drew-parsons** [comment]
I'm not certain that I'm using the right search term with PDB.  If I enter `lysozyme`, for instance, it tells me "Could not read the PDB molecule: lysozyme"

**Comment by ghutchis** [comment]
Yeah, at the moment, I'm not aware of a generic search API for PDB -- would be nice.

Try `1CRN` or `6vxx` as PDB codes.

**Comment by drew-parsons** [comment]
Alas, 1CRN and 6vxx aren't found by the PDB search either.

**Comment by drew-parsons** [comment]
PQR import is now working in v1.99 (imports benzene), but PDB import is still not working.

**Comment by ghutchis** [comment]
I'm going to close this. Please open a new issue for PDB import and we can debug that.
