### ISSUE TITLE
Consistent segfaults while manipulating bonds between independent carbon bonds + hydrogens

### ISSUE THREAD

**Issue by Makiah** [OpenChemistry/avogadrolibs#1492]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.0-eed1ba848a8bbae6d50205eda16e1046a760e36e
 - Qt: 5.15.2 GCC 64-bit

**Desktop version: (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - Compiler N/A

**Describe the bug**
Avogadro 2 will segfault and display some suboptimal behavior while manipulating bonds and hydrogens between two independent carbon atoms. I've narrowed one potential problematic sequence of events down to the following, for which I've attached screenshots in order to reproduce. 

**To Reproduce**

1. Open Avogadro 2, create two carbon atoms by left clicking with the "Draw" tool.
![step1](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/4da50da0-08e4-411e-bc48-776fb5b535b6)
2. Left click on the first carbon atom, and drag the resulting bond to the second carbon atom. You should see the following. Notably this hydrogen manipulation done after the bond manipulation is also incorrect, as the second carbon now has zero attached hydrogens: this seems related to https://github.com/OpenChemistry/avogadrolibs/issues/1478. 
![Screenshot from 2023-12-03 18-55-41](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/9366b2c0-d7dd-45b0-b688-adad4a60ef76)
3. Remove the bond between the first and second carbon by right clicking it. 
![Screenshot from 2023-12-03 18-56-01](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/19fa4f58-e3d5-40b9-9f9d-42336d5006f4)
4. Remove the second carbon by right clicking it
![Screenshot from 2023-12-03 18-56-13](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/00b9a439-09e5-4fc5-bc41-f0f028b73bc0)
5. Remove the first carbon by right clicking it. You'll notice a segfault prompted by a `nullptr` access to `Molecule::bonds`, I have a quick fix set up locally so I see the following. 
![Screenshot from 2023-12-03 18-56-27](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/4844826e-4efd-470a-bc70-e22cb3f85490)
![Screenshot from 2023-12-03 18-56-35](https://github.com/OpenChemistry/avogadrolibs/assets/10727824/ad73366d-f153-4995-85ce-334ec66a3bd1)

Working on understanding the root cause here to ideally address this issue and https://github.com/OpenChemistry/avogadrolibs/issues/1478 simultaneously. 

**Expected behavior**
No segfaults, valence shell of carbons correctly populated at each step in the above process (might split this into a couple separate PRs). 

**Screenshots**
Attached above

**Comment by ghutchis** [comment]
Is this now fixed by #1493 ? I was never able to reproduce this, so I need to know if your patch fixed the underlying issue. Thanks.

**Comment by ghutchis** [comment]
Once again, I'm pretty sure this is fixed. Can you please check? Otherwise I'm going to close this in a week as resolved.
