### ISSUE TITLE
Change Template>Ligands to Fragments and Build>Insert>Fragment to Molecule

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1496]
Fragment to me implies part of a molecule, rather than a full self-contained one. Adding these to an extant molecule is what the `Template` tool does via `Ligands`.

Since the fragments from `Ligands` can be added to any molecule, not just metals, it is useful for adding e.g. acetyl groups to sugars, and calling it ligands hides this fact.

The source for the contents of that tab is also the OpenChemistry/fragments repository.

Meanwhile `Build|Insert|Fragment...` allows the insertion of full molecules, not attachment to current ones. It is sourced from OpenChemistry/molecules.

For consistency I suggest calling the `Ligands` tab of the `Template` panel `Fragments`, and the menu option `Build|Insert|Molecule...`

If this is agreed on then I'll look at changing it myself.

**Comment by ghutchis** [comment]
Seems like something to post on the forum https://discuss.avogadro.cc/

Build -> Insert -> Molecule is fine with me.

Not quite as sure about "Fragment" vs. "Ligand" in the template tool... ligand seems somewhat better to me, in part because many of the categories are ligands.

Maybe the solution for discovery is to have 3 tabs: "Centers", "Ligands" and "Fragments" or "Functional Groups"

**Comment by matterhorn103** [comment]
Sorry, I am often unsure when a forum post is better to promote discussion and when it is better to just open an issue to save you a job.

> Maybe the solution for discovery is to have 3 tabs: "Centers", "Ligands" and "Fragments" or "Functional Groups"

That would also be a sensible way to do it.

**Comment by ghutchis** [comment]
No worries. I've been trying to keep "things that need discussion from many people" on the discussion forum and "tickets for accountability" here on issues.

I've noticed that more casual users don't follow GitHub.

**Comment by ghutchis** [comment]
Let me know if that PR does what you suggested...

**Comment by ghutchis** [comment]
Oh, you wanted the molecules piece too..

Do you think I should move Build => Insert => Molecule to File => Import to match the Crystals dialog?

**Comment by matterhorn103** [comment]
> Let me know if that PR does what you suggested...

This looks perfect this way I think, yeah. :)

I wonder if maybe under `Templates > Centers > Coordination`: the **"1: Linear"** option should be called **"1: Terminal"** to avoid having both it and **"2: Linear"** described as being linear, which leads to slight confusion.

On a more philosophical level, can an atom with a single bond even be considered a linear geometry?
