### ISSUE TITLE
Allow plugins/extensions to request specific positions in menus, choose order of commands, layout of dialogs

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1498]
Currently anything added to a menu or dialog by a plugin seems to be displayed in alphabetical order. Ideally the plugin could choose how these things are displayed.

If I understand correctly, in the code, menu options are given an integer as a sort of "priority" and are ordered by that, and dividers are added every 100. So ideally what would be implemented:

1. When a script specifies its location using `--menu-path`, it would be able to provide a number to use for sorting *at each level* so that it could affect both the plugin's location in the menus, but also the relative order of the plugin's commands if it has multiple.

Secondly, the options for customizing script-specific dialogs are fantastic and allow for a lot of flexibility, but the way things are displayed is not controllable:

2. The relative order of dialog widgets specified in  `"userOptions"` should be settable.

I am not sure what the mechanism is for the latter in other dialogs in the program.

**Comment by ghutchis** [comment]
Adding "menu priority" wouldn't be too hard. Maybe there's a way to add it to `--menu-path`, like:

"Build|Insert{32}" to indicate the priority.

I guess you also want to add an "order" attribute to change the sort of the "userOptions"? Makes sense.

**Comment by matterhorn103** [comment]
Exactly that would be perfect :)

**Comment by ghutchis** [comment]
See #1501 

I'll have to do some work on the "order" attribute.

**Comment by matterhorn103** [comment]
Remind me to add stuff to the docs about this before you close the issue!
