### ISSUE TITLE
Copy / paste or export property dialogs

### ISSUE THREAD

**Issue by maverick422** [OpenChemistry/avogadrolibs#1505]
How can I get the output file of various types of properties in the analysis like atom and bond, dihedral angle properties, I mean to output these parameters in the form of a file like excel file

**Comment by ghutchis** [comment]
@Surajjalpun2002 - can you take a look at #1506 and see if we can add a small context menu with "Copy" and "Export CSV" or similar options?

https://stackoverflow.com/a/24255300/131896

**Comment by Surajjalpun2002** [comment]
will do.

**Comment by maverick422** [comment]
I am very grateful for this, but I have another question, when I use the export tool to export the data file of LAMMPS, the file seems to be missing the information about bonds and others, so that in ovito, there is an error message said ‘’Bond type out of range in Bonds section of LAMMPS data file at line 654‘’.I'm not sure if it's just me or something else, since I have windows 10, Avogadro version 1.98.1 and Avogadro Library fersion: 1.98.1, and I'm constructing a macromolecular structure with six monomers crosslinked. I've tried other formats of output files that don't seem to work to keep the bond properties and so on, so I'm filing this ISSUE about the properties information and look forward to your reply, thanks!

**Comment by Surajjalpun2002** [comment]
![image](https://github.com/OpenChemistry/avogadrolibs/assets/107067085/d97d8f99-f1e9-489a-ac85-cc2570f09405)
is this fine?

**Comment by Surajjalpun2002** [comment]
![image](https://github.com/OpenChemistry/avogadrolibs/assets/107067085/31a30f52-fa77-4b29-84c1-ee51a4ada547)
![image](https://github.com/OpenChemistry/avogadrolibs/assets/107067085/e7be9ae4-109c-4a82-8269-68e47d5dc8ae)
currently only csv file can be created though

**Comment by ghutchis** [comment]
Sure, looks good. Can you submit a pull request? Thanks!

**Comment by ghutchis** [comment]
Fixed by #1515 thanks!
