### ISSUE TITLE
Cannot open XYZ files with tab-separated columns

### ISSUE THREAD

**Issue by pepalogik** [OpenChemistry/avogadrolibs#1512]
**Avogadro version**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.3

**Desktop version**
 - OS: Linux Mint
 - Version: 21.2 Cinnamon
 - Compiler: - (installed from Ubuntu repos)

**Describe the bug**
(already described in the title)

**To Reproduce**
1. Extract the attached file.
2. Try to open it with Avogadro.

**Expected behavior**
A visualization of the structure should appear, as was the case in older versions of Avogadro. PyMOL can read the file, too.

**Screenshot - text (with file path removed)**
[File error]
Error while reading file '...':
Not enough tokens in this line: Ni	0.0	0.0	0

**Additional context**
I think the culprit is the method of line splitting in this line:
https://github.com/OpenChemistry/avogadrolibs/blob/d86b46d118162e02ff123b49d44b64ef64f27ef6/avogadro/io/xyzformat.cpp#L96C47-L96C47
As the XYZ format is not standardized, I think any combination of tabs and spaces between tokens should be accepted.

**Attachment**
[IniModelCutout.zip](https://github.com/OpenChemistry/avogadrolibs/files/13614914/IniModelCutout.zip)

**Comment by ghutchis** [comment]
I would love to know what program is putting out XYZ files with tabs...

**Comment by ghutchis** [comment]
I would be very careful using tabs because many other programs split on spaces.
