### ISSUE TITLE
View Configuration pane is empty

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1529]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.1
 - Qt: 5.15.11
 
The bug applies to both an up-to-date self-compiled version and the nightly AppImage. As I wasn't aware that the pane should have anything in it, I guess this bug has always existed.

**Desktop version: (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version: snapshot 20231213
 - KDE Plasma Version: 5.27.10
 - KDE Frameworks Version: 5.112.0
 - Kernel Version: 6.6.6-1-default (64-bit)
 - Compiler (if you built from source)

**Describe the bug**
The view configuration pane is completely empty for all tools.

**Expected behavior**
Screenshots of the macOS version at two.avogadro.cc indicate that the pane should be populated.

**Screenshots**
![Screenshot_20231215_014900](https://github.com/OpenChemistry/avogadrolibs/assets/83813148/18923fcc-bacc-4466-a6a2-d262752e79a5)

**Comment by ghutchis** [comment]
Click on a display type (like Ball and Stick)

**Comment by ghutchis** [comment]
Personally, I think that pane should be hiding unless you tap an icon like in Avogadro 1.x, but I'm open to suggestions.

**Comment by matterhorn103** [comment]
Ah, I see. The empty is very counterintuitive, yes.

I think the actual problem at the moment is that it is hidden functionality. I had (and a given user would have) no idea that clicking the entries in the "Display types" menu brings up options.

One idea that might make it more discoverable: the ball and stick option could be selected by default when Avogadro launches, which would mean the View Configuration panel would be populated already with the relevant options. On my system, even though various Display types are ticked, none are actually highlighted.

This is actually the second time that I didn't know about some functionality that is revealed by clicking the display type entries, so I think somehow it needs to be clearer that the entries are not just checkboxes, some sort of visual indication.

**Comment by matterhorn103** [comment]
Another thought – what about if each entry in Display types had a ••• button next to the name, like in various other programs (including GitHub on the top-right of comments here actually). This would indicate extra options.

Clicking it could open the View Configuration pane. Then that pane could be hidden like you suggest.

**Comment by ghutchis** [comment]
The tricky thing is getting the columns right:

<img width="257" alt="Screenshot of display types with … indicated" src="https://github.com/OpenChemistry/avogadrolibs/assets/41128/04e2810c-cf31-4ff4-adfc-ee29c91922c3">
