### ISSUE TITLE
[BUG]: When the layout is empty and you try to get angle properties App Crashes

### ISSUE THREAD

**Issue by secretkontributer** [OpenChemistry/avogadrolibs#1564]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.98.0
 - Qt: 5.15.3

**Desktop version: (please complete the following information):**
 - OS: Windows11
 - Version 10.02.2261
 - Compiler (if you built from source)

**Describe the bug**
App Crashes when you try to get angle properties (when the layout is empty basically no molecules are there)

**To Reproduce**
1.Go to Analysis menu tab
2. Go to properties
3. Go to angle properties
4. App will crash

**Expected behavior**
The app should not crash .

**Screenshots**
![Screenshot 2024-01-01 115031](https://github.com/OpenChemistry/avogadrolibs/assets/134409422/5f53cd5b-acd4-4e16-9801-a398ad6e6c37)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
Oka, this is fixed, so I'm going to close it. Thanks!
