### ISSUE TITLE
Sssr cannot find the ring of following xyz file.

### ISSUE THREAD

**Issue by zhangfq-chemistry** [OpenChemistry/avogadrolibs#1592]
30
30
 C                 -2.99877605   -0.01835985    0.00000000
 C                 -1.60361605   -0.01835985    0.00000000
 C                 -0.90607805    1.18939115    0.00000000
 C                 -1.60373205    2.39790015   -0.00119900
 C                 -2.99855705    2.39782215   -0.00167800
 C                 -3.69615805    1.18961615   -0.00068200
 H                 -3.54853505   -0.97067685    0.00045000
 H                  0.19360195    1.18947115    0.00063400
 H                 -1.05353205    3.35004315   -0.00125800
 H                 -3.54867905    3.35010315   -0.00263100
 H                 -4.79576205    1.18979915   -0.00086200
 Fe                -0.63917707   -1.69011107    0.00230795
 N                  0.50086726   -1.03423130   -1.31288051
 O                  1.57286781   -0.61208158   -0.97967897
 O                  0.12797757   -1.05417561   -2.45260164
 S                  0.44519215   -3.56974844    0.00490290
 O                  1.06362601   -3.76518642    1.24098764
 O                 -0.34850216   -4.58231394   -0.53670102
 H                  1.26339123   -3.19216367   -0.81859588
 C                 -1.82212628   -2.37067448    1.36699275
 O                 -2.83419070   -3.06264716    1.26471251
 O                 -1.43536567   -2.00175804    2.61428056
 H                 -2.04635500   -2.35659257    3.28057280
 C                 -1.50736442   -2.17975902   -2.05568326
 C                 -2.41506626   -2.73005718   -0.99446780
 H                 -0.79318520   -2.80384456   -2.36135208
 H                 -1.71452872   -1.24829350   -2.34277746
 H                 -2.20790196   -3.66152270   -0.70737361
 H                 -3.12924548   -2.10597164   -0.68879899
 F                  0.42579821   -1.07402457    1.23270020

**Comment by ghutchis** [comment]
You need to provide much more information. Avogadro doesn't use SSSR.

What version of Avogadro are you using and what exactly are you trying to do?

Thanks.

**Comment by ghutchis** [comment]
I'm happy to re-open this if you can explain the particular bug or provide more context, thanks.
