### ISSUE TITLE
Fetch PDB does not import molecules

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1616]
**Avogadro version:
 - Avogadrolibs: 1.99.0   (1.99.0-410-gc556839)
(but About also reports "Avogadro Library Version: 1.97.0-4-37-geaf1e6e")
 - Qt: 5.15.10

**Desktop version:**
 - OS: Linux
 - Version: debian unstable
 - Compiler gcc 13.2.0

**Describe the bug**
The Import: Fetch PDB function fails to import molecules. 
The dialog box reports, for instance, "Could not read the PDB molecule: 1CRN"

I tested "lysozyme", "1CRN", "6vxx"

**To Reproduce**
1. Go to 'File'
2. Click on 'Import'
3. Scroll down to 'Fetch from PDB...'
4. For "Chemical structure to download", enter 1CRN. Click OK. 
5. See error

**Expected behavior**
Fetch PDB should find and import molecules. 

**Additional context**
Originally discussed in #1489

**Comment by ghutchis** [comment]
If you can try #1622 - I would be curious at what step things fail. The patch adds console debugging output after receiving the network reply and when trying to read the temporary file.

**Comment by drew-parsons** [comment]
The patch reports
``` FetchPDB received data from network and wrote to temp file:  "/tmp/1CRN.mmtf"
Reading molecule from temp file:  "/tmp/1CRN.mmtf"
```
I can confirm the reported file was created
```
$ ls -l /tmp/1CRN.mmtf
-rw-r--r-- 1 user user 7885 Feb 18 00:39 /tmp/1CRN.mmtf
```
containing binary data
```
$ head /tmp/1CRN.mmtf
�%�mmtfVersion�1.0.0�mmtfProducer�UNKNOWN�numBonds�Q�numAtoms�G�numGroups.�numChains�numModels�structureId�1CRN�title�wWATER STRUCTURE OF A HYDROPHOBIC PROTEIN AT ATOMIC RESOLUTION. PENTAGON RINGS OF WATER MOLECULES IN CRYSTALS OF CRAMBIN�chainsPerModel��groupsPerChain�.�chainNameList�A�chainIdList�A�spaceGroup�P 1 21 1�unitCell��B#�
�A�33�A�(��B��B��=�B��bioAssemblyList���transformList���chainIndexList��matrix��?������?������?������?��name�1�bondAtomList��`	�!'#/)61;8F=LHTN_Vganitpv�����������������s����������������������
�!%#-'9/>;�bondOrderList�<0�groupList���groupName�SER�atomNameList��N�CA�C�O�CB�OG�elementList��N�C�C�O�C�O�bondOrderList��bondAtomList��formalChargeList��singleLetterCode�S�chemCompType�L-PEPTIDE LINKING��group
```
Trying to open the file from avogadro crashes the computer.

**Comment by drew-parsons** [comment]
With #1642 , 1CRN and 6vxx import successfully.  lysozyme triggers a segfault.

**Comment by ghutchis** [comment]
Do you have a pointer to the lysozyme model you used? I'd obviously like to get rid of segfaults 😄

**Comment by drew-parsons** [comment]
No model here.  I literally just typed in `lysozyme` in the input box.  For what it's worth, it segfaults if I enter `ghutchis` too.

If I search for `1LYZ` then it loads fine.

**Comment by ghutchis** [comment]
That works for me, but I'll check around the code and make sure the error checking is robust.

**Comment by drew-parsons** [comment]
That patch sorts fixes it.
