### ISSUE TITLE
Player tool crashing: SIGSEV

### ISSUE THREAD

**Issue by hollaho** [OpenChemistry/avogadrolibs#165]
Program crashes at startup after "Player tool added". This might mean that the player tool is not responsible but whatever comes next. Or that Playertool messed something up.
Strace indicates rather a problem with the grafics engine or its use.

avogadro2-0.8.0:

> OBProcess::executeObabel: Running "obabel" "-V"
> "obabel"  found:  "obabel: Open Babel 2.3.2 -- Oct 21 2016 -- 01:15:10"
> Checking for generator scripts in "/usr/bin/../lib64/avogadro2/scripts/inputGenerators"
> Checking for file format scripts in "/usr/bin/../lib64/avogadro2/scripts/formatScripts"
> "MeasureTool" added
> "Navigator" added
> "PlayerTool" added
> fish: 'avogadro2' terminated by signal SIGSEGV (Adressbereichsfehler)

strace:

> ioctl(8, DRM_IOCTL_GEM_OPEN, 0x7ffd494af420) = 0
> ioctl(8, DRM_IOCTL_I915_GEM_WAIT or DRM_IOCTL_RADEON_GEM_OP, 0x7ffd494af3d0) = 0
> ioctl(8, DRM_IOCTL_RADEON_GEM_GET_TILING, 0x7ffd494af440) = 0
> ioctl(8, DRM_IOCTL_I915_GEM_WAIT or DRM_IOCTL_RADEON_GEM_OP, 0x7ffd494af400) = 0
> ioctl(8, DRM_IOCTL_RADEON_GEM_CREATE, 0x7ffd494af400) = 0
> ioctl(8, DRM_IOCTL_RADEON_GEM_CREATE, 0x7ffd494af360) = 0
> futex(0x1368e0c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1368e08, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
> futex(0x1368de0, FUTEX_WAKE_PRIVATE, 1) = 1
> ioctl(8, DRM_IOCTL_RADEON_GEM_CREATE, 0x7ffd494af490) = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf341a7000
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x968} ---
> +++ killed by SIGSEGV +++
> fish: 'strace avogadro2' terminated by signal SIGSEGV (Adressbereichsfehler)

**Comment by ghutchis** [comment]
Can you try 1.90 instead? I'm not sure if there's anything specific, but it would help:
http://www.openchemistry.org/downloads/

Certainly, there shouldn't be crashes, so I'm happy to help debug this.

**Comment by cryos** [comment]
As Geoff said it would be useful if you could try the latest version, but this looks like you are using the open source ATI driver. If so, it would be good to get more details on the graphics card/driver/OS. I suspect we are hitting a driver issue as next is generally displaying the 3D view, we try to ensure the context has everything we need, but I am afraid the open source ATI driver has not worked well in my experience (and I don't have current hardware I can test on).

**Comment by hollaho** [comment]
I am using Gentoo as OS, so the avogadro version depends on whats available for portage. Seems this is pretty outdated. I can also try to manually download and compile the 1.9 version, but this may fail if it has much differend dependencies compared to 0.8. Might be better to get the Gentoo package updated first...

**Comment by cryos** [comment]
Any luck on this, in all honesty I suspect it is the OpenGL stack provided by the graphics driver. I don't have an ATI card in any of my Linux machines as I have found the Linux OpenGL support to be lacking...

**Comment by cryos** [comment]
I am going to close this, it looks like something outside of our control, and is unlikely to be something we can fix. The tools are loaded right before we attempt to render an empty scene using OpenGL. I don't use ATI on Linux, but have had great luck with Intel and NVIDIA cards. We require OpenGL 2.1, and do what we can to detect it/warn but this doesn't always work.
