### ISSUE TITLE
App crashes when clicking "Optimize Geometry" without any atom

### ISSUE THREAD

**Issue by perminder-17** [OpenChemistry/avogadrolibs#1660]
**Describe the bug**
When attempting to optimize geometry in the application without adding any atoms, the app crashes. This occurs specifically when navigating to Extension -> Optimize Geometry without prior addition of a molecule.

**To Reproduce**
1. Don't add any atom.
2. Go to Extension
3. Click on Optimize Geometry

**Expected behavior**
The app should not crash.

**Comment by perminder-17** [comment]
Made a PR for this @ghutchis .

**Comment by ghutchis** [comment]
Thanks - fixed by #1661
