### ISSUE TITLE
Orbitals Toolbar Does Not Display When Opening a Formatted Checkpoint File

### ISSUE THREAD

**Issue by haydenmann3** [OpenChemistry/avogadrolibs#1669]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 10.12.4]: 1.99.0

**Describe the bug**
When opening a gaussian formatted checkpoint file (.fchk), the geometry displays but the MOs do not. The only way to render the MOs is to calculate a surface. The formatted checkpoint file has the MOs saved to it, calculated in gaussian using pop=(nboread, savemixed). But when I open this file, the orbitals toolbar does not display. This issue does not occur in Avogadro 1.

**To Reproduce**
On a sample molecule of your choice in Guassian, compute the NBOs of a molecule and save them to the checkpoint file. This can be done using the following line in your gaussian input file.

`# b3lyp/[your basis set] pop=(nboread, savenbos)`

Once the calculation is complete and the .chk file is converted to .fchk using the `formchk` utility, open this file in Avogadro2.

**Expected behavior**
The Orbital Toolbar should pop-up, allowing me to easily render the MOs.

**Additional context**
Due to the preliminary nature of my research, I cannot upload sample files for the molecule I've seen this issue with.

**Comment by ghutchis** [comment]
It's not a bug. We haven't implemented that feature yet.

You can render MO through the Analysis => Create Surfaces… command
