### ISSUE TITLE
request of clarification, string translation

### ISSUE THREAD

**Issue by nbehrnd** [OpenChemistry/avogadrolibs#1677]
To close the loop of the French avogadrolibs translation on weblate, there is one string I seek help to translate.

At present, the source string is `line size`.  Prior to the update of the English source about 6 months ago, it was `line width`.  Weblate's context to this reads 

> i18n: file: qtplugins/spectra/spectradialog.ui:434 i18n: ectx: property (text), widget (QLabel, label_5)

In the Linux AppImage of Avogadro 1.99 at my disposition, fetched today 2024-06-25, I can *guess* that this belongs to an entry following either analysis -> vibrational modes, or analysis -> plot spectra.  Reading the output of GAMESS (US) about water (attached below) which *I thought* would provide access to both an equilibrium structure as well as vibrations, the two options remained gray and inaccessible to advance further.  Thus perhaps one of the watchers can help me here.

The earlier `line width` could be translated with two different meanings and the current source string `line size` is not of help for me:

+ `largeur de ligne` would about about `line width` as in using either a thin, or coarse pencil to plot the diagram; i.e. how to present the results of the computation.
+ `largeur de raie` on the other hand refers to spectral linewidth.  Though it appears less probable than the first option, because of the limitations mentioned, it still could represent the original intent.

[request_clarification.zip](https://github.com/user-attachments/files/15975051/request_clarification.zip)

**Comment by ghutchis** [comment]
"Line width" is probably better. It's the first choice - a thin or coarse line for the diagram. It's on the appearance section of the dialog.

I'll put in a change to the text and a clarification in the translation call which should propagate through into Weblate in a day or two.
