### ISSUE TITLE
cannot import from PQR: Network error socket operation timed out

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#1687]
**Avogadro version:**
 - Avogadrolibs: 1.99.0 (debian 1.99.0-5+b2)
 - Qt: 5.15.13
 - OpenSSL 3.2.2

**Desktop version::**
 - OS: Debian Linux
 - Version unstable
 - Compiler gcc 13.3.0
 - Build log  https://buildd.debian.org/status/fetch.php?pkg=avogadrolibs&arch=amd64&ver=1.99.0-5%2Bb2&stamp=1719565080&raw=0 
  
**Describe the bug**
Today "Import from PQR" fails to return search results, instead returning
Name: Network error
Mass:  Socket operation timed out

Network access in general is fine, in the sense that "Fetch from PDB" returns 1CRN successfully, and "Download by Name" returns molecules.  Extensions-"Download Plugins" finds a list of available plugins.

**To Reproduce**
1. Go to 'File'
2. Click on 'Import'
3. Scroll down to 'Search PQR'

**Expected behavior**
PQR import should return (a list of) results, rather than timing out with a network error.

**Screenshots**
![image](https://github.com/OpenChemistry/avogadrolibs/assets/26508288/8e3098a4-0832-4c1b-b32b-b6f7ad93719b)

**Comment by ghutchis** [comment]
I mean, I think that's a PQR issue, not an Avogadro one... At the moment, it seems to be down.

**Comment by drew-parsons** [comment]
Ah, I was afraid that might be the problem. Hopefully they bring it back.
