### ISSUE TITLE
workspace(background graphics) issues

### ISSUE THREAD

**Issue by Subula-debug** [OpenChemistry/avogadrolibs#1690]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (e.g. 1.90.0-316-g6d14770)
 - Qt: (e.g., 5.9.5)

**Desktop version: (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. 10.12.4]
 - Compiler (if you built from source)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by Subula-debug** [comment]
![Screenshot 2024-08-22 6 50 12 AM](https://github.com/user-attachments/assets/b98de0c2-7f22-4f1f-9a86-85af03bf5ac6)
this how my software appears 
what might  be the problem and how do I fix it

**Comment by ghutchis** [comment]
You're using an old version (1.97). Please install, e.g. from https://two.avogadro.cc/ either 1.99 or a nightly build.

**Comment by ghutchis** [comment]
I'm closing this because it should be fixed in more recent releases or nightly builds as indicated above.
