### ISSUE TITLE
cartesian

### ISSUE THREAD

**Issue by Timote79** [OpenChemistry/avogadrolibs#1691]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish Avogadro calculated XYQ moments to render with ..

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please be detailed. How might this feature work (e.g., first a window would open and you'd click to …)

**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
I don't know what your request or bug is - can you please supply some comments or post on the forum at https://discuss.avogadro.cc/ Otherwise I will close this issue in a week.

**Comment by ghutchis** [comment]
I'm closing this because it's not at all clear what your request or bug is.
