### ISSUE TITLE
How to add a repeated molecule

### ISSUE THREAD

**Issue by Timote79** [OpenChemistry/avogadrolibs#1693]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish Avogadro calculated XYQ moments to render with ..

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please be detailed. How might this feature work (e.g., first a window would open and you'd click to …)

**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
I'm not sure I know what you want - you didn't change any of the boilerplate template.

You want to copy / paste? Select the molecule, Edit => Copy then Edit => Paste

**Comment by ghutchis** [comment]
I'm closing this - if you have questions, please open a topic on https://discuss.avogadro.cc - the best place for support discussions.
