### ISSUE TITLE
Black screen when changing window size

### ISSUE THREAD

**Issue by RubiaLab** [OpenChemistry/avogadrolibs#1699]
Avogadro version:
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.2

Desktop version:
 - OS: MacOS
 - Version 14.6.1

**Describe the bug**
On my MacBook, I get complete back screen in the Avogadro2 app as soon as I resize the window. No matter if I click on the "+" button for full screen or by resizing the window manually with the mouse arrow.

**Screenshots**
<img width="1116" alt="Bildschirmfoto 2024-08-31 um 11 13 21" src="https://github.com/user-attachments/assets/7147571c-7f25-4e02-a055-94f67548d082">

**Comment by ghutchis** [comment]
That's certainly a new one. Out of curiosity, are you running on Intel or Apple Silicon?

Can you try a nightly build: https://two.avogadro.cc/ and see if it also happens? It should be a newer release of Qt IIRC.

**Comment by pokapple** [comment]
I’m running on a MacBook Air Intel i7 Late 2020.
The link to the MacOS Nightly Build on the website is not working currently.

**Comment by RubiaLab** [comment]
Okay, the MacOS Nightly Build link is working again. But also with the nightly build, the problem is still there. As soon as I resize the window, everything turns black. But according to the program information, it is the same Qt-Version 5.15.2.

**Comment by RubiaLab** [comment]
I just found out by coincidence: If you draw a molecule and optimize it, the black screen does not occur upon resizing the window...at least I could resize Avogadro now to full screen...interesting workaround ;)

**Comment by ghutchis** [comment]
This is definitely a weird graphics driver bug on Mac / Intel. Have you upgraded to macOS 15.x yet? If it still active on there, I'll see what I can do about getting a test build with Qt 6.x.

**Comment by RubiaLab** [comment]
I just updated from macOS 15.0.x to 15.1.1 and it actually seems to work now. I couldn't produce the same error again. It seems as it was some issue which was fixed with the update. I'll close the issue and thank you for your help :)
