### ISSUE TITLE
Add ghost atoms to elements list in the Draw Tool's pane or to Build menu

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1715]
As far as I know, the only current way to create a ghost/dummy atom is by creating one of a normal element, then changing the element to `Xx` in either the coordinate editor or `Atom Properties`.

We will document this of course as part of the 2.0 docs, but it's still not discoverable or obvious.

I suggest adding it to the list of elements that can be selected from when using the Draw Tool; alternatively, it could be a menu entry under `Build`, under `Insert` presumably.

**Comment by Tharanishwaran** [comment]
can i work in this issue

**Comment by Tharanishwaran** [comment]
can i work in this issue ?

**Comment by Tharanishwaran** [comment]
can i work in this issue

**Comment by Tharanishwaran** [comment]
\assign
