### ISSUE TITLE
Energy and Forces Calculation not Working on Mac

### ISSUE THREAD

**Issue by ChemEm** [OpenChemistry/avogadrolibs#1723]
**Avogadro version: 1.99.0**
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.8

**Desktop version:**
 - OS: MacOS
 - Version: 13.5.1
 - Compiler: N/A

**Describe the bug**
Energy and forces calculation under "Extensions"-->"Calculate" always returns 0, even after configuring and optimizing the geometry through Babel.

**To Reproduce**
1. Go to 'Extensions'
2. Click on 'Calculate'
3. Select 'Energy' or 'Forces'
4. See error, display is 'MMFF94 Energy = 0'

**Expected behavior**
The error should not be 0, and should display units. 

**Screenshots**
<img width="676" alt="Screenshot 2024-10-02 at 22 08 07" src="https://github.com/user-attachments/assets/7f6e13a4-dc06-4295-b060-9b64ca0d0bd0">

**Additional context**
Just using this to see the energy of different butane conformers.

**Comment by ghutchis** [comment]
There's a thread on the forum as linked.

Would you be willing to run from the Terminal.app - this will show the console messages and hopefully give me more information about what's going on.

If you open up a Terminal, you can run Avogadro2 like this:

``` bash
/Applications/Avogadro2.app/Contents/MacOS/Avogadro2
```

(This assumes you've installed Avogadro in your /Applications folder.)

You'll see a whole bunch of messages like:
```
Using locale:  "en_US"
qt.network.ssl: Error receiving trust for a CA certificate
Extension plugins dynamically found… 49
OBProcess::executeObabel: Running "/Applications/Avogadro2.app/Contents/MacOS/obabel" "-L formats read"
OBProcess::executeObabel: Running "/Applications/Avogadro2.app/Contents/MacOS/obabel" "-L formats write"
… (etc)
```

Use the app - draw a molecule, etc. and then calculate the energy or optimize and copy / paste the log here.

I'd like to know why you're not seeing any energies (but on my MacBook and other test Macs it's working fine.)
