### ISSUE TITLE
Arabic menu items

### ISSUE THREAD

**Issue by hmsenn1** [OpenChemistry/avogadrolibs#1724]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: NA (empty)
 - Qt: NA (empty)
 - This is for Avogadro2 1.99, Nightly Build Mac Intel 30-09-24. The dmg release has the same issues.

**Desktop version: (please complete the following information):**
 - OS: MacOS
 - Version 12.7.6

**Describe the bug**
Some menu items, buttons, etc. are in Arabic. See the screenshots for examples.

**To Reproduce**
N/A

**Expected behavior**
English please

**Screenshots**
2 screenshots as examples.

<img width="744" alt="Screenshot 2024-10-07 at 15 40 53" src="https://github.com/user-attachments/assets/c9717ddd-f294-4fe8-838d-bbc03648e00c">
<img width="647" alt="Screenshot 2024-10-07 at 15 35 20" src="https://github.com/user-attachments/assets/fc635be2-5ee4-4024-aa9b-8a92df4a76ac">

**Comment by ghutchis** [comment]
Yes, there is a start of an Arabic translation:
https://hosted.weblate.org/projects/avogadro/-/ar/

If you don't want that, you can change the default language using Extensions ⇒ User Interface Language... and restart Avogadro

**Comment by ghutchis** [comment]
In general, on Mac, it picks up on languages in your System Settings list. If you haven't added Arabic, it would help to see what your "Preferred Language" list is in your System Settings.

**Comment by hmsenn1** [comment]
English (UK) is the primary language, then German and French. To my surprise, Arabic and a few other languages in non-Latin scripts followed (see screenshot). I've now deleted all the non-Latin languages, went back to Avogadro, set the language to System Language, and it's all fine.
<img width="228" alt="Screenshot 2024-10-07 at 16 27 04" src="https://github.com/user-attachments/assets/4d7f2951-c6d9-43ed-aae8-cd075dd1c485">
