### ISSUE TITLE
[BUG]: Hovered 'Light/Dark' Text Sticks After Mode Switch – Requires Extra Click to Dismiss

### ISSUE THREAD

**Issue by sinhaaman3256** [OpenChemistry/avogadrolibs#1725]
**Describe the bug:**
When switching between light and dark mode, the hovered text "light/dark" remains visible until an additional click is made. The hover text does not disappear automatically after the mode switch, requiring unnecessary interaction.

**To Reproduce:**
1. Open Avogadro.
2. Hover over the mode toggle button (light/dark).
3. Click to switch between light and dark modes.
4. Notice that the hover text persists after the switch until another click is made.

**Expected behavior:**
The hovered "light/dark" text should disappear automatically when the mode switch is completed without needing an additional click.

**Screenshots:**
![Screenshot 2024-10-10 004438](https://github.com/user-attachments/assets/ad069ff5-41a1-4f9a-97f4-0124c88aea81)

**Video Demonstration:**
[

https://github.com/user-attachments/assets/167dc765-8214-4ada-9572-056b1679f326

]

**Additional context:**
This issue creates a minor but noticeable disruption in the user experience when switching themes. Automatically dismissing the hover text would streamline interactions.

**Comment by ghutchis** [comment]
Is this with the website https://two.avogadro.cc/ or the app?

**Comment by sinhaaman3256** [comment]
The website

**Comment by ghutchis** [comment]
As far as I can tell, it's inherent in the pydata-sphinx theme: https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/gallery.html

There's probably a way to fix it with custom CSS, but I'm not an expert. I'm also having trouble figuring out the particular element for that "hover" text.

I agree with you, it's really weird, but I'm not sure we can do anything about it right now.
