### ISSUE TITLE
Background in split view appears transparent

### ISSUE THREAD

**Issue by PeteGierth** [OpenChemistry/avogadrolibs#1729]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.99.0 (nightly version downloaded 14/10/2024)
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: windows 
 - Version 10
 - Compiler (if you built from source)

**Describe the bug**
When you split the screen view, either horizontally or vertically, the new section of screen has no background, you just see through to whatever is behind (desktop, other windows etc). 
As a workaround You can click on the new section, and view menu-> set background colour and set it, and it updates to whatever you set.

**To Reproduce**

1. Click on 'split horizontal'
2. 2. click " 3d view" in the new section

**Expected behavior**
The workspace is split into two with the same background colour in each

**Screenshots**
(what you can see on the right hand side here is my desktop background)
![image](https://github.com/user-attachments/assets/3e27d95c-1e4b-4de7-9823-5377387f74de)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
Huh. Now that's a new one... Looks like it's not properly copying the render options from the previous pane.

**Comment by ghutchis** [comment]
I've been investigating this and it seems like it could be a bunch of work. How important is the feature to you?

I'm inclined to disable the "split horizontal" / vertical buttons for now -- in favor of getting 2.0 out the door with auto-optimize, etc.

**Comment by PeteGierth** [comment]
Hi Geoff,
I like the split horizontal/vertical feature a lot; but the background issue
is really pretty trivial. Given the workaround I don't see that fixing this is
at all important compared to the other things that I'm sure are taking up lots of your time!
I would favour leaving the split view in place as is.

Thanks for your efforts in making this extremely useful software!

Pete



--

Peter Gierth (he/him)

Senior NMR Specialist

Yusuf Hamied Department of Chemistry

University of Cambridge

https://www.ch.cam.ac.uk/analytical/nmr



________________________________
