### ISSUE TITLE
vtk-7 support

### ISSUE THREAD

**Issue by sagitter** [OpenChemistry/avogadrolibs#174]
Hi all.

Can you render `avogadrolibs` compatible with `vtk-7.1.0` please?

**Comment by cryos** [comment]
I think I need a little more detail on what you want here. I would turn off the experimental VTK support for now if you are packaging, I will be updating it to work with recent updates we merged into VTK in the last few months and things should work much better.

**Comment by sagitter** [comment]
I'm packaging `avogadro2` for Fedora; we are using `vtk-6.3.0` with `Fedora <= 25` and `vtk-7.1.0` in following releases. `avogadrolibs` works fine with `vtk-6.3.0` but not with `vtk-7.1.0` that provides some different modules and header files.

I disabled `vtk` support for now.

**Comment by ghutchis** [comment]
I believe this is now solved by #210 - correct @cryos ?

**Comment by cryos** [comment]
This should be resolved now yes. Closing, but please reopen if master won't build for you.
