### ISSUE TITLE
Switch AppImage to use linuxdeploy

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1752]
We need to update the AppImage builds:
- [ ] Switch to linuxdeploy https://github.com/linuxdeploy/linuxdeploy
    - [ ] For example https://github.com/linuxdeploy/linuxdeploy-plugin-qt
- [ ] Use Ubuntu 22.04 (e.g., last LTS)
- [ ] Build Qt6 deploy for testing

**Comment by Samueru-sama** [comment]
Consider switching to [go-appimage](https://github.com/probonopd/go-appimage) instead. 

It has a deploy everything mode that makes the appimage be able to work on any linux system, be it  15 year old or even musl distros.

[some examples here](https://github.com/AlexanderP/tesseract-appimage/issues/3)

This also makes it far more flexible for building as you can even pick a rolling release distro.

**Comment by ghutchis** [comment]
I tried `go-appimage` and it crashed, while at least for now `linuxdeploy` works.
