### ISSUE TITLE
Add option to transform relative to specific atom and to true origin (or arbitrary point?)

### ISSUE THREAD

**Issue by matterhorn103** [OpenChemistry/avogadrolibs#1756]
See #1755 for background.

Two options for the transformation centre used by the Manipulation Tool would be nice:

1. "Specific atom" and then a drop-down list of atom indices
2. A genuine "Origin" – the current "Origin" option doesn't actually result in rotation around the origin. Ideally the option to use 0,0,0 would be there.

(Alternatively to 2), the user could be given the ability to provide coordinates of the centre to use, which would cover the origin use case while being more flexible.)

**Comment by ghutchis** [comment]
I think for the "specific atom" is just a special case of a selection - select one atom. So for ease-of-use, I'd rather not have a drop-down list of atom indices -- it could get quite long and then the user needs to know what atom 42 is (with a potential off-by-one error. ;-)

So I'm going to close this, since I mention the need for the "true origin" in #1755

**Comment by matterhorn103** [comment]
But only the selected atoms get transformed, so it isn't possible to do it the way you suggest. The selection determines which atoms move, while the drop-down choices determine the centre they are moved with respect to. So you could select a single atom and then choose the "centre of selection" option, sure, but the result would be the single atom rotating relative to its own centre doesn't make a whole lot of sense.

**Comment by ghutchis** [comment]
Fair point. Let me think about this. I don't think a drop-down menu is the solution, but maybe it has a checkbox or option to move either the selected or unselected atoms.

**Comment by matterhorn103** [comment]
I mean this was inspired by the bloke on the forum that I wrote that plugin for. I could imagine it being useful to be able to build a complex with two complicated ligands at axial positions and then put solvent ligands in the other coordination sites by rotating them round the metal atom centre, for example. So I was thinking how that sort of thing could be enabled.
