### ISSUE TITLE
构建时 Qt5 引用未定义的问题

### ISSUE THREAD

**Issue by jiuzhi1234** [OpenChemistry/avogadrolibs#1760]
在使用 Qt6 编译 avogadrolibs 时，发现 mocs_compilation.cpp 和 obprocess.cpp 文件中存在未定义的 QRegExp 引用错误。这导致 libAvogadroMoleQueue.so 和 libAvogadroQtPlugins.so 在链接步骤失败。错误信息如下所示：

/usr/bin/ld: CMakeFiles/MoleQueue.dir/MoleQueue_autogen/mocs_compilation.cpp.o: in function `QList<QRegExp>::erase(QList<QRegExp>::const_iterator, QList<QRegExp>::const_iterator) [clone .isra.0]':
mocs_compilation.cpp:(.text+0x1628): undefined reference to `QRegExp::~QRegExp()'
/usr/bin/ld: CMakeFiles/MoleQueue.dir/MoleQueue_autogen/mocs_compilation.cpp.o: in function `QtPrivate::QDataStreamOperatorForType<QRegExp, true>::dataStreamIn(QtPrivate::QMetaTypeInterface const*, QDataStream&, void*)':
mocs_compilation.cpp:(.text._ZN9QtPrivate26QDataStreamOperatorForTypeI7QRegExpLb1EE12dataStreamInEPKNS_18QMetaTypeInterfaceER11QDataStreamPv[_ZN9QtPrivate26QDataStreamOperatorForTypeI7QRegExpLb1EE12dataStreamInEPKNS_18QMetaTypeInterfaceER11QDataStreamPv]+0x7): undefined reference to `operator>>(QDataStream&, QRegExp&)'
/usr/bin/ld: CMakeFiles/MoleQueue.dir/MoleQueue_autogen/mocs_compilation.cpp.o: in function `QtPrivate::QDataStreamOperatorForType<QRegExp, true>::dataStreamOut(QtPrivate::QMetaTypeInterface const*, QDataStream&, void const*)':
mocs_compilation.cpp:(.text._ZN9QtPrivate26QDataStreamOperatorForTypeI7QRegExpLb1EE13dataStreamOutEPKNS_18QMetaTypeInterfaceER11QDataStreamPKv[_ZN9QtPrivate26QDataStreamOperatorForTypeI7QRegExpLb1EE13dataStreamOutEPKNS_18QMetaTypeInterfaceER11QDataStreamPKv]+0x7): undefined reference to `operator<<(QDataStream&, QRegExp const&)'

此外，还发现涉及 QOpenGLWidget 和 QOpenGLFramebufferObject 的未定义引用错误。为了解决这些问题，暂时在链接命令中手动添加了 libQt6Core5Compat.so 和 libQt6OpenGLWidgets.so。

**Comment by ghutchis** [comment]
Please make sure you're using both the latest HEAD for both `avogadrolibs` and `avogadroapp` when building. Both of these have been resolved using recent pull requests.

**Comment by ghutchis** [comment]
Does this still show up in the latest HEAD? If not, I'm going to close this in a week. Thanks.

**Comment by ghutchis** [comment]
I'm going to close this - if you're still having problems with the latest `HEAD` from git, please open a new issue.
