### ISSUE TITLE
 shortcut keys for better navigation in computer software

### ISSUE THREAD

**Issue by mmSamyak** [OpenChemistry/avogadrolibs#1764]
In the software, there is a need for some shortcut keys to navigate in 3D space. Add a feature by which the user should be able to view the bonds in 3D space by pressing "alt" key and hovering the mouse.

**Comment by ghutchis** [comment]
I'm not sure I understand what you mean. You can already view bonds in 3D space. Can you be a bit more specific about what you want?

**Comment by ghutchis** [comment]
I'm going to close this for lack of information. If you can provide more details about what you want, I'm happy to re-open.
