### ISSUE TITLE
BUG: Found an assignment bug in cmlformat.cpp

### ISSUE THREAD

**Issue by TactfulDeity** [OpenChemistry/avogadrolibs#1776]
In `avogadro/io/cmlformat.cpp` on line 209 [here](https://github.com/OpenChemistry/avogadrolibs/blob/91489fe119d23a846b3d987dad29249c4fb7110a/avogadro/io/cmlformat.cpp#L209), there is a assignment bug in the if statement. Instead of checking with `==` it has `=`. I have a fix for this on a large local branch with a number of other code clean ups, I want to make a post here in case it needs to get in sooner or at least make sure it is a known issue. 

If it is not a pressing issue I will reference this bug when I open my PR.

**Comment by ghutchis** [comment]
It's a bug for sure, but it will only pop up with handling certain types of crystal structures in the CML file format. I'd guess it's a small fraction of people, which is why it hasn't been noticed before.

**Comment by TactfulDeity** [comment]
Im preparing to open a PR with the fix now

**Comment by TactfulDeity** [comment]
This is actually an intentional assignment being done in an if statement, I am going to modify the code to be more clear in its evaluation. **This is not actually a bug**
