### ISSUE TITLE
Add Shortcut Keys to navigate/modify molecules

### ISSUE THREAD

**Issue by Milziade** [OpenChemistry/avogadrolibs#1794]
It would be very useful to have shortcut keys to move faster between molecule editing tools (navigation, draw, selection, measure, ...)
By now I have to click on tool's button to change tool, but it would save a lot of time to have some shortcut (e.g. `Alt + 1` for Navigation tool, `Alt + 2` for Draw and so on)
The best would be to add Preference submenu (maybe under File menu?) where you can configure your own shortcut, but I think a good start would be to add these shortcut

Thank you for taking in consideration such suggestion!

**Comment by ghutchis** [comment]
It already exists. Control + 1, Control + 2, etc.

**Comment by Milziade** [comment]
Oh I see... Thank you!
I think it would be useful to add these shortcut in the button description, it would be easier for novice (like me) to find out.
I'll try to change the description and submit a pull request if it works

P.s. Reading the [Navigator.ccp file](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/navigator/navigator.cpp), I found that you can use WASD / arrow keys / ... for a more precise rotation, maybe a pop-up with _Tips & Tricks_ containing such info would be useful (similar to the LibreOffice ones)

**Comment by matterhorn103** [comment]
> I think it would be useful to add these shortcut in the button description, it would be easier for novice (like me) to find out.
> I'll try to change the description and submit a pull request if it works

Yes, definitely, this is something I've been meaning to add ever since I myself learnt about the shortcuts. The tooltips need a little bit of work anyway but it would be really great if you could add the shortcuts to the tooltips!

> P.s. Reading the [Navigator.ccp file](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/navigator/navigator.cpp), I found that you can use WASD / arrow keys / ... for a more precise rotation, maybe a pop-up with _Tips & Tricks_ containing such info would be useful (similar to the LibreOffice ones)

That also reminds me to add that to the documentation for the Navigation Tool, thanks.

**Comment by Milziade** [comment]
Hi! I just created [pull request](https://github.com/OpenChemistry/avogadrolibs/pull/1807) with these small changes. 
Feel free to tell me if anything is wrong

Thank you for your time

**Comment by Milziade** [comment]
Fixed as requested. I tested it on Linux machine with Ctrl key, if anyone can test it on Mac  would be great
