### ISSUE TITLE
Bug: MO-plot

### ISSUE THREAD

**Issue by jkn93** [OpenChemistry/avogadrolibs#180]
in file:  avogadrolibs/avogadro/core/gaussiansettools.cpp
line 66:   int indexMO(mo - 1);

The index 'mo' is already in the range of [0,#mo-1], i.e., the plotted MOs are shifted
down by one and show, e.g., the HOMO if the LUMO is requested.
The program also crashes if the 1st MO is supposed to be plotted.

**Comment by cryos** [comment]
Thanks, I know this used to work as I have an ancient benzene calculation where I love the shapes in the highest MO, but I think in some of the refactoring we went from a 0 to 1-based index and I missed it. Should be fixed in #188, I could reproduce the crash you described before I applied the fix.

**Comment by cryos** [comment]
This is now resolved.
