### ISSUE TITLE
Molecular orbital rendering with Flying Edges is incorrect (negative mesh)

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#1827]
Here's a rendering of the LUMO for benzene (file is attached - unzip to get benzene.fchk):
<img width="250" alt="Screenshot 2024-11-28 at 7 20 43 PM" src="https://github.com/user-attachments/assets/e402b78b-8a06-4359-ade9-5aec2bd56a32">

With the current code, I get a very different look:
<img width="336" alt="Screenshot 2024-11-28 at 7 22 43 PM" src="https://github.com/user-attachments/assets/b9fab27c-22e9-4a87-b5ae-0a542239d8b6">

The problem is with the mesh for the negative isosurface (it's the `mesh2` in the code). The code sets m_reverseWinding and inverts the iso value (i.e., not 0.03 but -0.03)

For example, the triangles are a bit weird too:
<img width="376" alt="Screenshot 2024-11-28 at 7 28 06 PM" src="https://github.com/user-attachments/assets/3e70fc76-7478-4537-96cc-d5c6bb71ae97">

[benzene.fchk.zip](https://github.com/user-attachments/files/17953057/benzene.fchk.zip)

**Comment by ghutchis** [comment]
@perminder-17 - any thoughts on this? It seems as if the Flying Edges is gluing together the two parts of the mesh even though the isovalues are very small.

**Comment by perminder-17** [comment]
Hmm..probably the issue behind is with `m_reverseWinding`. I'll check it very soon, in marching cubes algorithm we sets the vertices and normals by looking at the `m_reverseWinding` but in flying-edges I think I have missed that. I'll fix it very soon, Sorry for the oversight.

**Comment by ghutchis** [comment]
No worries, I should have tested more carefully. I'm just working towards a release in mid-December, so everything is getting tested more rigorously.
