### ISSUE TITLE
Orbitals toolbar not auto-opening and molecular orbitals not displayed on .chk file import

### ISSUE THREAD

**Issue by TristanClay** [OpenChemistry/avogadrolibs#1860]
**Avogadro version :**
 - Avogadrolibs: 1.99.0
 - Qt: 5.15.8
 - SSL Version: Secure Transport, macOS 15.1

**Desktop version: **
 - OS: MacOS
 - Version15.1.1 (24B91)

**Describe the bug**
When importing .chk files into the software, the Orbitals toolbar fails to open automatically, which is a critical feature for visualizing molecular orbitals. As a result, the molecular orbitals are not displayed in the calculation results, preventing users from analyzing the data as intended.

This issue disrupts the workflow significantly, as users are forced to manually open the Orbitals toolbar, which is not only time-consuming but also increases the likelihood of errors. The lack of automatic toolbar opening and molecular orbital display is a deviation from the expected behavior and impacts the usability of the software.

**To Reproduce**
1. Import .chk File: Navigate to the file menu and select the option to import a .chk file. Choose a .chk file that you expect to contain molecular orbital data.
2. Check for Toolbar Activation: After the file has been imported, observe whether the Orbitals toolbar opens automatically.
3. Review Calculation Results: If the Orbitals toolbar opens, proceed to check the calculation results for the display of molecular orbitals. If it does not open, manually open the Orbitals toolbar and then check for the molecular orbitals.

**Expected behavior**
- Automatic Toolbar Opening: The Orbitals toolbar should automatically open or become accessible without requiring manual intervention from the user. This is a standard feature designed to enhance user experience and streamline the workflow for analyzing molecular orbitals.
- Display of Molecular Orbitals: Once the .chk file containing molecular orbital data is successfully imported, the software should correctly parse and display the molecular orbitals in the calculation results section. Users should be able to view, manipulate, and analyze these orbitals as part of the software's intended functionality.

**Screenshots**
A screenshot after the .chk file has been imported, showing that the Orbitals toolbar has not opened automatically. This screenshot should clearly show the absence of the toolbar or any indication that it should have opened.
<img width="1470" alt="Screenshot 2024-12-11 at 00 23 48" src="https://github.com/user-attachments/assets/1f4343a1-411a-4f63-83be-a5df47344d93">

**Comment by ghutchis** [comment]
It's not a bug. It's not implemented yet. https://github.com/OpenChemistry/avogadrolibs/issues/1669
