### ISSUE TITLE
i want the chemical structure of interaction between water and calcite

### ISSUE THREAD

**Issue by marziyeh-sarlak** [OpenChemistry/avogadrolibs#1875]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish Avogadro calculated XYQ moments to render with ..

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please be detailed. How might this feature work (e.g., first a window would open and you'd click to …)

**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
This is not a feature or bug request for Avogadro. If you'd like to ask how to calculate that, as indicated above, you can post on the forum https://discuss.avogadro.cc/ or other sites (e.g., https://mattermodeling.stackexchange.com/)
