### ISSUE TITLE
Very slow for large file to perceive rings

### ISSUE THREAD

**Issue by zhangfq-chemistry** [OpenChemistry/avogadrolibs#1883]
Qt: (6.8.0)/Ubuntu22
I test that it is this function runs slowly.

std::vector<std::vector<size_t>> perceiveRings(const Graph& graph)
{
 ......
//very slow here 
  for (size_t k = 0; k < n; ++k) {
    for (size_t i = 0; i < n; ++i) {
      for (size_t j = 0; j < n; ++j) {
        if (i == j || i == k || k == j)
          continue;

        if (D(i, j) > D(i, k) + D(k, j)) {
          if (D(i, j) == D(i, k) + D(k, j) + 1)
            Pt(i, j) = P(i, j);
          else
            Pt(i, j).clear();

          D(i, j) = D(i, k) + D(k, j);
          P(i, j) = P.splice(i, k, j);
        } else if (D(i, j) == D(i, k) + D(k, j)) {
          P.addPaths(i, j, P.splice(i, k, j));
        } else if (D(i, j) == D(i, k) + D(k, j) - 1) {
          Pt.addPaths(i, j, P.splice(i, k, j));
        }
      }
    }
  }
......

**Comment by ghutchis** [comment]
At the moment, this ring perception code is not used internally. If you want good ring perception code, I suggest using either Open Babel or RDKit.

It's certainly my intent to replace this old code in `avogadrolibs` before any sort of aromaticity perception.

**Comment by zhangfq-chemistry** [comment]
Thanks!
