### ISSUE TITLE
suggestion for QTAIMODEIntegrator::r8_rkf45

### ISSUE THREAD

**Issue by serval2412** [OpenChemistry/avogadrolibs#2]
Hello,

By running cppcheck (a C/C++ static analyzer) on sources, I noticed this:
[libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp:959]: (error) Memory leak: f1
[libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp:959]: (error) Memory leak: f2
[libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp:959]: (error) Memory leak: f3
[libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp:959]: (error) Memory leak: f4
[libavogadro/src/extensions/qtaim/qtaimodeintegrator.cpp:959]: (error) Memory leak: f5

First I thought adding appropriate delete [] but then I noticed that the initialization of f1, f2, ... f5 could be delayed a bit.
Instead of line 937...94, it could be line 1049, just before the big for loop.
It would allow to avoid to alloc memory for nothing in case of return 2 cases (line 952 and 1035) + return 7 case (line 1015) so perhaps gain some perf.

Julien

**Comment by ghutchis** [comment]
Patches welcome. (Similarly if people want to run cppcheck and other analyzers on the code, this would be great.)
