### ISSUE TITLE
Optimize Geometry - "Error interpreting obabel MDL output"

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#203]
_From @1ykos on August 14, 2017 14:12_

Freshly pulled from git and compiled without errors trying to optimize geometry produces the stated error: "Error interpreting obabel MDL output".
It seems the way in which obabel is invoked is wrong.
`OBProcess::executeObabel: Running "/home/usr/bin/openchemistry/prefix/bin/obabel" "-imol -omol --minimize --log --crit 1e-6 --ff GAFF --steps 2500 --rvdw 10 --rele 10 --freq 10"
MDL: "Open Babel 2.4.1 -- Aug 14 2017 -- 14:41:50\nUsage:\nobabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]\nTry  -H option for more information.\n"` 
the zlib linking issue in obabel (26) could also be the cause.

_Copied from original issue: OpenChemistry/avogadroapp#62_

**Comment by ghutchis** [comment]
_From @cryos on August 14, 2017 15:3_

This works locally, checked and I am using the same version of obabel on Linux here. I wonder if it is related to that, or error checking if the optimization can't complete for some reason. If the forcefield plugin doesn't load it may then not recognize the option.

**Comment by ghutchis** [comment]
(bump)

**Comment by ghutchis** [comment]
@1ykos - if this is still a problem, please respond. It works for me, and I'd like to resolve old issues.

**Comment by 1ykos** [comment]
I have since upgraded to a different opensuse version. I will try tomorrow and will let you know if it workes or not.
If I remember correctly it could be resolved by
export BABEL_LIBDIR=/usr/lib64/openbabel/2.3.2/

**Comment by maalbadri** [comment]
Hi, I'm having this issue with all obabel dependencies. Tried to follow @1ykos library path to both my local anaconda openbabel as well as the Avogadro2.app content on Mac OS.

Running latest Avogadro2 and Mac OS 10.14.6.

**Comment by frda058** [comment]
Hi, still getting this error when optimizing geometry on Avogadro2. Can anyone please advise a fix?
<img width="374" alt="Screen Shot 2020-07-07 at 1 38 43 PM" src="https://user-images.githubusercontent.com/67458938/86820597-45906480-c057-11ea-93df-74292c3b42df.png">

**Comment by ghutchis** [comment]
@frda058 - this is a closed bug report so if you're having problems, it's better to start a new issue. However, I'd suggest trying this build for mac: https://github.com/OpenChemistry/avogadrolibs/suites/648275435/artifacts/5525298
