### ISSUE TITLE
"Reset View" Command

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#221]
Avogadro v1 had a feature to reset the view - computing the best-fit plane through the molecule. This also included an animation as the view twisted into position and zoom.

Another useful feature is the Reset View to Axes - rather than calculate the best-fit plane, the view resets to display the XY plane.

**Comment by ghutchis** [comment]
I have an initial template here, but don't have time to finish it:
https://gist.github.com/ghutchis/d53469f38887074eb63017bdaf590c0a

**Comment by serk12** [comment]
Hi, I'm almost done with this issue but I'm facing some problems with the animation. 
I'm using a QTimer to update the camera view model but it doesn't update the scene, any solution?

**Comment by cryos** [comment]
You might have to show code, but only the camera should need to be changed. I am not clear on what you mean by it doesn't update the scene. Maybe you need a call to render to actually show the updated camera position?

**Comment by serk12** [comment]
Ups sorry. Yes, here is the code https://github.com/serk12/avogadrolibs/blob/issue-221/avogadro/qtplugins/resetview/resetview.cpp
To be more exactly the problem is here:
`  QTimer::singleShot(alpha*1000, this, [this, interpolation] (){ m_camera->setModelView(interpolation); });`
My theory is that the Action threads dies before this happen and it doesn't call the update render, but I don't know how to call it.

**Comment by ghutchis** [comment]
@serk12 - sorry I missed your comment - at the first step, let's skip the animation and make sure the camera is set correctly and re-renders. If so, please submit a PR - the animation is secondary.

When we implemented this in Avo1, we did it the opposite way:
https://github.com/cryos/avogadro/blob/79d22168cb8c5a874189bebf16f7270871f3c469/avogadro/src/mainwindow.cpp#L2753

In that code, the class kept a permanent QTimer that would periodically call the interpolation method - and in turn update the camera.

As far as needing to call for an explicit re-render,  I'm not sure. The code in `avogadro/qtplugins/navigator/navigator.cpp` doesn't do that, but that's called through Qt events so it's inherently part of the render loop anyway.

**Comment by ghutchis** [comment]
Thanks to @serk12 - this is now merged.
