### ISSUE TITLE
Selection Commands

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#224]
The Select menu could use some additional simple commands ported from Avogadro v1:

* Select by Element - pop up the periodic table and select all atoms of a given element
* Select by Residue (requires #58)

**Comment by ghutchis** [comment]
Select water would be a great addition too (i.e., loop through all the oxygen atoms and check if they're part of a water)

**Comment by grindhold** [comment]
tomorrow morning my debian updated to avogadro  1.91.0-2 (although the about screen says 1.90.0). according to the docs there should be some content in the dockable tool-settings dialog when i select "selection" as a tool. unfortunately mine is empty. i only have content in the field when i select either the "draw" or the "player" tool. !(image)[https://i.imgur.com/5BrDeML.png]
