### ISSUE TITLE
fileformatScripts require Molequeue

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#241]
From https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/scriptfileformats/CMakeLists.txt

```
# Pull in MoleQueue -- just for QtJson right now...
find_package(MoleQueue REQUIRED NO_MODULE)
include_directories(${MoleQueue_INCLUDE_DIRS})
```

Why should writing an IO script require Molequeue?

**Comment by cryos** [comment]
It was for QJson (mentioned in the comments in the CMake file). Removing, I will let the buildbot confirm, but worked locally with removal of the CMake lines requiring MoleQueue.
