### ISSUE TITLE
GLSL code is re-processed with every build

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#250]
It's not a huge deal, but a pain when building frequently during development...

```
Adding cylinders_fs.glsl to encoder... /Users/ghutchis/Devel/openchemistry/avogadrolibs/avogadro/rendering/cylinders_fs.glsl /Users/ghutchis/Devel/build/openchemistry/avogadrolibs/avogadro/rendering/cylinders_fs.h cylinders_fs
Adding cylinders_vs.glsl to encoder... /Users/ghutchis/Devel/openchemistry/avogadrolibs/avogadro/rendering/cylinders_vs.glsl /Users/ghutchis/Devel/build/openchemistry/avogadrolibs/avogadro/rendering/cylinders_vs.h cylinders_vs
…
```

Is there a way to ensure that the products (headers) are only built any time the GLSL code changes?

**Comment by cryos** [comment]
There probably is, I will try and take a look when I get a chance. It is mildly irritating, I can at least make it quieter.

**Comment by cryos** [comment]
So #254 makes this quieter, this was debug code I had meant to remove long ago. They are not actually getting reprocessed on each cmake run - I just verified 

`-rw-r--r-- 1 marcus users  566 Mar 22 09:53 mesh_fs.h`

Rerunning CMake is not modifying them, and rebuilds are not being triggered needlessly.
