### ISSUE TITLE
QVTKOpenGLWidget.h not found

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#253]
I tried USE_VTK for the build settings and after building VTK, I get the following build error. (I don't have VTK installed anywhere.)

```
/Users/ghutchis/Devel/openchemistry/avogadrolibs/avogadro/qtplugins/plotxrd/xrdvtkplot.cpp:30:10: fatal error: 
      'QVTKOpenGLWidget.h' file not found
#include <QVTKOpenGLWidget.h>
         ^~~~~~~~~~~~~~~~~~~~
```

**Comment by cryos** [comment]
You should turn on VTK at the superbuild level, and that should offer a minimal VTK with what is needed. You can of course copy the configuration options and build your own VTK. I am eager to get this made as simple as possible, so appreciate testing.

**Comment by ghutchis** [comment]
That's what I did, which is why I flagged an issue. Busy today, but I'll check it out tomorrow.

**Comment by cryos** [comment]
That is strange, just checking and here avogadrolibs triggers a VTK build (it is an optional dependency based on the flag). VTK built, and then avogadrolibs built using the VTK from the prefix. I am guessing this is a macOS build, I can trigger a build on my test machine to see if something platform specific is amiss. It would be good to know `prefix/include/vtk-9.0/` exists when you get a chance.

**Comment by ghutchis** [comment]
I have vtk-7.1.

**Comment by cryos** [comment]
That is way too old, git submodule update should have updated VTK, and the external build should have then configured it correctly.

**Comment by cryos** [comment]
Although looking again now, it looks like maybe my SHA update for VTK never got merged. I see b8076a from 2015. I will fix it.

**Comment by psavery** [comment]
Indeed, on my Mac (High Sierra), I just tried recursively cloning open chemistry and building it from scratch with the following cmake flags (I have to specify the qt directory for mine):

`cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/ -DUSE_VTK=ON`

and it appeared to build successfully.

Not too long ago, Marcus updated the VTK submodule. I think updating your VTK submodule will hopefully fix it.

**Comment by cryos** [comment]
I thought I was going crazy, but was on an old branch on that machine, commit 2e1fdefdbc7fd6ff107959c6c93a02c9c702da7e in the openchemistry repo updated VTK and the build flags. I can see it on master too.

**Comment by cryos** [comment]
Trying a clean build on my macOS machine I am seeing issues with the new libmsym find calls, so the error on the build machine may have been correct.

**Comment by ghutchis** [comment]
Yeah, I'm seeing weirdness here with finding things.

**Comment by cryos** [comment]
I just pushed avogadrolibs forward for some tweaks to the find libmsym logic, this now compiles, but on the Mac the OpenGL context will be broken until the new QVTKOpenGLWidget code is merged. There is a merge request, and if they take a while I can literally copy that file to our repository as it is just one class.

**Comment by ghutchis** [comment]
(bump) - can we close this one?

**Comment by ghutchis** [comment]
@cryos and @psavery - looks like this is merged now? If not, can you link to the merge request so I can close when it's finished?

**Comment by psavery** [comment]
Yes, I think this can be closed now. To fix this issue just required a "git pull origin master" in the openchemistry superbuild repository, I believe.

[Here](https://github.com/OpenChemistry/openchemistry/commit/2e1fdefdbc7fd6ff107959c6c93a02c9c702da7e) is where VTK was fast-forwarded.
