### ISSUE TITLE
Bond tolerance option to calculate bonds

### ISSUE THREAD

**Issue by ladyteam** [OpenChemistry/avogadrolibs#256]
For a more flexible calculations of bonds based on covalence radius the good idea to add tolerance options controlled by user. Some compounds obtains a very small distance between atoms and this leads to a number of extra bonds calculated wich are in fact not exist. The other structures obtains a distance between atoms is too far and the bonds are not added. Thus two options namely “Bond tolerance” and “Minimal bonding distance” for user to control correct bond calculation would be very very helpful. Such approach is implemented in JMOL visualization software and is frequencely used by users.

Friendly, Eugene

**Comment by ghutchis** [comment]
I intend to implement this in the next few days. Can you give me an example file? Thanks.

**Comment by ghutchis** [comment]
The code for detecting bonds is in https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/core/molecule.cpp#L707

This method could use parameters as suggested by the user with a default of 0.0 for the current behavior.

After that, some commands should be added to the menus as a submenu:
- Remove bonds (i.e., remove all bonds to selected atoms)
- Connect atoms (i.e., remove any bonds and re-perceive bonds to selected atoms)

Later, perceive bond orders can be added
