### ISSUE TITLE
Build error while building avogadrolibs

### ISSUE THREAD

**Issue by badarsh2** [OpenChemistry/avogadrolibs#257]
I encountered the following error while building avogadrolibs:

`[ 87%] Building CXX object avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp: In member function ‘void Avogadro::QtPlugins::Symmetry::detectSymmetry()’:
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:270:62: error: invalid conversion from ‘const msym_symmetry_operation_t** {aka const msym::_msym_symmetry_operation**}’ to ‘msym::msym_symmetry_operation_t** {aka msym::_msym_symmetry_operation**}’ [-fpermissive]
       (ret = msymGetSymmetryOperations(m_ctx, &msopsl, &msops))) {
                                                              ^
In file included from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/operationstablemodel.h:22:0,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.h:31,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.h:22,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:17:
/home/adarsh/Documents/Github/openchemistry-build/prefix/lib/cmake/libmsym/../../../include/libmsym/msym.h:182:30: note:   initializing argument 3 of ‘msym::msym_error_t msym::msymGetSymmetryOperations(msym::msym_context, int*, msym::msym_symmetry_operation_t**)’
     msym_error_t MSYM_EXPORT msymGetSymmetryOperations(msym_context ctx, int *s
                              ^
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:315:67: error: invalid conversion from ‘const msym_subgroup_t** {aka const msym::_msym_subgroup**}’ to ‘msym::msym_subgroup_t** {aka msym::_msym_subgroup**}’ [-fpermissive]
     if (MSYM_SUCCESS != (ret = msymGetSubgroups(m_ctx, &msgl, &msg))) {
                                                                   ^
In file included from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/operationstablemodel.h:22:0,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetrywidget.h:31,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.h:22,
                 from /home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:17:
/home/adarsh/Documents/Github/openchemistry-build/prefix/lib/cmake/libmsym/../../../include/libmsym/msym.h:180:30: note:   initializing argument 3 of ‘msym::msym_error_t msym::msymGetSubgroups(msym::msym_context, int*, msym::msym_subgroup_t**)’
     msym_error_t MSYM_EXPORT msymGetSubgroups(msym_context ctx, int *l, msym_su
                              ^
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:198:15: warning: unused variable ‘error’ [-Wunused-variable]
   const char* error = NULL;
               ^
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:200:31: warning: unused variable ‘symerr’ [-Wunused-variable]
   double cm[3], radius = 0.0, symerr = 0.0;
                               ^
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:206:39: warning: unused variable ‘mlength’ [-Wunused-variable]
   int mesl = 0, msgl = 0, msopsl = 0, mlength = 0;
                                       ^
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp: In member function ‘void Avogadro::QtPlugins::Symmetry::symmetrizeMolecule()’:
/home/adarsh/Documents/Github/openchemistry/avogadrolibs/avogadro/qtplugins/symmetry/symmetry.cpp:369:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (mlength != length)
               ^
avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/build.make:66: recipe for target 'avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o' failed
make[5]: *** [avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/symmetry.cpp.o] Error 1
CMakeFiles/Makefile2:4141: recipe for target 'avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/all' failed
make[4]: *** [avogadro/qtplugins/symmetry/CMakeFiles/Symmetry.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/avogadrolibs.dir/build.make:119: recipe for target 'avogadrolibs-prefix/src/avogadrolibs-stamp/avogadrolibs-build' failed
make[2]: *** [avogadrolibs-prefix/src/avogadrolibs-stamp/avogadrolibs-build] Error 2
CMakeFiles/Makefile2:146: recipe for target 'CMakeFiles/avogadrolibs.dir/all' failed
make[1]: *** [CMakeFiles/avogadrolibs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by cryos** [comment]
Update the superbuild, and rebuild libmsym, the API changed I am afraid in an incompatible way. Please reopen if updating libmsym does not resolve the issue.
