### ISSUE TITLE
Crash when measuring more than two atoms

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#270]
_From @jevandezande on June 14, 2017 12:46_

Avogadro2 crashes when I attempt to measure more than two atoms. The first two atoms can be selected and the distance between them appears; however, upon selecting the third atom the program crashes with the following output:

```
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
zsh: segmentation fault (core dumped)  ./avogadro2 ~/tmp/orca/IrCl6/geom.xyz
```

This happens no matter what atoms I try to measure: on symmetric and asymmetric molecules, when I load a file from the command line as while as within the app using `open`, and when I measure bonded or non-bonded distances.

Here is the full output I get when running avogadro:
```
Extension plugins dynamically found... 24
OBProcess::executeObabel: Running "obabel" "-L formats read"
OBProcess::executeObabel: Running "obabel" "-L formats write"
OBProcess::executeObabel: Running "obabel" "-L forcefields"
OBProcess::executeObabel: Running "obabel" "-V"
"obabel"  found:  "obabel: Open Babel 2.3.2 -- Oct 24 2016 -- 09:36:56"
Checking for generator scripts in "/home/vandezande/.local/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/share/ubuntu/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/local/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/usr/share/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/var/lib/snapd/desktop/OpenChemistry/Avogadro/scripts/workflows"
Checking for generator scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/workflows"
Checking for generator scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for file format scripts in "/home/vandezande/progs/openchemistry-build/avogadroapp/bin/../lib/avogadro2/scripts/formatScripts"
SymmetryScene constructor
SymmetryScene::process
Missing origo or radius
"Navigator" added
"Editor" added
"Selection" added
"Manipulator" added
"BondCentric" added
"MeasureTool" added
"PlayerTool" added
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
SymmetryScene::process
Missing origo or radius
zsh: segmentation fault (core dumped)  ~/progs/openchemistry-build/avogadroapp/bin/avogadro2 geom.xyz
```

_Copied from original issue: OpenChemistry/avogadroapp#61_

**Comment by ghutchis** [comment]
What version are you using?

**Comment by ghutchis** [comment]
_From @jevandezande on June 16, 2017 12:19_

Sorry for the slow response, yesterday was a holiday here in Germany. I compiled from the Avogadro2 source on Ubuntu 17.04 using g++ 6.3.0, CMake 3.7.2, and Qt 5.7.1. I didn't notice any errors when compiling. I built from the Openchemistry supermodule following the instructions in the wiki.

Is there a way to run a testsuite on the program? I noticed mention of the `ENABLE_TESTS` flag in the wiki, but could not find directions on how to run tests.

**Comment by ghutchis** [comment]
_From @chicolucio on October 19, 2017 20:34_

Same problem here.

**Comment by ghutchis** [comment]
_From @ezavod on February 23, 2018 21:15_

Same here. Also crashes when holding left mouse button while moving (dragging) the mouse in drawing mode with similar error.
OS: openSUSE Tumbleweed 64bit
Avogadro2: 1.90.0-33-gd5e1f82
AvogadroLibs: 1.90.0-234-ga35df76
Qt: 5.10.0

**Comment by ghutchis** [comment]
@chicolucio and @jevandezande - I can't reproduce this. My first thought is that there's a divide by zero somewhere in the measure tool, but that's not obvious how that would happen.

If I create a branch with a different way to calculate the angle, would you be willing to try it?

**Comment by jevandezande** [comment]
I would be willing to test.
I just built a clean version of Avogadro2 and still had the same problem.

I used:
Ubuntu 18.04
G++ 7.20
Cmake 3.9.1
LibXml2 2.9.4
Qt 5.9.1

**Comment by ghutchis** [comment]
@jevandezande - what's your graphics driver? I'm wondering about this, likely related issue:
https://github.com/OpenChemistry/avogadrolibs/issues/67

Seems like the problem is in text rendering.

**Comment by jevandezande** [comment]
I'm using the default Intel HD 520 graphics drivers.

output from: `sudo lshw -c video`
``` 
*-display                 
       description: VGA compatible controller
       product: HD Graphics 520
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:126 memory:e0000000-e0ffffff memory:d0000000-dfffffff ioport:3000(size=64) memory:c0000-dffff```

**Comment by ghutchis** [comment]
@jevandezande - have you been able to reproduce this with more recent releases? I'm still unable to reproduce this.

If I don't hear back in a week, I'm going to close this - you can open a new bug if there are crashes.
