### ISSUE TITLE
Adapt AppImage from GitHub build

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#301]
@probonopd contributed an AppImage upload feature for Avogadro using a Travis build:
https://github.com/cryos/avogadro/pull/907

Assuming issues with Open Babel environment variables can be worked out, this seems like an excellent use for the Travis builds to provide pre-releases.

**Comment by probonopd** [comment]
Replacing AppRun with something like this should do the trick:

```
#!/bin/bash

# The purpose of this custom AppRun script is
# to export Open Babel environment variables
# before launching the application

HERE="$(dirname "$(readlink -f "${0}")")"

export BABEL_DATADIR=$(readlink -f "${HERE}/usr/share/openbabel/*/")
export BABEL_LIBDIR=$(readlink -f "${HERE}/usr/lib/openbabel/*/")

exec "${HERE}/usr/bin/avogadro" "$@"
```

**Comment by ghutchis** [comment]
Thanks - I don't have a Linux box handy, but I'll look at merging this, updating the script and we'll see if others can test.

**Comment by fusion809** [comment]
I'll be happy to test it out, I've got a heap of Linux installs I can try any AppImages ya build on. Virtual machines could be handy way for ya to test 'em out. 

[Bodhi Linux](https://www.bodhilinux.com/) might be a good distro to use in a virtual machine to test it out, as its installer is simple and its installation is pretty quick, but most importantly it is minimal. Minimalism might be handy as it means if your AppImage can run under it, it's almost guaranteed it'll also work on other distros as they tend to have more libraries and programs pre-installed. 

[MX Linux](https://mxlinux.org/) is another suggestion for a distro, its installer is even simpler and faster to use (which I'm guessing would be handy as I'd imagine you're busy and don't have time to waste installing a distro). It isn't as minimal as Bodhi, but still.

**Comment by cryos** [comment]
For Avogadro 2 we try to figure out the correct environment variables to help Open Babel find its plugins, etc. See avogadro/qtplugins/openbabel/obprocess.cpp with BABEL_DATADIR and BABEL_LIBDIR, we also did that in avogadro/src/main.cpp in Avogadro 1.x. I remember Open Babel kept changing things, and that would occasionally break. Maybe we just need to fix that as it is used on Windows, macOS, and Linux (at least in theory), and should remove the need for a wrapper script.

**Comment by ghutchis** [comment]
There's also `linuxdeployqt` here: https://github.com/probonopd/linuxdeployqt

At the moment, it requires Ubuntu 16.04, which had problems compiling everything. Hopefully the next release will support 18.04 LTS and we can build using the GitHub actions.

Another possibility now that it's on Flatpak, is `flatpak2appdir` - https://github.com/sudo-give-me-coffee/flatpak2appdir

**Comment by ghutchis** [comment]
Looks like this  might be a good approach (another  Qt-based app):
https://github.com/crow-translate/crow-translate/commit/4f8a1f41347442671ea07153dc00416476f39ec2

**Comment by probonopd** [comment]
> At the moment, it requires Ubuntu 16.04, which had problems compiling everything. Hopefully the next release will support 18.04 LTS and we can build using the GitHub actions.

Yes, the contious build supports that now.

**Comment by ghutchis** [comment]
@probonopd - thanks - I'll take a look tomorrow.

**Comment by probonopd** [comment]
Thank you @ghutchis - will the AppImage be available for download on GitHub Releases?

**Comment by ghutchis** [comment]
Yes, once we have our next release (probably a 1.95.2) it will show up on GitHub releases and I can add it to the hub.

For now, I'm testing to make sure it's not missing anything critical. 😄
