### ISSUE TITLE
Scripts not installed on MacOS

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#308]
I'm confused why the default scripts aren't installed on Mac, e.g.

```
install(PROGRAMS ${format_scripts}
  DESTINATION "${INSTALL_LIBRARY_DIR}/avogadro2/scripts/formatScripts/")
```

But there's no `lib` directory in my Mac app package so these are never run.

**Comment by cryos** [comment]
I will look into it, I thought that this was working in the packages, but it doesn't appear to work in the test packages I made the other day. I will look into it, and get it fixed up.

**Comment by cryos** [comment]
I just remembered that to make packages with everything pulled in you need to turn on INSTALL_BUNDLE_FILES in avogadroapp, then it has the Avogadro scripts, as well as some Open Babel files in lib. I verified this on the macOS build tree I have been experimenting with.

This is when using make package, I am not sure how you mean, they also end up in the prefix Avogadro2.app if you turn on that flag. The macOS install tree may benefit from defaulting that to ON, for other operating systems it is not needed.

**Comment by ghutchis** [comment]
Yes, this works. I'm getting some sleep, but I'll push a fix to `avogadroapp` to default to ON for Mac.

**Comment by ghutchis** [comment]
See https://github.com/OpenChemistry/avogadroapp/pull/86
