### ISSUE TITLE
RPMLint warning: /usr/lib/libAvogadroQtPlugins.so.1.91.0 calls exit(), which is strongly discouraged

### ISSUE THREAD

**Issue by fusion809** [OpenChemistry/avogadrolibs#317]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: latest commit, 1560 (02eeab3).
 - Qt: 5.11.1.

**Desktop version: (please complete the following information):**
 - OS: openSUSE Tumbleweed.
 - Version: 20180714.
 - Compiler: gcc 8.1.1. 

**Describe the bug**
I'm not much of a programmer, but the openSUSE Build Service's RPMLint program reports the warning (as opposed to error):

```bash
[  327s] avogadro2-libs.x86_64: W: shared-lib-calls-exit /usr/lib/libAvogadroQtPlugins.so.1.91.0 exit@GLIBC_2.2.5
[  327s] This library package calls exit() or _exit(), probably in a non-fork()
[  327s] context. Doing so from a library is strongly discouraged - when a library
[  327s] function calls exit(), it prevents the calling program from handling the
[  327s] error, reporting it to the user, closing files properly, and cleaning up any
[  327s] state that the program has. It is preferred for the library to return an
[  327s] actual error code and let the calling program decide how to handle the
[  327s] situation.
[  327s] 
```

so from what I understand of this warning /usr/lib/libAvogadroQtPlugins.so.1.91.0 calling exit() makes handling errors or bugs more challenging. This isn't a bug, _per se_, it's merely a warning that if rectified might make your jobs easier and aid future bug reporters in describing exactly what is wrong. 

**To Reproduce**
1. Clone my OBS repository: https://build.opensuse.org/package/show/home:fusion809/avogadro2-libs with (assuming `osc` is installed):

```bash
osc co home:fusion809 avogadro2-libs
```

2. Run:

```bash
osc build openSUSE_Tumbleweed x86_64 --noverify
```

3. Look near the end of the log and lo and behold you should see this warning. 

**Additional context**
My full build log, although I don't think it'll be helpful here, is [here](https://gist.github.com/91514232d199d4c88e9aa674f01bca46). 

Thanks for your time and I hope this helps advance this fine project,
Brenton

**Comment by ghutchis** [comment]
This has now been fixed in #475
