### ISSUE TITLE
Support for beta orbitals

### ISSUE THREAD

**Issue by bryce-anderson** [OpenChemistry/avogadrolibs#33]
Currently there doesn't appear to be the ability to plot anything but alpha (I presume they are alpha) orbitals. Is there a plan to add this functionality in the future? 

Currently the rendering appears to be under some flux (issue #27) but after that is done, I don't mind attempting to add that functionality.

**Comment by cryos** [comment]
Yes, you are right. I think it would be great to add in that functionality, and would appreciate your help. Let's try and get this code merged in, and extend out our capabilities in dealing with electronic structure. I would be happy to give you any pointers you might need as you start looking into this.

**Comment by ghutchis** [comment]
Long time coming, but @cryos has added this in #318

**Comment by cryos** [comment]
Yes, I am sorry it took so long! It really wasn't that much code...
