### ISSUE TITLE
Use Map<atom name, atomic number> instead of Array<atom name> for storing atom names in residuedata

### ISSUE THREAD

**Issue by badarsh2** [OpenChemistry/avogadrolibs#344]
- As of now, the native .gro reader guesses the element name based on the PDB spec atom names and sets a `CustomElementMap`, which can be quite ambiguous at times (eg. HG** is considered as Mercury instead of Hydrogen). 
- The PDB reader recently implemented works as expected for most part, but there exists a popular variant of PDB called PQR (https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html#PQR) which does not explicitly contain the element name. 

To handle the above two issues, I feel it would be good to have a dictionary header mapping the PDB atom names to the respective elements. Probably it can be created using the same utility that creates the `residuedata` header.

**Comment by ghutchis** [comment]
Do you want to extend the `atomnames` to be a pair of name and atomic number?

**Comment by badarsh2** [comment]
Yes, that sounds good.
