### ISSUE TITLE
Failing moleculetest - bondByUniqueID

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#348]
The current Travis is failing out for all builds after #336. That merge was tested without #316 so ctest didn't show the failure.

I have no idea why the test is failing [qtgui/moleculetest.cpp#L544](https://github.com/OpenChemistry/avogadrolibs/blob/2c2afd3a947a30a16f847f5ba29affe3b5153d49/tests/qtgui/moleculetest.cpp#L544)
```
  EXPECT_FALSE(assign.bondByUniqueId(2).isValid());
```

The commit doesn't change anything in the qtgui/molecule class.

Help debugging this would be most welcome (e.g., how many bonds does the water molecule think it has at this point, etc.)

**Comment by cryos** [comment]
I can take a look at this, I have been traveling a lot, but will try to set some time aside to figure out what is wrong unless @psavery gets a chance to look into it before me.

**Comment by ghutchis** [comment]
Thanks - this is fixed by #349
