### ISSUE TITLE
Molecular orbitals change in CJSON

### ISSUE THREAD

**Issue by alesgenova** [OpenChemistry/avogadrolibs#386]
At OpenChemistry we are relying on avogadrolibs to convert from NWCHEM output to the CJSON format, which is used across all our tools.

In a recent [commit](https://github.com/OpenChemistry/avogadrolibs/commit/181aeba294b46187d183d6b663dc4d3ee2e8955e#diff-7f05a3cadcacb72aa4e85b9133f06ab4), the schema for the molecular orbital portion of the CJSON has drastically changed:

BEFORE:
```json
{
  "molecularOrbitals": {
    "numbers": [ ],
    "energies": [ ],
    "occupations": [ ]
  }
}
```

AFTER:
```json
{
  "orbitals": {
    "electronCount": 10,
    "moCoefficients": [ ]
  }
}
```

These two pieces of information are complementary and they can both be useful depending on the application. Is there a plan to bring the `numbers`, `energies`, `occupations` back?
The additional size would be negligible, considering that they are are arrays of length `N`, whereas `moCoefficients` is `N^2`, where `N` is the number of basis functions.

**Comment by cryos** [comment]
I will take a look, I forgot that we relied on some of these things, I made a number of updates to the electronic structure. I plan on bringing the occupations, energies, etc back yes.

**Comment by cryos** [comment]
Just confirming before I take a look at this, we want to bring back the arrays mentioned above, anything else? I will be taking a pass at the new JSON reader/writer code for CJSON, and hoping to tag a release soon to test out the binary Python wheel packaging.

**Comment by alesgenova** [comment]
At the moment the orbital select menu can make educated guesses about which orbitals are occupied if those arrays are missing.

However, if the arrays are preset it is be able to display additional information to the user.

So in short, yes, it would be good if these arrays were brought back.

Partially related to this, where is the `electronCount` key expected to be in the cjson tree? I think I saw it in two different places depending on file

**Comment by cryos** [comment]
I moved it to the orbitals object, that is where it is expected. I am going to work on cleaning this up and ensuring read/write are also consistent.

**Comment by cryos** [comment]
Merged, closing this issue.
