### ISSUE TITLE
AppVeyor should cache dependencies

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#388]
Right now, the AppVeyor build is hitting a 60-minute timeout on a consistent basis.

We should either use Chocolatey to install some packages or cache dependencies:
- https://www.appveyor.com/blog/2014/11/06/appveyor-with-a-hint-of-chocolatey/
- https://chocolatey.org
- https://www.appveyor.com/docs/build-cache/

My guess is that the build cache will be more useful..

**Comment by psavery** [comment]
I do like chocolatey, but unfortunately, it doesn't look like it has a lot of the dependencies for Avogadro2 (I don't see glew, zlib, hdf5, libxml2, or eigen). I'll try to figure out how we can use the build cache. Looks like it has a limit of 1 GB.

**Comment by psavery** [comment]
I have been looking at doing a build cache to relieve our 60-minute AppVeyor build. I think it is still a possibility to do, but it is a little tricky for a few reasons:

1. The directories and files are cached only at the end of a successful build. This may imply that the build needs to already be passing to use the cache, whereas ours is failing. In addition, anytime we needed to rebuild our cache, it would start timing out again.

2. We can set up dependencies for the cache, and if those dependencies are modified, the cache gets rebuilt. But most of these dependencies are in the OpenChemistry repo - not the avogadrolibs repo. Some of the possible dependencies in the OpenChemistry repo are: cmake/projects.cmake, cmake/External_*.cmake, and possibly several other files in the cmake/ directory of OpenChemistry.

3. I am not sure if we can cache and restore a part of the cmake build tree without re-building it again. I just haven't tested it yet.

Another idea: we could possibly make a separate repository for the avogadrolibs dependencies and have a separate build for that (which could use AppVeyor and upload the compiled dependencies to GitHub releases automatically or something) - and then AppVeyor on Avogadrolibs can download and use the compiled dependencies. That would separate the compilation of the dependencies from the compilation of Avogadrolibs. It's just an idea, though.

PR #392 might be "good enough" for now as well.

**Comment by ghutchis** [comment]
I'm going to close this, since it's specific to Appveyor and the new GitHub builds have much longer timeouts. I'll open a new issue about caching .. I think having a separate repo for dependencies might be helpful.
