### ISSUE TITLE
Plugin Destructors Never Get Called?

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/avogadrolibs#389]
Hi all,

I've been running some tests, and it seems to me that the plugin destructors do not actually get called.

I tested it out by trying to print a message in several different plugin destructors ([copypaste](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/copypaste/copypaste.cpp#L64), [openbabel](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/openbabel/openbabel.cpp#L102), [plotxrd](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/plotxrd/plotxrd.cpp#L54), and [select](https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/select/select.cpp#L53) were the ones I tried).

Can anyone else confirm this? I was going to use the destructors to help make sure the Vtk plot (in PR #379) gets closed when the program exits..
Patrick

**Comment by cryos** [comment]
Ancient bug, but fixed in https://github.com/OpenChemistry/avogadroapp/pull/363 where the MainWindow should be on the stack, and then the plugin instances should have a parent passed in. Verified that destructors are called and opened #1250 to fix a bug where a plugin was deleting the molecule.
