### ISSUE TITLE
Change default tool to navigation, if the cartesian editor is used to add atoms

### ISSUE THREAD

**Issue by Diazonium** [OpenChemistry/avogadrolibs#394]
It would be nice if the default tool would switch to navigation from the draw tool, when an empty document is populated via the cartesian editor.
I have accidentally started to add ethane molecules more times than I can count, after copy-pasting structures into the cartesian editor for a quick look. It is not a big deal, but happens often enough to be annoying.

**Comment by ghutchis** [comment]
I think I’d make a more specific use case - if file is empty, then switch to the navigation tool.

Use case:
- User starts with something, uses Cartesian Editor to tweak - keep whatever tool was used before
- User starts with empty file, pastes in Cartesians - switch to navigate tool

Does that seem reasonable?

**Comment by Diazonium** [comment]
Sure, that works as well.

**Comment by suryanshsrivastava** [comment]
@ghutchis Kindly review the pull request and merge

**Comment by ghutchis** [comment]
This is fixed (finally) by #593 for the 1.94 release.
