### ISSUE TITLE
Add option for anti-aliasing

### ISSUE THREAD

**Issue by Diazonium** [OpenChemistry/avogadrolibs#395]
While entirely cosmetic, adding an option for toggling anti-aliasing (or even better, adjusting its quality) would be really nice. Modern graphics hardware is very powerful, and even low-end integrated graphics solutions should have no issue doing anti-aliasing when small to medium sized datasets are loaded.

Options include:
SSAA (should be easy to do, just render at 2x/4x the resolution, then downscale to the final res, excellent quality, potentially problematic performance impact)
MSAA (should be a lot faster than SSAA, generally good quality, should also be easy to implement, I think OGL has built in support for it, it just needs to be enabled)
FXAA(extremely fast, poor quality, mostly just blurs the edges a little bit)

**Comment by ghutchis** [comment]
We’d generally be okay with bringing this back. General advice is here:
https://stackoverflow.com/questions/14474259/how-do-i-enable-multisampling-antialiasing-in-opengl-with-qt5

We tried it previously:
https://github.com/OpenChemistry/avogadroapp/commit/aa3d2eebed9cdd312158603d6bbc6e76948a6dfe#diff-af573dc8b85e9bb58929b8fd5b5f5331

I believe there were some issues with the approach, but that may have been a Qt bug.

**Comment by ghutchis** [comment]
@badarsh2 - do you remember what the bug with multi-sampling was?

**Comment by badarsh2** [comment]
Multisampling was causing trouble with the media exports; the graphics and video exports turned out to be corrupt. As a simple workaround, we had removed the `setSamples()` call in the `QSurfaceFormat` object.

**Comment by ghutchis** [comment]
It looks like there might be an option - keeping the default QSurfaceFormat at 0, but setting the format for the viewer widget to have samples.. 
https://stackoverflow.com/a/45109541/131896

**Comment by ghutchis** [comment]
BTW, I fixed the problem with media exports and the latest versions should have multisampling enabled by default.

I'm going to close this one.
