### ISSUE TITLE
 reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#400]
Getting these errors on FreeBSD 11.2 with clang-6:
```
/usr/ports/science/avogadrolibs/work/avogadrolibs-1.91.0/avogadro/rendering/meshgeometry.cpp:174:23: error: reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
                      reinterpret_cast<const GLvoid*>(NULL));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/usr/ports/science/avogadrolibs/work/avogadrolibs-1.91.0/avogadro/rendering/cylindergeometry.cpp:226:23: error: reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
                      reinterpret_cast<const GLvoid*>(NULL));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by cryos** [comment]
Do you know how this can be achieved on FreeBSD then? I wrote that code, and it works everywhere I have tested it.

**Comment by yurivict** [comment]
You should try compiling with the clang compiler.

**Comment by cryos** [comment]
I have in the past, I can take a look at that on Linux and see if I reproduce your issue. For macOS we use their clang compiler without issue.

**Comment by yurivict** [comment]
On FreeBSD ```NULL``` is defined as ```nullptr```.
Replacing it with ```0``` indeed eliminates the errors.

You should replace ```NULL``` with ```nullptr``` as described here: https://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced

**Comment by psavery** [comment]
@yurivict It's interesting that FreeBSD defines `NULL` as `nullptr`. The `reinterpret_cast` does not work with `nullptr` instead of `NULL` (see error output below where I replaced `NULL` with `nullptr` on my arch linux machine).

```
/home/patrick/src/openchemistry/avogadrolibs/avogadro/rendering/meshgeometry.cpp:174:62: error: invalid cast from type ‘std::nullptr_t’ to type ‘const GLvoid*’ {aka ‘const void*’}
                       reinterpret_cast<const GLvoid*>(nullptr));
```

@cryos Maybe we could replace the whole `reinterpret_cast<const GLvoid*>(NULL)` with `nullptr`? It compiles on my arch linux machine.

**Comment by cryos** [comment]
It seems like an odd decision on FreeBSD's part that isn't analogous to what was done on other platforms, but when I get a chance I can replace that with a 0. We have no testing on the BSD OSes, and so it is hardly surprising there might be issues. I see a number of reports filed, whilst it would be great to get working there I don't have time to dedicate to porting for BSD. If there are reasonable patches, or others do then that is great.

**Comment by yurivict** [comment]
I already ported it to FreeBSD, and there are working ports.

**Comment by cryos** [comment]
Then I would appreciate patches if they exist :smile:

**Comment by yurivict** [comment]
It still has the same problem:
```
/usr/ports/science/avogadrolibs/work/avogadrolibs-1.91.0-107-g60c69b0/avogadro/rendering/ambientocclusionspheregeometry.cpp:933:25: error: reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
                        reinterpret_cast<const GLvoid*>(NULL));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/avogadrolibs/work/avogadrolibs-1.91.0-107-g60c69b0/avogadro/rendering/ambientocclusionspheregeometry.cpp:1007:25: error: reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
                        reinterpret_cast<const GLvoid*>(NULL));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/avogadrolibs/work/avogadrolibs-1.91.0-107-g60c69b0/avogadro/rendering/ambientocclusionspheregeometry.cpp:1329:23: error: reinterpret_cast from 'nullptr_t' to 'const GLvoid *' (aka 'const void *') is not allowed
                      reinterpret_cast<const GLvoid*>(NULL));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```

**Comment by cryos** [comment]
This is why a patch would have been far more useful....
