### ISSUE TITLE
Shouldn't install static libs as plugins

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#401]
For example:
```
lib/avogadro2/staticplugins/BallStick.a
lib/avogadro2/staticplugins/BondCentric.a
lib/avogadro2/staticplugins/Bonding.a
lib/avogadro2/staticplugins/CoordinateEditor.a
lib/avogadro2/staticplugins/CopyPaste.a
```

FreeBSD 11.2

**Comment by cryos** [comment]
The default is to compile static, they can be compiled as dynamic too, and the reporter should consider switching their build to that. I don't see how installing these causes any harm, and if the packaging on a specific distro prefers not to then they should patch locally. Closing.

**Comment by cryos** [comment]
I misspoke, apologies... Change `BUILD_STATIC_PLUGINS` to OFF, `BUILD_SHARED_LIBS` defaults to ON, then you will get shared plugins.
