### ISSUE TITLE
Please add cmake variables USE_EXTERNAL_xx for projects (xx) that may exist as separate packages

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#402]
Particularly, ```jsoncpp``` has a package.
```libgwavi``` also has a package on Arch Linux. I can easily create one on FreeBSD.
In general, external package use should be preferred.

**Comment by cryos** [comment]
We have removed jsoncpp, and will not be using it in future. On the whole we have favored never bringing things in, but a few small utilities are in thirdparty. We should add switches to use system versions.
