### ISSUE TITLE
Please make python/ a separate sub-project, not an option of the main project

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#406]
```python/CMakeFiles.txt``` should define a standalone project for python bindings.
It should expect avogadrolibs installed, and link with them.

Reason: several different versions of python can be installed on the same machine simultaneously. Each one needs a separate bindings package. Therefore, python bindings can't be just an option of the main project, it should be a separate project.

**Comment by cryos** [comment]
I see your point, but we are not the first and will not be the last project to do this. We thought about the pros and cons of splitting, and may reconsider in the future, but at this stage are sticking with this pattern.

**Comment by cryos** [comment]
I see your point, but we are not the first and will not be the last project to do this. We thought about the pros and cons of splitting, and may reconsider in the future, but at this stage are sticking with this pattern.

**Comment by cryos** [comment]
I see your point, but we are not the first and will not be the last project to do this. We thought about the pros and cons of splitting, and may reconsider in the future, but at this stage are sticking with this pattern.

**Comment by cryos** [comment]
I see your point, but we are not the first and will not be the last project to do this. We thought about the pros and cons of splitting, and may reconsider in the future, but at this stage are sticking with this pattern.
