### ISSUE TITLE
Add long description to setup.py

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/avogadrolibs#408]
We need some words describing the wrapped portion of avogdrolibs. This will appear on PyPI.

**Comment by cjh1** [comment]
@cryos If you provide some words, I can add them in at some point.

**Comment by cryos** [comment]
I think we may want to adapt what is suggested here, https://packaging.python.org/guides/making-a-pypi-friendly-readme/ and have the long description be the README.md. Implementing that would seem useful, and we could always make a more specific markdown document in the future if that one is a little too general.
