### ISSUE TITLE
The force field optimization is not working

### ISSUE THREAD

**Issue by osmartormenajr** [OpenChemistry/avogadrolibs#420]
**Avogadro version: 1.91.0
 - Avogadrolibs: 1.91.0
 - Qt: 5.8.0

**Desktop version:
 - OS: macOS Mojave
 - Version: 10.14.3
 - Compiler: Binary download

**Describe the bug**
Whenever I try to optimize any molecule, no matter how simple, I get the following error message: "Error interpreting obabel MDL output.". In the Geometry Optimization Parameters window, the Force Filed dropdown menu has only one option: "forcefields", even though I was able to find a lot of force fields inside de app package.

**To Reproduce**
Just try and optimize any geometries.

**Expected behavior**
Well, I expected the geometries to get optimized...

**Additional context**
The lack of a similar issue, so far as I could look for in the web, indicates that the issue could be very specific to my configuration.

**Comment by psavery** [comment]
I tried this on an updated build on Linux, and it seemed to work okay. It might be specific to the mac build. I will try it on Mac later.

**Comment by psavery** [comment]
It looks like the `obabel` executable on the downloaded binaries for Mac are not finding the plugins for some reason. For instance, `./obabel -L` outputs only "ops".

@ghutchis Do you have any recommendations for debugging/fixing this? Is there a way, for instance, to print out where it is searching for plugins?

**Comment by ghutchis** [comment]
@psavery - nothing obvious, which is why this is sitting here. I'm hoping an updated build will solve the problem.

There shouldn't be any cases where `ops` is found but `forcefields` do not. Usually this is set by the environment variables, with the build setting as a fall-back.

**Comment by cryos** [comment]
We will create new binaries soon, and make sure this works. There are a number of dependencies I want to update too.

**Comment by ghutchis** [comment]
This build should work: https://github.com/OpenChemistry/avogadrolibs/suites/648275435/artifacts/5525298
