### ISSUE TITLE
Avogadro2 randomly crashes when the AVX-vectorization is enabled

### ISSUE THREAD

**Issue by antoscha** [OpenChemistry/avogadrolibs#426]
It seems to be a problem with Eigen3 parts of code since the error message looks like:
`avogadro2: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion (internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.`

**Comment by ghutchis** [comment]
I *think* the new #428 patch should fix this. Can you confirm @antoscha ?

**Comment by antoscha** [comment]
Yes, the problem has gone. Thank you!
