### ISSUE TITLE
Molequeue cannot open finished job with Avogadro2 (running)

### ISSUE THREAD

**Issue by mike4chem** [OpenChemistry/avogadrolibs#434]
-  Avogadro version: 1.91.0
 - Avogadrolibs: 1.92.0
 - Qt:  5.14.0
-  MoleQueue 09.0-4-g0511c9a

 - OS: Arch Linux
 - Version  4.19.88-1-lts
 - Compiler gcc version 9.2.0 (GCC)

**Describe the bug**
Trying to Open nwchem or gamess finished job file into RUNNING Avogadro2. Avogadro2 opened empty molecule instead of completed job file with optimized geometry. 

**To Reproduce**
1. Go to Quantum -> Input Generator job 
2. Submit job for nwchem or gamess calculations 
3. Completed job cannot be automatically or manually opened into RUNNING avogadro2.
(a) Only NEW avogadro2 instance (case of nwchem) can open final file. 
(b) New avogardo2 instance can only open starting file for gamess, not the output.

**Expected behavior**
Avogadro 2 should open output file automatically when that option was used.

**Additional context**
I am running avogadro2 from terminal which shows the following upon job submission to nwchem calculations:
QObject::connect: No such signal MoleQueue::Client::errorReceived(int, uint, QString) in /home/spot/openchemistry/avogadrolibs/avogadro/molequeue/molequeuewidget.cpp:288
QObject::connect: (receiver name: ‘widget’)
QObject::disconnect: No such signal MoleQueue::Client::errorReceived(int, uint, QString) in /home/spot/openchemistry/avogadrolibs/avogadro/molequeue/molequeuewidget.cpp:293
QObject::disconnect: (receiver name: ‘widget’)
QObject::connect: No such signal Avogadro::MoleQueue::MoleQueueWidget::jobUpdated(MoleQueue::JobObject) in /home/spot/openchemistry/avogadrolibs/avogadro/molequeue/molequeuedialog.cpp:125
QObject::connect: (sender name: ‘widget’)
QObject::connect: (receiver name: ‘widget’)
QObject::connect: No such signal Avogadro::MoleQueue::MoleQueueWidget::jobUpdated(MoleQueue::JobObject)
QObject::connect: (sender name: ‘widget’)

**Comment by ghutchis** [comment]
Thanks for posting - the thread on this is here: https://discuss.avogadro.cc/t/molequeue-cannot-open-finished-job-with-avogadro2-running/3029/5

**Comment by ghutchis** [comment]
Does this still occur with 1.95 or more recent?

**Comment by ghutchis** [comment]
I'm closing this. If you're still having problems with a more recent release (e.g., 1.95 or later) please open a new issue, thanks.
