### ISSUE TITLE
avogadrolibs-1.92.1 fails to build: undefined reference to `gwavi_open'

### ISSUE THREAD

**Issue by pacho2** [OpenChemistry/avogadrolibs#436]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.92.1
 - Qt: 5.13.2

**Desktop version: (please complete the following information):**
 - OS: Gentoo Linux
 - Compiler : gcc-9.2.0

Fails to build with:
```
[ 77%] Building CXX object avogadro/qtplugins/surfaces/CMakeFiles/Surfaces.dir/SurfacesPlugin.cpp.o
cd /var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtplugins/surfaces && /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DSurfaces_EXPORTS -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtplugins/surfaces/Surfaces_autogen/include -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1 -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/core -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/io -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/quantumio -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/rendering -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtgui -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtopengl -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/molequeue -I/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtplugins/surfaces -isystem /usr/include/eigen3 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1/thirdparty/libgwavi -isystem /var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1/thirdparty/gif-h -isystem /usr/include/qt5/QtConcurrent   -DNDEBUG -O2 -pipe -march=native -fno-stack-protector -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=c++11 -o CMakeFiles/Surfaces.dir/SurfacesPlugin.cpp.o -c /var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtplugins/surfaces/SurfacesPlugin.cpp
[ 77%] Linking CXX shared module ../../../lib/avogadro2/plugins/Surfaces.so
cd /var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/avogadro/qtplugins/surfaces && /usr/bin/cmake -E cmake_link_script CMakeFiles/Surfaces.dir/link.txt --verbose=1
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -fPIC -O2 -pipe -march=native -fno-stack-protector -Wl,--fatal-warnings -Wl,--no-undefined -lc -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -shared  -o ../../../lib/avogadro2/plugins/Surfaces.so CMakeFiles/Surfaces.dir/Surfaces_autogen/mocs_compilation.cpp.o CMakeFiles/Surfaces.dir/gaussiansetconcurrent.cpp.o CMakeFiles/Surfaces.dir/slatersetconcurrent.cpp.o CMakeFiles/Surfaces.dir/surfacedialog.cpp.o CMakeFiles/Surfaces.dir/surfaces.cpp.o CMakeFiles/Surfaces.dir/SurfacesPlugin.cpp.o -Wl,-rpath,/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build/lib: ../../../lib/libAvogadroQtGui.so.1.92.0 ../../../lib/libAvogadroQuantumIO.so.1.92.0 /usr/lib64/libQt5Concurrent.so.5.13.2 /usr/lib64/libQt5Widgets.so.5.13.2 /usr/lib64/libQt5Gui.so.5.13.2 /usr/lib64/libQt5Core.so.5.13.2 ../../../lib/libAvogadroIO.so.1.92.0 ../../../lib/libAvogadroCore.so.1.92.0 /usr/lib64/libQt5Core.so.5.13.2 
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/Surfaces.dir/surfaces.cpp.o: in function `Avogadro::QtPlugins::Surfaces::recordMovie()':
surfaces.cpp:(.text+0x2d2c): undefined reference to `gwavi_open'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/Surfaces.dir/surfaces.cpp.o: in function `Avogadro::QtPlugins::Surfaces::movieFrame()':
surfaces.cpp:(.text+0x2fa7): undefined reference to `Avogadro::QtOpenGL::ActiveObjects::instance()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: surfaces.cpp:(.text+0x2faf): undefined reference to `Avogadro::QtOpenGL::ActiveObjects::activeGLWidget() const'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: surfaces.cpp:(.text+0x3594): undefined reference to `gwavi_add_frame'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: surfaces.cpp:(.text+0x3ca7): undefined reference to `gwavi_close'
collect2: error: ld returned 1 exit status
make[2]: *** [avogadro/qtplugins/surfaces/CMakeFiles/Surfaces.dir/build.make:172: lib/avogadro2/plugins/Surfaces.so] Error 1
make[2]: Leaving directory '/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build'
make[1]: *** [CMakeFiles/Makefile2:3615: avogadro/qtplugins/surfaces/CMakeFiles/Surfaces.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/sci-libs/avogadrolibs-1.92.1/work/avogadrolibs-1.92.1_build'
make: *** [Makefile:130: all] Error 2
```

Thanks

**Comment by cryos** [comment]
I am working on a new release right now - getting ready to tag 1.93.0. Can you see if this still fails with master? I am using GCC 9.2.0 locally on Arch Linux and it works but I don't have access to a Gentoo system to test.

**Comment by RizzerOnGitHub** [comment]
It's working on Debian, you can compare build flags and installed packages at 
https://buildd.debian.org/status/package.php?p=avogadrolibs
https://buildd.debian.org/status/fetch.php?pkg=avogadrolibs&arch=amd64&ver=1.92.1-5&stamp=1579262530&raw=0

**Comment by StefanBruens** [comment]
It likely oly happens when you build with BUILD_STATIC_PLUGINS=OFF and the '--no-undefined' linker flag.

**Comment by pacho2** [comment]
hi

Sorry for the delay

I have tried with 1.93.0 and the failure is the same

With the patch
https://github.com/OpenChemistry/avogadrolibs/pull/443

it continues a bit more but fails with this error:
`[100%] Linking CXX shared module ../../../lib/avogadro2/plugins/QTAIMExtension.so
cd /var/tmp/portage/sci-libs/avogadrolibs-1.93.0/work/avogadrolibs-1.93.0_build/avogadro/qtplugins/qtaim && /usr/bin/cmake -E cmake_link_script CMakeFiles/QTAIMExtension.dir/link.txt --verbose=1
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -fPIC -O2 -pipe -march=native -fno-stack-protector -Wl,--fatal-warnings -Wl,--no-undefined -lc -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -shared  -o ../../../lib/avogadro2/plugins/QTAIMExtension.so CMakeFiles/QTAIMExtension.dir/QTAIMExtension_autogen/mocs_compilation.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimextension.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimwavefunction.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimwavefunctionevaluator.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimodeintegrator.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimmathutilities.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimlsodaintegrator.cpp.o CMakeFiles/QTAIMExtension.dir/qtaimcubature.cpp.o CMakeFiles/QTAIMExtension.dir/QTAIMExtensionPlugin.cpp.o -Wl,-rpath,/var/tmp/portage/sci-libs/avogadrolibs-1.93.0/work/avogadrolibs-1.93.0_build/lib: ../../../lib/libAvogadroQtGui.so.1.93.0 ../../../lib/libAvogadroIO.so.1.93.0 ../../../lib/libAvogadroCore.so.1.93.0 /usr/lib64/libQt5Widgets.so.5.13.2 /usr/lib64/libQt5Gui.so.5.13.2 /usr/lib64/libQt5Core.so.5.13.2 
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QtConcurrent::IterateKernel<QList<QList<QVariant> >::const_iterator, QList<QVariant> >::start()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E5startEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E5startEv]+0xc): undefined reference to `QtConcurrent::ThreadEngineBase::isProgressReportingEnabled()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E5startEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E5startEv]+0x2e): undefined reference to `QtConcurrent::ThreadEngineBase::setProgressRange(int, int)'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QtConcurrent::SequenceHolder1<QList<QList<QVariant> >, QtConcurrent::MappedEachKernel<QList<QList<QVariant> >::const_iterator, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >::~SequenceHolder1()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED1Ev[_ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED1Ev]+0x39): undefined reference to `QtConcurrent::ThreadEngineBase::~ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `virtual thunk to QtConcurrent::SequenceHolder1<QList<QList<QVariant> >, QtConcurrent::MappedEachKernel<QList<QList<QVariant> >::const_iterator, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >::~SequenceHolder1()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED1Ev[_ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED1Ev]+0x80): undefined reference to `QtConcurrent::ThreadEngineBase::~ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QtConcurrent::SequenceHolder1<QList<QList<QVariant> >, QtConcurrent::MappedEachKernel<QList<QList<QVariant> >::const_iterator, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >::~SequenceHolder1()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED0Ev[_ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED0Ev]+0x39): undefined reference to `QtConcurrent::ThreadEngineBase::~ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `virtual thunk to QtConcurrent::SequenceHolder1<QList<QList<QVariant> >, QtConcurrent::MappedEachKernel<QList<QList<QVariant> >::const_iterator, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >, QtConcurrent::FunctionWrapper1<QList<QVariant>, QList<QVariant> > >::~SequenceHolder1()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED0Ev[_ZN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_ED0Ev]+0x90): undefined reference to `QtConcurrent::ThreadEngineBase::~ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QFuture<QtPrivate::MapResultType<void, QList<QVariant> (*)(QList<QVariant>)>::ResultType> QtConcurrent::mapped<QList<QList<QVariant> >, QList<QVariant> (*)(QList<QVariant>)>(QList<QList<QVariant> > const&, QList<QVariant> (*)(QList<QVariant>))':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_[_ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_]+0x26): undefined reference to `QtConcurrent::ThreadEngineBase::ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_[_ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_]+0x11e): undefined reference to `QtConcurrent::ThreadEngineBase::acquireBarrierSemaphore()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_[_ZN12QtConcurrent6mappedI5QListIS1_I8QVariantEEPFS3_S3_EEE7QFutureIN9QtPrivate13MapResultTypeIvT0_E10ResultTypeEERKT_SA_]+0x168): undefined reference to `QtConcurrent::ThreadEngineBase::~ThreadEngineBase()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QtConcurrent::IterateKernel<QList<QList<QVariant> >::const_iterator, QList<QVariant> >::forThreadFunction()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x20): undefined reference to `QtConcurrent::BlockSizeManagerV2::BlockSizeManagerV2(int)'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x45): undefined reference to `QtConcurrent::ThreadEngineBase::isCanceled()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x5a): undefined reference to `QtConcurrent::BlockSizeManagerV2::blockSize()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x9d): undefined reference to `QtConcurrent::ThreadEngineBase::waitForResume()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0xe4): undefined reference to `QtConcurrent::BlockSizeManagerV2::timeBeforeUser()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x14f): undefined reference to `QtConcurrent::BlockSizeManagerV2::timeAfterUser()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x1f9): undefined reference to `QtConcurrent::ThreadEngineBase::setProgressValue(int)'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E17forThreadFunctionEv]+0x360): undefined reference to `QtConcurrent::ThreadEngineBase::startThread()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `QtConcurrent::IterateKernel<QList<QList<QVariant> >::const_iterator, QList<QVariant> >::threadFunction()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv]+0x126): undefined reference to `QtConcurrent::ThreadEngineBase::waitForResume()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv]+0x148): undefined reference to `QtConcurrent::ThreadEngineBase::startThread()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o: in function `virtual thunk to QtConcurrent::IterateKernel<QList<QList<QVariant> >::const_iterator, QList<QVariant> >::threadFunction()':
qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv]+0x728): undefined reference to `QtConcurrent::ThreadEngineBase::waitForResume()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: qtaimcriticalpointlocator.cpp:(.text._ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv[_ZN12QtConcurrent13IterateKernelIN5QListIS1_I8QVariantEE14const_iteratorES3_E14threadFunctionEv]+0x74a): undefined reference to `QtConcurrent::ThreadEngineBase::startThread()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o:(.data.rel.ro._ZTIN12QtConcurrent12ThreadEngineI5QListI8QVariantEEE[_ZTIN12QtConcurrent12ThreadEngineI5QListI8QVariantEEE]+0x18): undefined reference to `typeinfo for QtConcurrent::ThreadEngineBase'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o:(.data.rel.ro._ZTCN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE0_NS_12ThreadEngineIS3_EE[_ZTVN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE]+0x88): undefined reference to `QtConcurrent::ThreadEngineBase::run()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o:(.data.rel.ro._ZTCN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE0_NS_13IterateKernelIS6_S3_EE[_ZTVN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE]+0xb0): undefined reference to `QtConcurrent::ThreadEngineBase::run()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o:(.data.rel.ro._ZTCN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE0_S9_[_ZTVN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE]+0xb0): undefined reference to `QtConcurrent::ThreadEngineBase::run()'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/QTAIMExtension.dir/qtaimcriticalpointlocator.cpp.o:(.data.rel.ro._ZTVN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE[_ZTVN12QtConcurrent15SequenceHolder1I5QListIS1_I8QVariantEENS_16MappedEachKernelINS4_14const_iteratorENS_16FunctionWrapper1IS3_S3_EEEES8_EE]+0xb8): undefined reference to `QtConcurrent::ThreadEngineBase::run()'
collect2: error: ld returned 1 exit status
make[2]: *** [avogadro/qtplugins/qtaim/CMakeFiles/QTAIMExtension.dir/build.make:225: lib/avogadro2/plugins/QTAIMExtension.so] Error 1
make[2]: Leaving directory '/var/tmp/portage/sci-libs/avogadrolibs-1.93.0/work/avogadrolibs-1.93.0_build'
make[1]: *** [CMakeFiles/Makefile2:5260: avogadro/qtplugins/qtaim/CMakeFiles/QTAIMExtension.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/sci-libs/avogadrolibs-1.93.0/work/avogadrolibs-1.93.0_build'
make: *** [Makefile:130: all] Error 2
`

Thanks for your help

**Comment by ghutchis** [comment]
@pacho2 - can you check to see if ${Qt5Concurrent_LIBRARIES} is set in `avogadro/qtplugins/qtaim/CMakeLists.txt`

It seems like it's not linked here...

**Comment by ghutchis** [comment]
@pacho2 - better yet, can you point me at your build script / logs? thanks.

**Comment by pacho2** [comment]
That has all the build logs as recorded by Gentoo portage 

The ebuild is at:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/avogadrolibs/avogadrolibs-1.93.0.ebuild

That one will work as-is because it will enable static plugins, but I manually disabled them locally to reproduce the problem

Thanks! 

[build.log](https://github.com/OpenChemistry/avogadrolibs/files/4560330/build.log)

**Comment by cryos** [comment]
I am using Arch Linux here, with shared plugins, and see some link failures that I am working on fixing here. I haven't built shared for a while, sorry about that. Thanks for the bug reports.

**Comment by ghutchis** [comment]
Let me know what to add to the GH build actions - we can definitely add a shared-no-static build to prevent this.

**Comment by cryos** [comment]
I think it needs another adjustment to the superbuild to make it easy to adjust from that level, I have that patch which fixes the link issues reported and a few I didn't find issues for.

**Comment by cryos** [comment]
Merged, please reopen if this is still an issue but you should be able to build against master/the next release once it is tagged. Thanks for reporting, and sorry it took so long to look into it.
