### ISSUE TITLE
empty toolsettings boxes

### ISSUE THREAD

**Issue by grindhold** [OpenChemistry/avogadrolibs#438]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.92.1-5 [according to debian] 1.92.0 [according to about screen]
 - Qt: 5.12.5

**Desktop version: (please complete the following information):**
 - OS: Debian
 - Version: bullseye

**Describe the bug**
According to the docs, the dockable dialog for tool settings should show some options when i select "selection" as tool. it does not on my installation. this is also true for all tools except "draw" and "player".

**To Reproduce**
1. Go to Avogadro
2. Select "Selection" as tool

**Expected behavior**
I expect to see tool settings in  the toolsettings dialogbox according to the docs.

**Screenshots**
![bugimage](https://i.imgur.com/5BrDeML.png)

**Comment by ghutchis** [comment]
This isn't a bug - some of the tools don't have settings at the moment (eg. selection).

**Comment by ghutchis** [comment]
The docs are for Avo 1.2 - not all features have been ported to Avo2, but help is certainly welcome.

**Comment by grindhold** [comment]
ah k :) i'm not used to unfinished stuff, even in debian testing. this is completely understandable. sorry for bothering
