### ISSUE TITLE
Open Babel Optimize Geometry arbitrarily adds H atoms

### ISSUE THREAD

**Issue by RizzerOnGitHub** [OpenChemistry/avogadrolibs#442]
**Avogadro version: 1.93.0:**
 - Avogadrolibs: 1.93.0
 - Qt: 5.12.5

**Desktop version: :**
 - OS: Linux  (Debian unstable)
 - Version linux 5.4.13-1
 - Compiler g++ 9.2.1 20200203

**Describe the bug**
The Optimize Geometry function sometimes fails, with the optimizing routine apparently arbitrarily adding its own H atoms contradicting the given structure.  Optimize Geometry appears to run for a reasonable number of iterations, but then gives the error message:
"Number of atoms in obabel output (22) does not match the number of atoms in the original molecule (19)."
(This example of 19 atoms refers to histidine with the carboxylate group protonated  and prime amine group unprotonated i.e. ...NH with 1 H atom, no charge. That is, neutral histidine)

The problem seems to happen for pH-dependent molecules such as amino acids, where carboxylate and amine groups may or may not be protonated.

If I manually click on "Adjust Hydrogens", then avogadro2 adds 3 protons, 1 to the  amine group and 1 each to the C and double-bonded O of the carboxylate.  So it's converting the carboxylic acid group to a methandiol group.  By the count of atoms in the error message, it looks like this is what Optimize Geometry is doing to the structure before running optimization.

So it looks as though Optimize Geometry is interfering with the given structure and not working with the structure as presented.

**To Reproduce**
1. Create an amino acid. Glycine will do.  If "Adjust Hydrogens" is set. then avogadro2 will create the amine group as ...NH2 (glycine cation).
2. Delete one of the amine hydrogens to get neutral glycine H2CNHCOOH
3. Click Extensions->Open Babel->Optimize Geometry.
4. Iterations will proceed, then give the error message
"Number of atoms in obabel output (10) does not match the number of atoms in the original molecule (9)."

**Expected behavior**

Optimize Geometry should work strictly with the given structure, and not add (or remove) hydrogen atoms.

**Comment by ghutchis** [comment]
I'm going to figure out the specific issue - but #448 will soon add an integrated optimizer.
