### ISSUE TITLE
avogadro-libs-1.93.0 fails to build due to missing "archive.h"

### ISSUE THREAD

**Issue by GenKawamura** [OpenChemistry/avogadrolibs#444]
**Avogadro version**
avogadro2-libs-1.90.0-12
Qt: 5.9.2

**Desktop version**
OS: Linux Scienfitic Linux (compatible with Redhat EL7)
Version: 7.6
Compiler: gcc-c++-4.8.5-39.el7.x86_64, cmake-2.8.12.2-2.el7.x86_64

**Describe the bug**
I am making a package of "avogadro2-libs-1.93.0-1.fc32" on the RHEL7 platform. But, the build fails in the part of "plugindownloader" due to missing "archive.h".

The error message is the following. The cause of "la_int64_t" should be defined by "archive.h". This header, "archive.h",  is defined in "zipextracter.h".

**Do you have any idea how to fix it?**

**In "avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.h"**
           #include "archive.h"
           #include "archive_entry.h"

We use the following packages which were required by the build.
* libarchive-3.1.2-14.el7_7.x86_64
* msgpack-3.1.0-2.el7.x86_64
* mmtf-cpp-devel-1.0.0-2.el7.x86_64

[build.log](https://github.com/OpenChemistry/avogadrolibs/files/4230175/build.log)
---------------------------------------------------------------------------------------------------
/tmp/avogadro2/BUILD/avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.cpp: In member function 'int Avogadro::QtPlugins::ZipExtracter::copyData(archive*, archive*)':
/tmp/avogadro2/BUILD/avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.cpp:38:3: error: 'la_int64_t' was not declared in this scope
   la_int64_t offset;
   ^~~~~~~~~~
/tmp/avogadro2/BUILD/avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.cpp:38:3: note: suggested alternative: 'u_int64_t'
   la_int64_t offset;
   ^~~~~~~~~~
   u_int64_t
/tmp/avogadro2/BUILD/avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.cpp:41:52: error: 'offset' was not declared in this scope
     r = archive_read_data_block(ar, &buff, &size, &offset);
                                                    ^~~~~~
/tmp/avogadro2/BUILD/avogadrolibs-1.93.0/avogadro/qtplugins/plugindownloader/zipextracter.cpp:41:52: note: suggested alternative: 'off_t'
     r = archive_read_data_block(ar, &buff, &size, &offset);
                                                    ^~~~~~
                                                    off_t
---------------------------------------------------------------------------------------------------

Thank you in advance
Gen

**Comment by ghutchis** [comment]
I suspect you're not using `libarchive`. The downloader uses libarchive which is clearly your missing header. As I posted to the discussion:

Are you using a recent version of the `openchemistry` repository and/or `USE_SYSTEM_LIBARCHIVE` ?

**Comment by cryos** [comment]
They are packaging it, and so using their own libraries. Can you link to a file listing for your libarchive package? It would be good to understand where the headers end up being installed.

**Comment by GenKawamura** [comment]
Hi,

I put my comment in the following discussion as well. I made a docker container for this RHEL7 packaging yesterday. 
https://discuss.avogadro.cc/t/avogadro-libs-1-93-0-fails-to-build-due-to-missing-archive-h/3086/2

As you can see, it's saying the missing archive types which should be defined by "archive.h".  I tried also "-DUSE_SYSTEM_LIBARCHIVE=ON" and some other things (e.g. fixing definitions), but it did not improve the situation.

https://github.com/Avogadro2-test/avogadro2-docker/blob/6bd15b241c352059d1ca212de213216cd4ceeaab/logs/docker-build.centos7.log

**Comment by GenKawamura** [comment]
The repository is in the following URL. The error is now easily re-producible.

I am testing the builds using docker every evening.
https://github.com/Avogadro2-test/avogadro2-docker

**Comment by GenKawamura** [comment]
The fedora packager Antonio answered. I could build the package after using the newer libarchive.

I update the "avogadro2-docker" as well.


>It's a compatibility issue with libarchive-3.1.2 provided on EPEL7.
>
>`libarchive` needs to be updated to a recent version (Fedora 32 provides
>libarchive-3.4.2).

**Comment by ghutchis** [comment]
I'm going to close this since it seems you're successful now?

**Comment by GenKawamura** [comment]
Yes. 1.93.0 in RHEL7 works now. Thanks!
