### ISSUE TITLE
step-by step plugins documentation

### ISSUE THREAD

**Issue by githiakalaban** [OpenChemistry/avogadrolibs#445]
**Is your feature request related to a problem? Please describe.**
i've tried to install external plugin but i don't find any information online am on a linux machine using the current avogadro2 

**Describe the solution you'd like**
please any information on a step-by-step installation of the plugin would help 

**Describe alternatives you've considered**

**Additional context**

Please consider opening a topic on https://discuss.avogadro.cc/ to allow further public discussion

**Comment by ghutchis** [comment]
The downloader was broken in versions before 1.94.0. Please try the new version.

There's also documentation on developing new scripts at: http://two.avogadro.cc/
