### ISSUE TITLE
Building avogadroapp failed, patch required for avogadrolibs. (openSUSE)

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenChemistry/avogadrolibs#446]
- Avogadrolibs: 1.93.0
 - Qt: 5.14.1
-Compiler gcc-c++ 9-1.6

Operating System: openSUSE Tumbleweed 20200227
KDE Plasma Version: 5.18.1
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.6-1-default
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM

When installing avogadrolibs on Linux, avogadrolibs will generate a file /usr/lib64/cmake/avogadrolibs/AvogadroLibsConfig.cmake

At line 13 this is found:
`set(AvogadroLibs_LIBRARY_DIR     "${AvogadroLibs_INSTALL_PREFIX}//usr/lib6464")`

Which is looks kinda odd, should it be this instead?
`set(AvogadroLibs_LIBRARY_DIR     "usr/lib64")`

Looking at the source code, the responsible file is in cmake/AvogadroLibsConfig.cmake.in

`set(AvogadroLibs_LIBRARY_DIR     "${AvogadroLibs_INSTALL_PREFIX}/@INSTALL_LIBRARY_DIR@@LIB_SUFFIX@")`

Which I believe must be like this

`set(AvogadroLibs_LIBRARY_DIR     "@INSTALL_LIBRARY_DIR@")`

The reason I found this potential bug is because trying to compile avogadro2 will result in error.
Therefor I create a patch for openSUSE.

```

diff -ruN a/cmake/AvogadroLibsConfig.cmake.in b/cmake/AvogadroLibsConfig.cmake.in
--- a/cmake/AvogadroLibsConfig.cmake.in	2020-01-14 14:43:42.000000000 +0000
+++ b/cmake/AvogadroLibsConfig.cmake.in	2020-02-29 12:47:27.087397497 +0000
@@ -10,7 +10,7 @@
 

 set(AvogadroLibs_INSTALL_PREFIX  "@CMAKE_INSTALL_PREFIX@")
 set(AvogadroLibs_INCLUDE_DIRS    "${AvogadroLibs_INSTALL_PREFIX}/@INSTALL_INCLUDE_DIR@")
-set(AvogadroLibs_LIBRARY_DIR     "${AvogadroLibs_INSTALL_PREFIX}/@INSTALL_LIBRARY_DIR@@LIB_SUFFIX@")
+set(AvogadroLibs_LIBRARY_DIR     "@INSTALL_LIBRARY_DIR@")
 set(AvogadroLibs_RUNTIME_DIR     "${AvogadroLibs_INSTALL_PREFIX}/@INSTALL_RUNTIME_DIR@")
 set(AvogadroLibs_CMAKE_DIR       "${AvogadroLibs_LIBRARY_DIR}/cmake/avogadrolibs")

```
 
https://build.opensuse.org/package/show/home:andythe_great/avogadrolibs

**Comment by ghutchis** [comment]
Okay, this one should be fixed by #460 too, thanks
