### ISSUE TITLE
Avagadro crashes in ESP calculation

### ISSUE THREAD

**Issue by jimkress65** [OpenChemistry/avogadrolibs#447]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (1.2.0)
 - Qt: (4.8.6)

**Desktop version: (please complete the following information):**
 - OS: [Windows 7 Pro]
 - Version [1.2.0]
 - Compiler (if you built from source)

**Describe the bug**
Application crashes when coloring a Van der Waals surface by Electrostatic Potential

**To Reproduce**
File > Open > RKS_PBE0-def2-SVP_18Na_no_wat_neut_nopts_plain.out (an ORCA output file)
Extensions > Create Surfaces 
Surface Type Van der Waals
Color by Electrostatic Potential
Calculate

Van der Waals surface created
Application crashes during the step Color by Electrostatic Potential

Problem Details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	avogadro.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5ca2200f
  Fault Module Name:	MSVCR100.dll
  Fault Module Version:	10.0.30319.1
  Fault Module Timestamp:	4ba1dbbe
  Exception Code:	40000015
  Exception Offset:	0008d635
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	b4fe
  Additional Information 2:	b4fe8fdd374cd6f413cb5ba4c10f112b
  Additional Information 3:	054f
  Additional Information 4:	054f3259001daadfd887e5aef0517ab7

**Expected behavior**
Display of a colored surface surrounding the molecule

**Screenshots**
N/A

**Additional context**
RKS_PBE0-def2-SVP_18Na_no_wat_neut_nopts_plain.out is a ORCA output file.  It contains 660 atoms and many thousands of basis functions.

Is there a limit to number of atoms or basis functions?

[RKS_PBE0-def2-SVP_18Na_no_wat_neut_nopts_plain.zip](https://github.com/OpenChemistry/avogadrolibs/files/4283838/RKS_PBE0-def2-SVP_18Na_no_wat_neut_nopts_plain.zip)

**Comment by ghutchis** [comment]
Not sure why you're getting a crash (in Avo v1.2) but there's no limit for the number of atoms or basis functions.

**Comment by jimkress65** [comment]
Thanks for your reply.

 

What would you suggest we do to try and figure out what is happening?  Since the Van der Waals surface is generated just fine but the ESP coloring crashes almost immediately, can we look into that code and try to find the problem?  I can share the input file if that would help.

 

BTW, if I do a 160 atom Carbon nanotube, Avo v1.2 works just fine.

 

James Kress Ph.D., President

The KressWorks® Institute 

An IRS Approved 501 (c)(3) Charitable, Nonprofit Corporation

“Engineering The Cure” ©

(248) 573-5499

 

Learn More and Donate At:

Website:  <http://www.kressworks.org/> http://www.kressworks.org

Facebook: https://www.facebook.com/KressWorks.Institute/

 

Confidentiality Notice | This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by ghutchis** [comment]
It took us a while to get nice electrostatic potential maps and van der Waals / solvent excluded surfaces, but this is available in the 1.97 releases:

https://github.com/openchemistry/avogadrolibs/releases/latest

I'm going to mark this as closed. If you encounter crashes with 1.97, please open a new bug report. Thanks!

**Comment by jimkress65** [comment]
Thanks.
