### ISSUE TITLE
AvogadroLibsConfig.cmake: Find include patch

### ISSUE THREAD

**Issue by pacho2** [OpenChemistry/avogadrolibs#449]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.93
 - Qt: 5.13

**Desktop version: (please complete the following information):**
 - OS: Gentoo Linux
 - Compiler gcc-9.2

I need to apply this patch to be able to compile avogadroapp:
https://github.com/schnitzeltony/meta-qt5-extra/blob/master/recipes-misc/recipes-chemistry/avogadro/avogadrolibs/0002-AvogadroLibsConfig.cmake-Find-include.patch

``

From a84b9bbc192fd27e8e87648b72331b8216993549 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Andreas=20M=C3=BCller?= <schnitzeltony@gmail.com>
Date: Fri, 16 Nov 2018 18:21:00 +0100
Subject: [PATCH] AvogadroLibsConfig.cmake: Find include
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Upstream-Status: Pending

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
---
 cmake/AvogadroLibsConfig.cmake.in | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/cmake/AvogadroLibsConfig.cmake.in b/cmake/AvogadroLibsConfig.cmake.in
index ad57195c..dc6555f6 100644
--- a/cmake/AvogadroLibsConfig.cmake.in
+++ b/cmake/AvogadroLibsConfig.cmake.in
@@ -19,5 +19,5 @@ set(AvogadroLibs_PLUGINS         "@AvogadroLibs_PLUGINS@")
 set(AvogadroLibs_STATIC_PLUGINS  "@AvogadroLibs_STATIC_PLUGINS@")
 
 if(NOT TARGET AvogadroCore)
-  include("${AvogadroLibs_CMAKE_DIR}/AvogadroLibsTargets.cmake")
+  include("${CMAKE_CURRENT_LIST_DIR}/AvogadroLibsTargets.cmake")
 endif()
-- 
2.14.4

``

Otherwise compilation of avogradoapp dies with
``

cmake -C /var/tmp/portage/sci-chemistry/avogadro2-1.93.0/work/avogadro2-1.93.0_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOCUMENTATION=no -DAvogadro_ENABLE_RPC=no -DENABLE_TESTING=no -DUSE_VTK=no -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-chemistry/avogadro2-1.93.0/work/avogadro2-1.93.0_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-chemistry/avogadro2-1.93.0/work/avogadroapp-1.93.0
loading initial cache file /var/tmp/portage/sci-chemistry/avogadro2-1.93.0/work/avogadro2-1.93.0_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
-- Found Git: /usr/bin/git (found version "2.24.1") 
-- Could not use git to determine source version, using version 1.93.0
CMake Error at /usr/lib64/cmake/avogadrolibs/AvogadroLibsConfig.cmake:22 (include):
  include could not find load file:

    /usr/lib6464/cmake/avogadrolibs/AvogadroLibsTargets.cmake
Call Stack (most recent call first):
  avogadro/CMakeLists.txt:1 (find_package)

-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.5") found components:  C 
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -pipe -march=native -fno-stack-protector
C++             -O2 -pipe -march=native -fno-stack-protector
Linker flags:
Executable      -Wl,--fatal-warnings -Wl,--no-undefined -lc -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu
Module          -Wl,--fatal-warnings -Wl,--no-undefined -lc -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu
Shared          -Wl,--fatal-warnings -Wl,--no-undefined -lc -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu

-- Configuring incomplete, errors occurred!

``

Thanks

**Comment by pacho2** [comment]
In Fedora they fix it in a different way:
https://src.fedoraproject.org/rpms/avogadro2-libs/blob/master/f/avogadro2-libs-fix_AvogadroLibsConfig.patch

**Comment by ghutchis** [comment]
Thanks - this should now be fixed in `master`
