### ISSUE TITLE
Selection tool 'Apply color' => extension

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#452]
The selection tool has code to apply custom colors to a set of selected atoms.

This is cool, but it's not easily discoverable - you have to tap on the semi-invisible button next to the "apply color" label.
<img width="230" alt="Screen Shot 2020-03-31 at 11 24 37 AM" src="https://user-images.githubusercontent.com/41128/78044098-37d58f80-7342-11ea-9904-a6e594cbf92c.png">

I think the code should migrate to an Extension that operates on a selection and is a menu item, for example under the "View" menu, e.g "Apply custom color". (This could be extended to apply colors based on the Avo1 color plugins .. partial charges, etc.)

The good news is that the rendering code already supports custom colors.
<img width="405" alt="Screen Shot 2020-03-31 at 11 26 10 AM" src="https://user-images.githubusercontent.com/41128/78044289-74a18680-7342-11ea-943e-cd3f9c6b19b7.png">

**Comment by ghutchis** [comment]
Avo1 color schemes:
- partial charges
- distance
- atom index
- residue
- color by SMARTS (easier is to add 'select by SMARTS' and custom color to a selection)

**Comment by Krzmbrzl** [comment]
Adding a frame around the color box would also make it more visible
