### ISSUE TITLE
Could not build avogadrolibs on openSUSE E: lto-no-text-in-archive

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenChemistry/avogadrolibs#455]
Hello,

I am trying to build avogadrolibs 1.93.0 on openSUSE Tumbleweed with cmake gcc.

I encounter multiple errors saying E: lto-no-text-in-archive
cmake give some hint: This archive does not contain a non-empty .text section.  The archive was not reated with -ffat-lto-objects option.

I have added %global _lto_cflags %%{_lto_cflags} -ffat-lto-objects to cmake, which fix the error.
However, the package maintainer won't accept this, as it is not actually a fix. They gave no explanation.

I have no clue what this error it is trying to say. Maybe have to add -ffat-lto-objects to it.

Thanks.

```
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/BallStick.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/BondCentric.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Bonding.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/CoordinateEditor.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/CopyPaste.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Crystal.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/CrystalScene.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/CustomElements.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Editor.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Force.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/GamessInput.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Hydrogens.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/ImportPQR.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/LammpsInput.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Licorice.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/LineFormatInput.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Manipulator.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/MeasureTool.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Meshes.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/MolecularProperties.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/MongoChem.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Navigator.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/NetworkDatabases.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/OpenBabel.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/OverlayAxes.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/POVRay.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/PlayerTool.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/PluginDownloader.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/QuantumInput.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/ScriptFileFormats.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Select.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Selection.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/SpaceGroup.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Spectra.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Surfaces.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Symmetry.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/SymmetryScene.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/ThreeDMol.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/VRML.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/VanDerWaals.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/VanDerWaalsAO.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/Wireframe.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/apbs.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/avogadro2/staticplugins/commands.a
[  254s] avogadrolibs-devel-static.x86_64: E: lto-no-text-in-archive (Badness: 10000) /usr/lib64/liblibgwavi.a
[  254s] This archive does not contain a non-empty .text section.  The archive was not
[  254s] created with -ffat-lto-objects option.
```

**Comment by ghutchis** [comment]
There seems to be a similar openSUSE patch for a different package:
https://www.mail-archive.com/opensuse-commit@opensuse.org/msg166302.html

If there's a way to detect your particular version of GCC, we can try to handle in our CMakeFiles.

**Comment by kevinsmia1939** [comment]
> There seems to be a similar openSUSE patch for a different package:
> https://www.mail-archive.com/opensuse-commit@opensuse.org/msg166302.html
> 
> If there's a way to detect your particular version of GCC, we can try to handle in our CMakeFiles.

From what I ask from other people in openSUSE, most likely the -ffat-lto-objects flag have to be added.

https://forums.opensuse.org/showthread.php/539911-How-to-detect-GCC-using-CMakeFiles-(avogadrolibs-dev-ask-this)?p=2933084#post2933084

**Comment by ghutchis** [comment]
I'm okay with that - but presumably that's needed for particular versions of GCC?

**Comment by cryos** [comment]
This seems very distro specific, it would be great to get some explanation, along with why I can't reproduce it here using a very recent GCC - are you adding other compiler flags we aren't using by default @kevinsmia1939?

**Comment by kevinsmia1939** [comment]
I will continue to ask openSUSE dev, mean while I found some info on this.

https://en.opensuse.org/openSUSE:LTO#LTO_enablement_in_openSUSE:Factory

**Comment by kevinsmia1939** [comment]
The log file contain all the flag passes when building avogadrolibs here:
https://build.opensuse.org/build/home:andythe_great/openSUSE_Tumbleweed/x86_64/avogadrolibs/_log

openSUSE's guy mention that this is about reproducible build.

They also give this documentation on LTO.
https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html

**Comment by ghutchis** [comment]
I spent some time looking into this, but IMHO, the package maintainer is wrong. As you said, the openSUSE docs recommend exactly that:

> the easiest to achieve this is by adding, somewhere near the top of the .spec file:
> 
> %global _lto_cflags %{?_lto_cflags} -ffat-lto-objects

If the package maintainer has another solution, patch,  I'm happy to consider it. But I can't find any way to detect that the compiler is using LTO, so I don't see how our cmake files should change.

I just merged patches from Fedora and other downstream maintainers - and would be happy to merge any changes the openSUSE maintainer suggests.

**Comment by kevinsmia1939** [comment]
> I spent some time looking into this, but IMHO, the package maintainer is wrong. As you said, the openSUSE docs recommend exactly that:
> 
> > the easiest to achieve this is by adding, somewhere near the top of the .spec file:
> > %global _lto_cflags %{?_lto_cflags} -ffat-lto-objects
> 
> If the package maintainer has another solution, patch, I'm happy to consider it. But I can't find any way to detect that the compiler is using LTO, so I don't see how our cmake files should change.
> 
> I just merged patches from Fedora and other downstream maintainers - and would be happy to merge any changes the openSUSE maintainer suggests.

I will check that with openSUSE dev and ask them to clarify on that, Thanks.

**Comment by kevinsmia1939** [comment]
Hello,

I ask this on openSUSE's mailing list.
https://lists.opensuse.org/opensuse-packaging/2020-05/msg00000.html

To quote the repo maintainer.

> 
> It would be a correct solution if the affected library were a library which
> should be shipped, but thats not the case here - it is just bunch of object
> files which should be statically linked to the shared libraries (here,
> dl'opened modules).
> 
> There is a bugreport I have opened upstream, which has seen some progress
> lately.
> 
> There currently is a patch in the package which fixes the problem correctly.

I believe that the bug they refer to is this:
https://github.com/OpenChemistry/avogadrolibs/issues/436

Which seems to have patch available for it, but I believe this only fix libgwavi but not the rest of the static libraries.

**Comment by cryos** [comment]
This seems like something that is a detail of OpenSUSE and should stay a patch there for their specific build set up. I was once a Gentoo maintainer, and have a decent feeling for these things. Unless you have a good reason why we as a project would change our build system I would suggest we close this issue until such a time as a more general solution is available. It looks like SUSE is already changing the build flags/compiler settings passed to Avogadro, and should make other local modifications there too.

**Comment by kevinsmia1939** [comment]
> This seems like something that is a detail of OpenSUSE and should stay a patch there for their specific build set up. I was once a Gentoo maintainer, and have a decent feeling for these things. Unless you have a good reason why we as a project would change our build system I would suggest we close this issue until such a time as a more general solution is available. It looks like SUSE is already changing the build flags/compiler settings passed to Avogadro, and should make other local modifications there too.

I could not convince opensuse repo maintainer to think otherwise. I also don't know about this issue to comment on it. All I could do is relay comment to you. Are there anything you want to tell opensuse maintainer? Or it might be better to tell them about the issue directly. Maybe at opensuse mailing list. opensuse-packaging@opensuse.org

Anyway, I will be keeping an eye on the updates and close the issue for now. Thanks for the reply.

**Comment by cryos** [comment]
Thanks, #472 fixes a number of link issues when building with shared plugins and will be merged soon. I think that will fix the more general issues, these just seem far too distro specific to be something we should worry about. I am open to being convinced otherwise, but also happy to move on if they don't have any energy to explain what is needed in a more general settings.

**Comment by StefanBruens** [comment]
libgwavi.a should not be installed in the first place, it is just a temporary build artifact statically linked into the Surfaces library. With a current cmake, it should even be built as an OBJECT library instead of a STATIC library.

For the static plugins, I think there is something wrong in general.
If these are linked statically into the avogadro libraries, then there is no longer a need to install and distribute these. If loadable plugins are wanted, stick to the dynamic libraries.

Linux distributions discourage packaging static libraries, and they do for very good reasons. I see no reason why a deviation from this policy is necessary, the dynamic library plugins are working fine.
