### ISSUE TITLE
Export Molecule: Unable to find a suitable writer for the selected format.

### ISSUE THREAD

**Issue by miroi** [OpenChemistry/avogadrolibs#464]
Hello,
I just installed Avogadro2 package (1.90.0) on my CenOS 7 x86_64 Linux.

When I try to export the molecule in some format, I always get the message "Unable to find a suitable writer for the selected format." 

What is missing ? I have all the package prerequisities installed.

**Comment by miroi** [comment]
Well, as workaround I used OpenBabel-GUI as another program to convert Avogadro2 native cml format to xyz format. 

Is there a simply way to link OpenBabel with Avogadro2 ?

**Comment by ghutchis** [comment]
You have a very old version - current is 1.93, and `master` will be 1.94. All of these versions should use Open Babel for translation if it's installed. The main difference is that it's not linking to `libopenbabel` but using it as a binary.

**Comment by miroi** [comment]
Ah, that is ... old packages... rather I use newer server to have all sofftware up-to-date.

Closing this issue.
