### ISSUE TITLE
cp2kinput includes molequeue unconditionally

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#476]
**Avogadro version:**
 - Avogadrolibs: 1.93.0+git20200509.e169315
 - Qt: 5.12.5

**Desktop version:**
 - OS: Linux
 - Version 5.6.7 (Debian unstable)
 - Compiler gcc 9.3.0

Build fails when molequeue is not installed since c2pkinput includes molequeue headers.

Excerpts from the build log:

    CMake Warning at avogadro/qtplugins/cp2kinput/CMakeLists.txt:1 (find_package):
      By not providing "FindMoleQueue.cmake" in CMAKE_MODULE_PATH this project
      has asked CMake to find a package configuration file provided by
      "MoleQueue", but CMake did not find one.
    
      Could not find a package configuration file provided by "MoleQueue" with
      any of the following names:
    
        MoleQueueConfig.cmake
        molequeue-config.cmake
    
      Add the installation prefix of "MoleQueue" to CMAKE_PREFIX_PATH or set
      "MoleQueue_DIR" to a directory containing one of the above files.  If
      "MoleQueue" provides a separate development package or SDK, be sure it has
      been installed.

Molequeue is optional, isn't it? So this is a warning, not an error?

Then later in the build,

    [ 51%] Building CXX object avogadro/qtplugins/cp2kinput/CMakeFiles/Cp2kInput.dir/cp2kinputdialog.cpp.o
    cd /home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/qtplugins/cp2kinput && /usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_WIDGETS_LIB -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/qtplugins/cp2kinput/Cp2kInput_autogen/include -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu -I/home/projects/debichem/build/avogadrolibs -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/core -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/io -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/quantumio -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/rendering -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/qtgui -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/qtopengl -I/home/projects/debichem/build/avogadrolibs/obj-x86_64-linux-gnu/avogadro/qtplugins/cp2kinput -isystem /usr/include/eigen3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -g -O2 -fdebug-prefix-map=/home/projects/debichem/build/avogadrolibs=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -fPIC -std=c++17 -o CMakeFiles/Cp2kInput.dir/cp2kinputdialog.cpp.o -c /home/projects/debichem/build/avogadrolibs/avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp
    In file included from /home/projects/debichem/build/avogadrolibs/avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp:24:
    /home/projects/debichem/build/avogadrolibs/avogadro/molequeue/molequeuedialog.h:20:10: fatal error: avogadromolequeueexport.h: No such file or directory
       20 | #include "avogadromolequeueexport.h"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[3]: *** [avogadro/qtplugins/cp2kinput/CMakeFiles/Cp2kInput.dir/build.make:83: avogadro/qtplugins/cp2kinput/CMakeFiles/Cp2kInput.dir/cp2kinputdialog.cpp.o] Error 1

cp2kinputdialog.cpp line 24 has `#include <molequeue/client/jobobject.h>`, without checking if molequeue in fact available.

**Comment by ghutchis** [comment]
Missed this one too - fixed by #558
