### ISSUE TITLE
Test "ArrayTest" fails

### ISSUE THREAD

**Issue by jcbollinger** [OpenChemistry/avogadrolibs#478]
**Avogadro version:**
 - Avogadrolibs: 1.93.0
 - Qt: 5.12.5

**Desktop version:**
 - OS: CentOS Linux
 - Version 8.1
 - Compiler GCC

**Describe the bug**
Avogadrolibs builds successfully and without any warnings of significant concern, and most of the tests pass.  But test "ArrayTest" fails with an assertion error.  Running the same test command directly to collect the output yields:
```
$ "/home/me/avogadrolibs-1.93.0/build/bin/AvogadroTests" "--gtest_filter=ArrayTest.*"
Running main() from gtest_main.cc
Note: Google Test filter = ArrayTest.*
[==========] Running 7 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 7 tests from ArrayTest
[ RUN      ] ArrayTest.setSize
[       OK ] ArrayTest.setSize (0 ms)
[ RUN      ] ArrayTest.isEmpty
[       OK ] ArrayTest.isEmpty (0 ms)
[ RUN      ] ArrayTest.push_back
[       OK ] ArrayTest.push_back (0 ms)
[ RUN      ] ArrayTest.clear
[       OK ] ArrayTest.clear (0 ms)
[ RUN      ] ArrayTest.detach
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

**To Reproduce**
1. Unpack the v1.93.0 release tarball and change to its directory
2. Create a build directory and change to it
3. Configure and build the software with various hardening flags enabled:
```
$  CXXFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection"

$ export CXXFLAGS

$ cmake
  -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
  -DOpenGL_GL_PREFERENCE:STRING=GLVND \
  -DENABLE_TESTING:BOOL=TRUE \
  -DUSE_HDF5:BOOL=TRUE

$ make
```
4. Run the test suite:
```
$ make test
```
5. Observe that the test suite reports one failing test out of 28
6. Run the failing test directly via the test command reported in the test log (see command and output in the above issue description)

**Expected behavior**
All tests executed should pass, or at worst xfail.

**Comment by jcbollinger** [comment]
My guess at the moment is that the exception arises in `Array::constData()`, as a result of referring to `d->data[0]` when `d->data` contains no elements.  If that's so then the two versions of `Array::data()` both appear to have the same issue.

**Comment by jcbollinger** [comment]
Debugging the test program reveals that it is indeed crashing in one of the calls to Array::constData() at line 67 of arraytest.cpp, where, after detachment, `array2`'s member `d` is a vector of zero length and capacity.

**Comment by jcbollinger** [comment]
After some thought, I modified `Array::constData()` and both versions of `Array::data()` to replace each appearance of the expression `&d->data[0]` with `d->data.data()`.  I presume that the original form was used for compatibility with C++11 prior to C++11, when `std::vector::data()` was introduced.  I think the change preserves the original semantics in all cases where those were in fact defined, plus solves the undefinedness problem for cases such as in the test case that broke for me.

With those changes, all test pass.

**Comment by cryos** [comment]
Thanks for the report, you are correct that the use of the first element address was for compatibility. It should certainly be replaced now that we require C++11 or greater. I am just taking a look at this now, thanks for the very detailed report.
