### ISSUE TITLE
Avogadro 1.2 style MO viewer

### ISSUE THREAD

**Issue by adreasnow** [OpenChemistry/avogadrolibs#479]
One of the most used features of Avogadro 1.2 for me is the convenient MO viewer that will auto generate the cubes for the HOMO/LUMO (+- a few extra) as you load in an appropriate file and allows you to conveniently click through the MOs for easy comparison. 

It would be amazing if this feature could be included in Avogadro 2, as now that modern linux distros are dropping support for QT4, all attempts to compile Avogadro 1.2 have been buggy messes.

I'm currently switching between GaussView (which I try and avoid) and IQmol, but I truly miss the speed and convenience with which Avogadro 1.2 handled MOs.

**Comment by ghutchis** [comment]
This is now fixed by #1888
