### ISSUE TITLE
Reduce underlinking in some plugins

### ISSUE THREAD

**Issue by ghost** [OpenChemistry/avogadrolibs#48]
Dear cryos,
in the course of preparing avogadrolibs, we usually test whether libraries are underlinked, that is, whether  some of their dependencies are pulled in via other object files. For normal executables, recent versions of binutils default to not search for dependencies in a transitive manner, which is a good thing, as it makes dependencies more explicit and less likely to break in the future. For shared objects, this is not the case, and requires compiling with **-Wl,--no-undefined** (https://blog.flameeyes.eu/2010/09/your-worst-enemy-undefined-symbols). We have compiled avogadrolibs and noticed some underlinking problems. Would you be willing to merge our patch (https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/avogadrolibs/files/avogadrolibs-0.8.0-underlinking.patch) to make the build more robust? You can reproduce the problems by compiling with

```
LDFLAGS="-Wl,--fatal-warnings -Wl,--no-undefined -lc  -Wl,--as-needed -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -Wl,--no-undefined"
```

**Comment by cryos** [comment]
Seems reasonable, I would consider merging such a patch. I am fixing up some issues on Windows, and looking to make a release soon.

**Comment by cryos** [comment]
I never received a reply, closing for now, please reopen if there are still issues and you have a patch proposal.

**Comment by jlec** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/avogadrolibs/files/avogadrolibs-0.8.0-underlinking.patch here it is
