### ISSUE TITLE
Wrong coordinates when using OpenBabel exporter

### ISSUE THREAD

**Issue by luancarvalhomartins** [OpenChemistry/avogadrolibs#483]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.93.0-28-g780d634
 - Qt: 5.12.18

**Desktop version: (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: kernel 5.4.0-40-generic, libc6 2.31-0ubuntu9
 - Compiler: gcc/cpp (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Describe the bug**
When exporting a molecule using File->Export->Molecule..., the coordinates are completely messed up. 
In order to export the molecule, I had to first click on Save in the file selector, then click Cancel, because the file selector was shown again (but I was a bug report for it).
**To Reproduce**
1. Draw a molecule (eg: methane)
1. Go to File->Export->Molecule...
2. Select a file name, use mol2 extension, or xyz but choose OpenBabel exporter; then click on "Save", the file chooser will show again (which is another bug, but already reported), then click "Cancel"
3. Open file in Avogadro2 - or in another editor - the coordinates will be wrong

**Expected behavior**
The coordinates should match the ones which were drawn. But they are totally wrong.

**Screenshots**
Molecule as drawn
![Screenshot_20200711_124209](https://user-images.githubusercontent.com/29309798/87232482-4b968600-c374-11ea-8f84-c83cdddb6382.png)
Molecule loaded from exported file
![Screenshot_20200711_124312](https://user-images.githubusercontent.com/29309798/87232484-4df8e000-c374-11ea-99c8-0b2495747cc4.png)

**Additional context**
The content of the mol2 file
```
@<TRIPOS>MOLECULE
*****
 6 5 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 C          -3.0000    1.0000   -3.0000 C.3     1  UNL1        0.0330
      2 H          -3.0000    2.0000   -0.0000 H       1  UNL1        0.0521
      3 H          -3.0000    1.0000    1.0000 H       1  UNL1        0.0521
      4 H          -3.0000    0.0000   -0.0000 H       1  UNL1        0.0521
      5 O          -2.0000    1.0000   -0.0000 O.3     1  UNL1       -0.3982
      6 H          -2.0000    2.0000    0.0000 H       1  UNL1        0.2090
@<TRIPOS>BOND
     1     1     2    1
     2     1     3    1
     3     1     4    1
     4     1     5    1
     5     5     6    1
```

**Comment by luancarvalhomartins** [comment]
I would like add that using an native Avogadro exporter works, even for a format that OpenBabel does not, eg: mol, xyz.

**Comment by cryos** [comment]
I will take a look

**Comment by luancarvalhomartins** [comment]
I was working on a PR. The problem was caused by pugixml using a "," as decimal separator when generating the cml file. It was happening because I was using LC_NUMERIC=en_DK.UTF-8. I was looking for a fix forcing pugixml to use a dot as de decimal sep.

**Comment by cryos** [comment]
Ah, that explains why I could have missed something so obvious. I would be happy to look at a PR, if you get stuck I can try taking a closer look too - decimal separators cause far too many subtle bugs!
