### ISSUE TITLE
Pencil tool cannot adjust bond order

### ISSUE THREAD

**Issue by luancarvalhomartins** [OpenChemistry/avogadrolibs#484]
**Avogadro version: (please complete the following information from the About box):**
  - Avogadrolibs: 1.93.0-28-g780d634
  - Qt: 5.12.18

**Desktop version: (please complete the following information):**
  - OS: Ubuntu 20.04
  - Version: kernel 5.4.0-40-generic, libc6 2.31-0ubuntu9
  - Compiler: gcc/cpp (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Describe the bug**
Creating a bond with a different order between two atoms already bonded does nothing.

**To Reproduce**
1. Draw an ethane
2. Click on the draw tool
3. Select Element = "Carbon" and Bond Order = "Double"
4. Click in one of the carbons and drag to the other one
5. The molecule is still and ethane, not an ethene

**Expected behavior**
I would expect the bond order to be adjusted when replacing a bond.

**Screenshots**
Draw a ethane
![Screenshot_20200711_145624](https://user-images.githubusercontent.com/29309798/87234584-41ca4e00-c387-11ea-9072-7d08cde0a4b8.png)
Trying to adjust the bond order (in this picture, I am holding the left mouse button after dragging from the left to the right C)
![Screenshot_20200711_145640](https://user-images.githubusercontent.com/29309798/87234585-4262e480-c387-11ea-8aba-52353f3ec2b9.png)
Still ethane
![Screenshot_20200711_145651](https://user-images.githubusercontent.com/29309798/87234586-4b53b600-c387-11ea-80fc-2bf87cd3f149.png)

**Additional context**
Add any other context about the problem here. **Please consider uploading or linking test files.**

**Comment by ghutchis** [comment]
If you change the bond order to double and click on the bond, it does change, correct?

I think I know where the bug is, but I usually change by clicking on the bond - want to confirm that works.

**Comment by luancarvalhomartins** [comment]
Yes, that indeed works. On a side note, is there any documentation on the Python API? I feel like contributing with some coding.

Thanks

**Comment by ghutchis** [comment]
@luancarvalhomartins - why don't you ask on the forum: https://discuss.avogadro.cc/  - are you asking about Python command, input generators, … the API depends a bit on the needs
