### ISSUE TITLE
can not save any file in any format

### ISSUE THREAD

**Issue by mersadkhan** [OpenChemistry/avogadrolibs#487]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs:1.93.0-28-g780d634
 - Qt: 5.9.7

**Desktop version: (please complete the following information):**
 - OS: linux mint 20cinnamon
 - Version 20
 - Compiler build-essential 

**Describe the bug**
I can not save any file in any format of my structure. I test the "apt install avogadro" version and also openchemistry compiled version. in both I have the same problem

**To Reproduce**
1. make a structure
2. save it as xyz or any other format
3. See error

**Expected behavior**
save the file

**Screenshots**
![Screenshot 2020-09-03 10:01:44](https://user-images.githubusercontent.com/4376091/92088627-63ffab80-edcd-11ea-9900-2f3c3e78ba08.png)

**Additional context**

**Comment by ghutchis** [comment]
I guess the first question is whether you have Open Babel installed. It's a bit weird, though, because XYZ (and CML and CJSON) are native formats.

How are you saving? To export to XYZ (with possible data loss, e.g. bond orders) you need to use the Export -> Molecule command. The Save command will save to CJSON and CML which will save all data.

**Comment by mersadkhan** [comment]
> I guess the first question is whether you have Open Babel installed. It's a bit weird, though, because XYZ (and CML and CJSON) are native formats.
> 
> How are you saving? To export to XYZ (with possible data loss, e.g. bond orders) you need to use the Export -> Molecule command. The Save command will save to CJSON and CML which will save all data.

sudo apt install avogadro
this command supposed to install all dependencies. anyway, I checked open babel is installed. the same problem is when I install Avogadro by compile of openchemistry package.
both of the tested. none of the works. just install last Mint Linux or start it live then install Avogadro. clearly I checked all of these things and then report this bug.

**Comment by ghutchis** [comment]
Okay, it's not the install. I'm not sure which command you're trying. Can you tell me which one?

File => Save (only works with CJSON and CML, not XYZ):
<img width="645" alt="Screen Shot 2020-09-14 at 10 17 56 AM" src="https://user-images.githubusercontent.com/41128/93097561-bfeeed80-f673-11ea-9ef6-e7bd8253a6ab.png">

File => Export => Molecule ( should work with XYZ):
<img width="376" alt="Screen Shot 2020-09-14 at 10 18 13 AM" src="https://user-images.githubusercontent.com/41128/93097656-d6954480-f673-11ea-9892-3551b05206e7.png">

**Comment by mersadkhan** [comment]
> Okay, it's not the install. I'm not sure which command you're trying. Can you tell me which one?
> 
> File => Save (only works with CJSON and CML, not XYZ):
> <img alt="Screen Shot 2020-09-14 at 10 17 56 AM" width="645" src="https://user-images.githubusercontent.com/41128/93097561-bfeeed80-f673-11ea-9ef6-e7bd8253a6ab.png">
> 
> File => Export => Molecule ( should work with XYZ):
> <img alt="Screen Shot 2020-09-14 at 10 18 13 AM" width="376" src="https://user-images.githubusercontent.com/41128/93097656-d6954480-f673-11ea-9892-3551b05206e7.png">

I use both of them. the save and save as method just makes a file (CML) but they don't write the structure. Since when I open the file with a new Avogadro it error and says no molecule nodes found. the other method of saving (export>molecule) doesn't make any file with the error that I have sent its screenshot.

**Comment by ghutchis** [comment]
I believe this is fixed in the just-released 1.94.0 version. I'm going to close this bug for now. If it happens to you, please open a new issue and I'll get on it ASAP.
