### ISSUE TITLE
Pull input generators from github.com/OpenChemistry/avogenerators

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#49]
The input generator repository has moved to:
https://github.com/OpenChemistry/avogenerators

There should be plugin loading to allow users to download / update new generators from the repository. Moreover, we should probably remove some (if not all) generators from the source repository and load either via git or cmake when building.

**Comment by cryos** [comment]
I will finish up the code, I think removing them from source, and packaging them via the superbuild would be best. I just need to finish that up before removing them.

**Comment by ghutchis** [comment]
I'm going to close this - we're proposing something different, which I think will be better.
