### ISSUE TITLE
Pencil Tool deletes hydrogen atoms when bond order are changed

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#505]
**Avogadro version:**
 - Avogadrolibs: 1.91.0
 - Qt: 5.10.1

**Desktop version:**
 - OS: Microsoft Windows
 - Version: 10.0.19041.572

**Describe the bug**
When changing bond order from ethane by clicking on C–C bond using `Pencil Tool`, hydrogen atoms from neighbor carbon are deleted.

**To Reproduce**
1. Go to `Pencil Tool`
2. Click on screen to add CH₄ molecule
3. Add the second carbon atom to create a ethane
4. Go to `Extensions > Open Babel > Optimize geometry `
4. Click on C–C bond to change the bond order and the H atoms to second carbon are deleted

**Expected behavior**
I expected to build an ethene molecule.

**Screenshots**
The follow gif image shows step-by-step what I'm doing.

![gif image for bug](https://user-images.githubusercontent.com/56561421/96941709-85b21080-14a9-11eb-919b-1922368ec3ff.gif)

**Additional context**
During installation, the Wizard show up this error message:

![Avogadro2-1 91 0-win64_VFKf5RObzL](https://user-images.githubusercontent.com/56561421/96942168-ba729780-14aa-11eb-997e-6e7b5c9d28a2.png)

**Comment by ghutchis** [comment]
This seems to be fixed in `HEAD` so I'm closing this one.

**Comment by ghutchis** [comment]
Just verified it - I'll see what's happening. Seems somewhat intermittent on my computer.

**Comment by ghutchis** [comment]
I'm going to close this one in favor of #678 as a "master issue" - the adjust hydrogens code is buggy and sometimes fails.
