### ISSUE TITLE
Import from PQR option is not working

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#506]
**Avogadro version:**
 - Avogadrolibs: 1.91.1
 - Qt: 5.10.1

**Desktop version:**
 - OS: Microsoft Windows
 - Version: 10.0.19041.572

**Describe the bug**
`Import from PQR` option is not working.

**To Reproduce**
1. Go to `File > Import > Import from PQR`
2. A dialog box shows up. On `Search By:` field, search for `benzene` by `name`, as example.
3. Click on `Search` button

**Screenshots**

![image](https://user-images.githubusercontent.com/56561421/96994447-1d901880-1503-11eb-9bc5-de05c1e4db91.png)

**Additional context**
Clicking at some row from Results Table, program close down.

**Comment by PurnimaPurnima** [comment]
I would like to take this up

**Comment by ghutchis** [comment]
Thanks - I believe this is already fixed in `HEAD`. Before you take it up, can you try one of the more recent binaries (or compile from source) and see if the bug still exists?

**Comment by drew-parsons** [comment]
For what it's worth, PQR import is working (with some search quirks) in the Debian build, 1.93.0+git20201104.926573b

**Comment by ghutchis** [comment]
I can confirm this works in latest, so I'm closing this.
