### ISSUE TITLE
Unable to build without MoleQueue

### ISSUE THREAD

**Issue by Krzmbrzl** [OpenChemistry/avogadrolibs#514]
When trying to build current master using `-DUSE_MOLEQUEUE=OFF` when calling cmake, I get a compile error at
```
In file included from /home/krzmbrzl/Documents/Git/avogadrolibs/avogadro/qtplugins/cp2kinput/cp2kinputdialog.cpp:24:
/home/krzmbrzl/Documents/Git/avogadrolibs/avogadro/molequeue/molequeuedialog.h:20:10: fatal error: avogadromolequeueexport.h: No such file or directory
   20 | #include "avogadromolequeueexport.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It seems like there is a check missing for whether MoleQueue support is wished or not.

**Comment by ghutchis** [comment]
Yeah, the big thing is splitting off MoleQueue support entirely, but thanks for this note - I didn't notice that cp2k doesn't build without MoleQueue. Right now the MoleQueue code is supplying the GUI forms for the input dialogs - and I haven't had time to migrate to the new code.
