### ISSUE TITLE
Linked WebPage gives 404

### ISSUE THREAD

**Issue by Krzmbrzl** [OpenChemistry/avogadrolibs#525]
The webpage you have linked here on GitHub (openchemistry.org/avogadro2) seems to be incorrect.

The correct URL seems to be https://www.openchemistry.org/projects/avogadro2/

**Comment by gaurivn** [comment]
I think it was intended for the logo and not the webpage.

**Comment by ghutchis** [comment]
Thanks for the heads-up. We're migrating and need to create a new project page anyway.
