### ISSUE TITLE
Version in cmake script doesn't match the tag

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#526]
Verision 1.93.1

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 12.2
 - Version 1.93.1
 - Compiler clang-10
 
**Describe the bug**
Version here https://github.com/OpenChemistry/avogadrolibs/blob/master/CMakeLists.txt#L31 doesn't match the tag. VERSION_PATCH is "0" when it should be "1".

**Comment by kevinsmia1939** [comment]
This should fix the issue.

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by kevinsmia1939** [comment]
> I would like to work on this issue.

https://github.com/OpenChemistry/avogadrolibs/pull/532

**Comment by ghutchis** [comment]
This is fixed in #605 for 1.94.0
