### ISSUE TITLE
fatal error: 'avogadromolequeueexport.h' file not found

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#527]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.93.1
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: FreeeBSD
 - Version 12.2
 - Compiler clang-10

**Describe the bug**
```
#include "avogadromolequeueexport.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by kevinsmia1939** [comment]
Have you build molequeue?

**Comment by ghutchis** [comment]
This is a duplicate.
