### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Schamnad** [OpenChemistry/avogadrolibs#53]
Hello there
I tried following the steps to build the OpenChemistry package provided in the [wiki](http://wiki.openchemistry.org/Build) 

>  mkdir openchemistry-build
>  cd openchemistry-build
>  cmake ../openchemistry
>  make -j5

The problem arises in the make step, it throws up the following error : 

> -- downloading...
>      src='http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz/download'
>      dst='/home/sanjeed/GSOC/openchemistry-build/Downloads/boost_1_55_0.tar.gz'
>      timeout='none'
> CMake Error at glew-prefix/src/glew-stamp/download-glew.cmake:9 (file):
>   file DOWNLOAD HASH mismatch
>     for file: [/home/sanjeed/GSOC/openchemistry-build/Downloads/glew-1.10.0.tgz]
>       expected hash: [2f09e5e6cb1b9f3611bcacxxxxxxxxxx] (edited the last 10 characters)
>         actual hash: [d41d8cd98f00b204e98009xxxxxxxxxx]
> make[2]: *** [thirdparty/glew-prefix/src/glew-stamp/glew-download] Error 1
> [ 17%] CMake Error at boost-prefix/src/boost-stamp/download-boost.cmake:9 (file):
>   file DOWNLOAD HASH mismatch
>     for file: [/home/sanjeed/GSOC/openchemistry-build/Downloads/boost_1_55_0.tar.gz]
>       expected hash: [93780777cfbf999a600f62xxxxxxxxxx] (edited the last 10 characters)
>         actual hash: [d41d8cd98f00b204e98009xxxxxxxxxx]
> make[1]: *** [thirdparty/CMakeFiles/glew.dir/all] Error 2
> 

I've been trying to search for a solution to this problem, but to no avail. 
Has anyone faced this issue before? Any help would be appreciated

System : Ubuntu 14.04
gcc version 4.9.3 (Ubuntu 4.9.3-8ubuntu2~14.04)

**Comment by cryos** [comment]
We perform simple MD5 hashing to ensure that the downloaded files match what was developed against. It would appear that your downloads do not match, I will take a look at fresh downloads to see if they have possibly been modified upstream.

**Comment by ghutchis** [comment]
@cryos I might suggest we bump the versions of the downloads anyway. Boost is now at 1.60, GLEW is at 1.13, etc.

**Comment by cryos** [comment]
@ghutchis, on Linux you can simply use the package manager, and it is often the simpler/quicker solution. For Windows I am working on this, but I just verified that the MD5 for Boost matches, and it is a local issue. Updating dependencies will not solve this problem, SourceForge does not generally let you change an uploaded file and so this issue is rare with any file hosted there.

**Comment by cryos** [comment]
@SSchamnad I have verified that the Boost source file MD5 does in fact match, and would advise you to use cmake-gui in the build directory and turn on USE_SYSTEM_BOOST, GLEW, etc, and install these packages with your package manager. If you want to build them all you will need to investigate what is wrong with your internet connection, as I am seeing the same MD5 results from freshly downloaded files.

**Comment by kash1102** [comment]
Is opengl a pre-requisite ?since Glew is openGl extension. If openGl is to be installed then which version of it.

**Comment by cryos** [comment]
GLEW is a library to aid in detecting OpenGL extensions at run time. There is only one version of the OpenGL headers/libraries, and extensions must be detected at run time, when you install GLEW it should bring in the right dependencies, on Debian/Ubuntu there are often -dev versions of the packages that have headers etc that are split from the main packages. OpenGL is required, hopefully this makes it clearer, we could use a little help to build up relevant package names for different Linux distributions to get people up and running more quickly, you will also need Qt 5 and its development packages.

**Comment by cryos** [comment]
I added some comments on prerequisites to the build page, it would be great to expand this out to make it easier for people to get up and running.

**Comment by kash1102** [comment]
Thanks for the help . Also I have sent a mail on the mailing listhttp://public.kitware.com/pipermail/openchemistry-developers/2016-March/thread.html#107 regarding how should i get started to contribute. It would be great if you could guide me regarding this.

**Comment by cryos** [comment]
I answered you on there, it is possible your download was interrupted, and so simply running the build command again would trigger another attempt to download the sources. I am now removing all of my locally cached tarballs to double check the MD5 sums match, this is a basic sanity check to ensure that the source tarball hasn't been corrupted.

**Comment by SSchamnad** [comment]
I faced a few peculiar issues when I tried to go through the entire process once again.
 When running make -j5, the process initially crashed with an error

> CMake Error at /home/sanjeed/GSOC/openchemistry-build/prefix/lib/cmake/kdsoap/KDSoapMacros.cmake:27 (qt4_wrap_cpp):
>   Unknown CMake command "qt4_wrap_cpp".
> Call Stack (most recent call first):
>   molequeue/app/CMakeLists.txt:114 (kdsoap_generate_wsdl)
> 
> 
> -- Configuring incomplete, errors occurred!

Followed the steps followed [here](http://stackoverflow.com/questions/5998100/error-in-cmake-path) to solve it. To my dismay, when I tried continuing the process it threw up another error

> In file included from /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/queues/queueuit.h:20:0,
>                  from /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/queuemanager.cpp:30:
> /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/credentialsdialog.h:20:25: fatal error: QtGui/QDialog: No such file or directory
>  #include <QtGui/QDialog>
>  

I figured out the problem was the mismatch between QT4 and QT5 as a few other people had faced a similar issue [here](http://stackoverflow.com/questions/14260475/qdialog-not-such-file-or-directory-qt-windows)
Some code in Molequeue/queueuit.cpp has been [deprecated](http://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5#toAscii.28.29_and_fromAscii.28.29_Methods_are_deprecated) and isn't compatible with QT4 (I've made the necessary changes and submitted a pull request). 

Molequeue was succesfully built after these changes. A few build errors still remain, will update accordingly

**Comment by cryos** [comment]
On Thu, Mar 3, 2016 at 4:50 PM, Sanjeed Schamnad
<notifications@github.com> wrote:
>
> I faced a few peculiar issues when I tried to go through the entire process once again.
> When running make -j5, the process initially crashed with an error
>
> CMake Error at /home/sanjeed/GSOC/openchemistry-build/prefix/lib/cmake/kdsoap/KDSoapMacros.cmake:27 (qt4_wrap_cpp):
> Unknown CMake command "qt4_wrap_cpp".
> Call Stack (most recent call first):
> molequeue/app/CMakeLists.txt:114 (kdsoap_generate_wsdl)
>
> -- Configuring incomplete, errors occurred!

You turned on a non-default, and I haven't tested that in a while. It
is a good catch!
>
> Followed the steps followed here to solve it. To my dismay, when I tried continuing the process it threw up another error
>
> In file included from /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/queues/queueuit.h:20:0,
> from /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/queuemanager.cpp:30:
> /home/sanjeed/GSOC/openchemistry/molequeue/molequeue/app/credentialsdialog.h:20:25: fatal error: QtGui/QDialog: No such file or directory
> #include
>
> I figured out the problem was the mismatch between QT4 and QT5 as a few other people had faced a similar issue here
> Some code in Molequeue/queueuit.cpp has been deprecated and isn't compatible with QT4 (I've made the necessary changes and submitted a pull request).
>
> Molequeue was succesfully built after these changes. A few build errors still remain, will update accordingly

Thanks, I hadn't tested that build configuration in a while, just
rebuilding it that way now.

Marcus

**Comment by cryos** [comment]
On Thu, Mar 3, 2016 at 4:55 PM, Marcus D. Hanwell
<marcus.hanwell@kitware.com> wrote:
> On Thu, Mar 3, 2016 at 4:50 PM, Sanjeed Schamnad
> <notifications@github.com> wrote:
>>
>> I faced a few peculiar issues when I tried to go through the entire process once again.
>> When running make -j5, the process initially crashed with an error
>>
>> CMake Error at /home/sanjeed/GSOC/openchemistry-build/prefix/lib/cmake/kdsoap/KDSoapMacros.cmake:27 (qt4_wrap_cpp):
>> Unknown CMake command "qt4_wrap_cpp".
>> Call Stack (most recent call first):
>> molequeue/app/CMakeLists.txt:114 (kdsoap_generate_wsdl)
>>
>> -- Configuring incomplete, errors occurred!
>
> You turned on a non-default, and I haven't tested that in a while. It
> is a good catch!

You don't need UIT support, I would suggest disabling
BUILD_MOLEQUEUE_UIT which you must have turned on (it is off by
default), and I can work up a patch to upgrade kdsoap which is what I
suspect is causing your follow on issues.

Marcus

**Comment by SSchamnad** [comment]
Thanks Marcus, the issue went away after disabling UIT support.
Majority of the packages get built but it still throws up a few errors with regard to HDF5

> /usr/bin/ld: warning: libhdf5_debug.so.8.1.0, needed by ../../lib/libAvogadroIO.so, not found (try using -rpath or -rpath-link)
> ../../lib/libAvogadroIO.so: undefined reference to `H5Pcreate'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Sget_simple_extent_dims'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Sget_simple_extent_ndims'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Fcreate'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Sclose'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dopen2'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Oget_info_by_name'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dwrite'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Screate_simple'
> ../../lib/libAvogadroIO.so: undefined reference to `H5check_version'
> ../../lib/libAvogadroIO.so: undefined reference to `H5P_CLS_LINK_CREATE_g'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Lexists'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dget_space'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Oexists_by_name'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dclose'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Ldelete'
> ../../lib/libAvogadroIO.so: undefined reference to `H5open'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dread'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Fopen'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Fclose'
> ../../lib/libAvogadroIO.so: undefined reference to `H5T_NATIVE_DOUBLE_g'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Dcreate2'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Pset_create_intermediate_group'
> ../../lib/libAvogadroIO.so: undefined reference to `H5Ovisit'
> collect2: error: ld returned 1 exit status

I installed HDF5 seperately and used cmake-gui to use the systems HDF5 to build as well as not use it while generating the files. This error seems persistent; I am unable to find this exact error online nor am I able to find this  libhdf5_debug.so.8.1.0 file.

![hdf5](https://cloud.githubusercontent.com/assets/7796078/13556526/9945a75c-e401-11e5-9441-395beedd7e3e.png)
shows the different setting being selected.

**Comment by SSchamnad** [comment]
After a little more investigation, I found a [issue page](http://ubuntuforums.org/archive/index.php/t-2255343.html) similar to mine. They have provided the fix to it by adding flags to the cmake while building the source

> cmake -DCMAKE_INCLUDE_PATH=$HOME/opt/hdf5/include -DCMAKE_LIBRARY_PATH=$HOME/opt/hdf5/lib

This doesn't work while doing the out of source directory build in our case - throws the following warning

> CMake Warning:  Manually-specified variables were not used by the project:    CMAKE_INCLUDE_PATH

To further investigate, I ran cmake -LAH | grep "HDF5"  to search for variables with hdf5, here are the results

> // HDF5 C++ Wrapper compiler.  Used only to detect HDF5 compile flags.
> HDF5_CXX_COMPILER_EXECUTABLE:FILEPATH=/usr/bin/h5c++
> // HDF5 Wrapper compiler.  Used only to detect HDF5 compile flags.
> HDF5_C_COMPILER_EXECUTABLE:FILEPATH=/usr/bin/h5cc
> HDF5_C_INCLUDE_DIR:PATH=/usr/include/hdf5/serial
> // HDF5 file differencing tool.
> HDF5_DIFF_EXECUTABLE:FILEPATH=/usr/bin/h5diff
> // The directory containing a CMake configuration file for HDF5.
> HDF5_DIR:PATH=HDF5_DIR-NOTFOUND
> // HDF5 Fortran Wrapper compiler.  Used only to detect HDF5 compile flags.
> HDF5_Fortran_COMPILER_EXECUTABLE:FILEPATH=/usr/bin/h5fc
> // HDF5 library compiled with parallel IO support
> HDF5_IS_PARALLEL:BOOL=FALSE
> HDF5_dl_LIBRARY_DEBUG:FILEPATH=HDF5_dl_LIBRARY_DEBUG-NOTFOUND
> HDF5_dl_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libdl.so
> HDF5_hdf5_LIBRARY_DEBUG:FILEPATH=HDF5_hdf5_LIBRARY_DEBUG-NOTFOUND
> HDF5_hdf5_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so
> HDF5_m_LIBRARY_DEBUG:FILEPATH=HDF5_m_LIBRARY_DEBUG-NOTFOUND
> HDF5_m_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libm.so
> HDF5_pthread_LIBRARY_DEBUG:FILEPATH=HDF5_pthread_LIBRARY_DEBUG-NOTFOUND
> HDF5_pthread_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libpthread.so
> HDF5_z_LIBRARY_DEBUG:FILEPATH=HDF5_z_LIBRARY_DEBUG-NOTFOUND
> HDF5_z_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libz.so
> // Should we use the system HDF5?
> USE_SYSTEM_HDF5:BOOL=ON

Cmake is unable to find the HDF5 DIR..

**Comment by Schamnad** [comment]
Finally solved it!
The problem lies in the line 

> /usr/bin/ld: warning: libhdf5_debug.so.8.1.0, needed by ../../lib/libAvogadroIO.so, not found (try using -rpath or -rpath-link)

Even when you use cmake-gui to configure the system to download HDF5 and not use the system HDF5, the build searches for _libhdf5_debug.so.8.1.0_ in usr/bin/lib when the actual file is created in /**OpenChemistrybuild-dir**/prefix/lib

Solved it by just copying libhdf5_debug.so.8.1.0 into /usr/bin/lib

For some reason, even when I build HDF5 from its source package, the file libhdf5_debug.so.8.1.0 is not created in /usr/bin/lib in Ubuntu 14.04..

Problem resolved for now. Closing it
