### ISSUE TITLE
Update artifact comments action

### ISSUE THREAD

**Issue by tonyhallett** [OpenChemistry/avogadrolibs#538]
@ghutchis 

As per https://github.com/OpenChemistry/avogadrolibs/commit/f298a1d4edf97d82a10c8de3c1202bcc9b624fdb#commitcomment-49183314

I have update the [action](https://github.com/marketplace/actions/workflow-artifact-pull-request-comment) to support push and pull_request workflows.  Hopefully that is sufficient for your needs.  For now I am not creating a separate action for the comments that is used internally by this action but if you are interested this action uses code from https://www.npmjs.com/package/@tonyhallett/github-actions see https://github.com/tonyhallett/github-actions/blob/de970ebd13063923f23e56733b7b3655b8358c87/src/workflow/artifacts/getWorkflowArtifactsComment.ts#L54

**Comment by ghutchis** [comment]
@tonyhallett - thank you, I'll check it out shortly

**Comment by ghutchis** [comment]
Looks like it works perfectly, thanks!

**Comment by tonyhallett** [comment]
@ghutchis Great.  Be sure to update the version in your workflow if you want the same behaviour for push.  If you do not then as it stands you are going to get a failing workflow for every push like https://github.com/OpenChemistry/avogadrolibs/actions/runs/723375613
