### ISSUE TITLE
In README.md, logo for Avogadro2 & Open Chemistry Project is not displayed

### ISSUE THREAD

**Issue by uniyalabhishek** [OpenChemistry/avogadrolibs#541]
**Describe the bug**
In README.md, logo for Avogadro2 & Open Chemistry Project is not displayed.

**Expected behavior**
Source is from https://camo.githubusercontent.com, img should be loaded as expected.

**Additional context**
This is the url for Avogadro2 logo that is currently being used
https://camo.githubusercontent.com/e54155f80c013b1a465a6da0953c1b1ce4ec4443a3929feb93014da51d3af284/687474703a2f2f6f70656e6368656d69737472792e6f72672f66696c65732f6c6f676f732f61766f676164726f322e706e67

I would like to resolve this issue, can I upload the images in a separate folder and then use it in README or it can only be resolved by the maintainer?

**Comment by jhalak27** [comment]
Hey, can I work on this?

**Comment by uniyalabhishek** [comment]
@jhalak27 I am also a contributor like you, go ahead if you can resolve it. As I mentioned in the comment, the link is currently being used from https://camo.githubusercontent.com, which might be used by the maintainer, so waiting from the go ahead by the maintainers of this repository, whether we can add the images in a file and then use it in README.md, which will close this issue.

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by uniyalabhishek** [comment]
By maintainer-Not required, The goal is for the 128px version in the README with a link to the 512px version.
