### ISSUE TITLE
Run clang-tidy on pull requests

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#550]
It would be great to run static analysis tools on pull requests.

One that looks really good:
https://github.com/marketplace/actions/clang-tidy-review

* It only runs on changes in the pull request
* Adds comments inline to the PR code
* Can use `compile_commands.json` (`-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to `cmake`)

An example with similar Qt build process:
https://github.com/Mudlet/Mudlet/blob/development/.github/workflows/clangtidy-diff-analysis.yml

(Basically, we'd clone the current `build_cmake.yml` for a `clang tidy-diff-analysis.yml` and run this new action)

**Comment by ghutchis** [comment]
Clazy would also be *really* helpful:
https://github.com/KDE/clazy

**Comment by PratyushD35** [comment]
@ghutchis  I am new to open source . I want to contribute .Can you please guide?

**Comment by ghutchis** [comment]
Sure. I can think of a few ways to help.
- Build OpenChemistry yourself (http://two.avogadro.cc/build.html) and make sure to use `-DCMAKE_EXPORT_COMPILE_COMMANDS` when you first run `cmake`
- Run `clang-tidy` on your new build. You'll probably have lots of comments. Upload that or run some of the "fixit" commands.
- Run `clazy` on the new build. As above, upload the warnings or run some of the "fixit" options.

Another option is to take a look at the branch I created (https://github.com/OpenChemistry/avogadrolibs/pull/551/)

This creates a .github workflow for running clang-tidy on the GitHub servers. 

I'd probably suggest Option 1 if you're just starting.

**Comment by ghutchis** [comment]
This is now handled by #668
