### ISSUE TITLE
Add support for Wayland

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenChemistry/avogadrolibs#567]
**Is your feature request related to a problem? Please describe.**
It will be some time before Wayland gain adoption. But since Ubuntu 21.04 and Fedora 34 switch to Wayland as default.
Avogadro in Wayland is broken at the moment. If I were to guess, it might be because broken glew on Wayland. So when glew support it, Avogadro might be.

**Describe the solution you'd like**
Run Avogadro on Wayland.

**Describe alternatives you've considered**

**Additional context**
https://discuss.avogadro.cc/t/will-avogadro-support-wayland/3499

**Comment by ghutchis** [comment]
As  I mentioned on the discussion forum, while there's a potential fix for GLEW,  there are also several alternatives:
- https://github.com/anholt/libepoxy
- https://github.com/skaslev/gl3w

I'd probably lean towards gl3w when we switch to the core profile.

**Comment by matterhorn103** [comment]
Noticed this issue while browsing the repo. I am running 1.98.1 on Wayland (KDE Plasma 5.27.9 on OpenSUSE Tumbleweed) just fine. Presumably this means the problem has since been resolved?

**Comment by kevinsmia1939** [comment]
> Noticed this issue while browsing the repo. I am running 1.98.1 on Wayland (KDE Plasma 5.27.9 on OpenSUSE Tumbleweed) just fine. Presumably this means the problem has since been resolved?

Where did you download from?

**Comment by matterhorn103** [comment]
Ok, this seems to only be true for the AppImage version, as when I build from source, I get graphical glitches.

@kevinsmia1939 The AppImage from https://two.avogadro.cc/ and the [nightly build](https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip) available via the readme of the repo both work fine on my PC on the Wayland session. Are they are broken for you?
