### ISSUE TITLE
Add support for selection

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/avogadrolibs#57]
Atom/bond selection is missing, and one of the major holes in editing functionality at this stage. This is the next thing I intend to add as a new feature.

**Comment by ghutchis** [comment]
I was talking with colleagues here and if selection was added even as a API, it could be quickly elaborated (e.g., select atoms within X Å, "fill" inside a selected region, etc.)

**Comment by cryos** [comment]
This is partially done, moving to 1.91 as it is far from complete.

**Comment by ghutchis** [comment]
I'm going to tag an incomplete list of actions / tools that need selection support (#140)

Commands / Extensions:
* Bond / Remove Bonds (partial support in #140)
* Add / Remove Hydrogens
* Cut / Copy / Paste / Clear

Tools:
* Manipulate (partial support in #140)

**Comment by ghutchis** [comment]
Paste (and other appendMolecule commands) now support selection with #151

**Comment by ghutchis** [comment]
AFAICT this is all supported in `master`. Additional features are welcome, but the basics are there.
