### ISSUE TITLE
Error reading Gaussian09 output files

### ISSUE THREAD

**Issue by gmseabra** [OpenChemistry/avogadrolibs#571]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: (e.g. 1.90.0-316-g6d14770)
 - Qt: (e.g., 5.9.5)

**Desktop version: (please complete the following information):**
 - OS: RHEL 8.2
 - Linux 4.18.0-193.19.1.el8_2.x86_64
 - Compiler `cmake`

**Describe the bug**
Cannot read Gaussian09 output file. When trying to open a G09  output file, OpenBabel just gives the message:
```
File Error:
Error while reading file '/home/seabra/work/li/hitopt/systems/hCOX-2/md/parm/COX-2_HEM_small_opt.g09':
OpenBabel error: conversion failed.
```

the following is printed on the command line:
```
OBProcess::executeObabel: Running "obabel" "-ig16 -ocml"
"obabel"  stderr:
 "0 molecules converted\n"
Process encountered an error, and did not execute correctly.
	Exit code: 0
	Exit status: QProcess::NormalExit
	Exit output: ""
```
And it does not read information from the file.

**To Reproduce**
1. Go to 'Open'
2. Click on 'Files of Type'
3. Scroll down to 'Gaussian Output (*.g09 *.g04...)'
4. Choose a file from the list 
5. Click open.

**Expected behavior**
It should open the file and the molecule show up in the screen. 

** Additional Information **
I attached a file where it happens.

** File Attached **
[COX-2_HEM_small_opt.g09.gz](https://github.com/OpenChemistry/avogadroapp/files/6475190/COX-2_HEM_small_opt.g09.gz)

**Comment by ghutchis** [comment]
Huh. I can reproduce the bug, but strangely, when I use Open Babel directly, it works just fine:
`obabel COX-2_HEM_small_opt.g09.gz -ocml`

**Comment by gmseabra** [comment]
Hum... Is it possible that something is being lost when sent to OpenBabel?

**Comment by ghutchis** [comment]
I don't know what's going on.. Right now (and I mean right now) any Gaussian file in Avogadro isn't read through Open Babel.
- FCHK works because Avo2 has code that does it natively
- It's not the molecule because H2O.g09 also failed (!)

Other things (Q-Chem, GAMESS, Orca, etc.) all work.

If I call `obabel` myself with the Gaussian files, they work fine.

I'll look into it more tomorrow.

**Comment by ghutchis** [comment]
As a workaround, if you install the `cclib` Python package, when reading Gaussian files (or generic `.out` or `.log` files) there should be a "User Script: CJSON" entry in the dialog that pops up. That works fine, although I don't know if it supports all possible data yet.

I still can't figure out why the `obabel` imports are failing for Gaussian .. it works on the command-line and everything else I throw at it seems to work.

**Comment by gmseabra** [comment]
> As a workaround, if you install the `cclib` Python package, when reading Gaussian files (or generic `.out` or `.log` files) there should be a "User Script: CJSON" entry in the dialog that pops up. That works fine, although I don't know if it supports all possible data yet.
> 
> I still can't figure out why the `obabel` imports are failing for Gaussian .. it works on the command-line and everything else I throw at it seems to work.

I did instal `cclib` locally (`conda install cclib`), but I still don't get this option.  Do I need to recompile Avogadro in order for it to show up? (I am running Avogadro2 in the same conda env where I installed `cclib`.)

Thanks! (I wish I could be of any more help)

**Comment by ghutchis** [comment]
That took longer than expected - once this builds, please let me know if it works for you. (The buildbot should comment on this issue with the binaries.)

**Comment by gmseabra** [comment]
Well, I tried to compile it clean, but removing everything, checking-out a brand new version of OpenChemistry and compiling following the OpenChemistry instructions, but now the compilation fails because it misses `SPGLIB_INCLUDE_DIR`:

```
(openchemistry) $ rm -rf .*
(openchemistry) $ git clone --recursive git://github.com/OpenChemistry/openchemistry.git
(openchemistry) $ mkdir openchemistry-build
(openchemistry) $ cd openchemistry-build/
(openchemistry/openchemistry-build) $ cmake ../openchemistry
(openchemistry/openchemistry-build) $ cmake --build . --config Release
[...]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SPGLIB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core
   used as include directory in directory /home/seabra/work/source/repos/openchemistry/openchemistry/avogadrolibs/avogadro/core

-- Configuring incomplete, errors occurred!
See also "/home/seabra/work/source/repos/openchemistry/openchemistry-build/avogadrolibs/CMakeFiles/CMakeOutput.log".
See also "/home/seabra/work/source/repos/openchemistry/openchemistry-build/avogadrolibs/CMakeFiles/CMakeError.log".
gmake[2]: *** [CMakeFiles/avogadrolibs.dir/build.make:114: avogadrolibs-prefix/src/avogadrolibs-stamp/avogadrolibs-configure] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/avogadrolibs.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
(openchemistry/openchemistry-build) $

**Comment by souzajp** [comment]
Good afternoon.

Has this problem with the error reading files from gaussian 09 been resolved? I'm having the same problem too

**Comment by Imnuts7** [comment]
I'm still having this problem in 1.95.1.

**Comment by bennski** [comment]
I'm also having this problem with 1.93.0-1
