### ISSUE TITLE
Add support for fragments to the molecule

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/avogadrolibs#58]
Support for fragments is important in a number of areas, including residues in biological structures, monomer units in polymers, etc.

**Comment by ghutchis** [comment]
From the discussion on the mailing list, this means there's support needed in Molecule (i.e., storing fragments) and also RWMolecule (i.e., undo/redo for adding, deleting, renaming fragments).

One key question is how to invalidate a fragment. For example, a "residue" should consider invalidating if an atom is removed or element changed (e.g., C->N means a different residue).

I would think there's a general Fragment base class needed, and then the Residue sub-class can intelligently handle changes to atoms/bonds.
