### ISSUE TITLE
1.94.0 installs an empty directory share/avogadro2/molecules

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#609]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.94.0

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 13

**Describe the bug**
Project shouldn't install empty directories.

**Comment by yurivict** [comment]
I couldn't reproduce this later.

**Comment by drew-parsons** [comment]
I think this was not a bug as such.  The Molecules data is contained in a separate repository (https://github.com/OpenChemistry/molecules). If that data was not downloaded and available at build time then the avogadro installation would install an empty directory to stand in for it.
