### ISSUE TITLE
USE_SPGLIB only installs header file without USE_QT, and also installs SpaceGroup.a with USE_QT

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#610]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.94.0
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: FreeBSD
 - Compiler: clang-11

**Describe the bug**
The header ```include/avogadro/core/avospglib.h``` and the corresponding library ```lib/avogadro2/staticplugins/SpaceGroup.a``` should be installed together. Currently ```USE_SPGLIB``` only enables the header, and then ```USE_QT``` enables the library.
If Qt is required for ```USE_SPGLIB``` it should break and say so when ```USE_SPGLIB=ON  USE_QT=OFF```

**Comment by ghutchis** [comment]
No, I think this is the correct behavior. The SpaceGroup.a is the Qt-based plugin for the GUI. The header can be used, e.g, by the Jupyter Python code. Right now, it doesn't use `spacegroup.h` but it will. The underlying non-Qt code uses `spglib` and doesn't need `SpaceGroup.a`
