### ISSUE TITLE
Doesn't install the 'crystals' directory when it is supplied by the caller

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#611]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.94.0

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 13

**Describe the bug**
Here https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/insertfragment/CMakeLists.txt#L48 crystals are only installed when downloaded with git, and not when this directory is supplied by the caller. This is different from the ```molecules``` directory that is (correctly) installed when it is supplied by the caller.

**Comment by ghutchis** [comment]
Thanks - it's the endif() in the wrong spot. I'll go fix that - sorry!

**Comment by ghutchis** [comment]
When I saw the issue posted, I thought 'that's weird, it's parallel code" - but no, it's not. Thanks for the issue.
