### ISSUE TITLE
Python bindings fail to build: Unknown CMake command "python3_add_library"

### ISSUE THREAD

**Issue by yurivict** [OpenChemistry/avogadrolibs#612]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.94.0

**Desktop version: (please complete the following information):**
 - OS: FreeBSD 13
 - Compiler clang-11

**Describe the bug**
```
-- Found pybind11: /usr/local/include (found version "2.6.2" )
CMake Error at /usr/local/share/cmake/pybind11/pybind11NewTools.cmake:196 (python3_add_library):
  Unknown CMake command "python3_add_library".
Call Stack (most recent call first):
  CMakeLists.txt:38 (pybind11_add_module)
```

```FindPython3``` documentation (https://cmake.org/cmake/help/latest/module/FindPython3.html) says that it defines ```Python3_add_library```, but you only call ```find_package(Python3 REQUIRED)```.

**Comment by BeatWolf** [comment]
How was this solved?

**Comment by yurivict** [comment]
Sorry, I don't remember.
