### ISSUE TITLE
Selecting atoms tools fails 

### ISSUE THREAD

**Issue by serk12** [OpenChemistry/avogadrolibs#614]
**Avogadro version:**
 - Avogadrolibs: 1.90.0 (master)
 - Qt: 5.12.8

**Desktop version:**
 - OS: ubuntu 20.04

**Describe the bug**

- The selecting tool have a strange behavior, I think it's when selecting more than half a bond.
- The selecting tool don't select if you move from bottom-left to top-right and vice versa. 

**To Reproduce**
1. Create a simple ethane molecule
2. Change to selection (don't move the camera)
3. Select the left part to 60-70% the bond

**Expected behavior**
Select only the left part

**Screenshots**

https://user-images.githubusercontent.com/10197352/121248032-3804df80-c8a3-11eb-8427-cdf08fbe24cc.mp4

**Comment by ghutchis** [comment]
`master HEAD` at the moment is 1.94, but it's worth investigating. I found a few selection bugs in the last few weeks.

**Comment by serk12** [comment]
No I have a normal 1080p screen. I also think it's something with the mapping, if you move the camera the bug behaves completely different, like bottom-left to top-right works but top-right to bottom-left don't, etc...

**Comment by serk12** [comment]
I've downloaded the Windows version and nothing from the selecting tool does work (I use windows 10 home).

**Comment by ghutchis** [comment]
@serk12 - do you want to try the Windows version now? It should be:
https://github.com/OpenChemistry/avogadrolibs/suites/2960459395/artifacts/66696306

Please let me know if we should close this.

**Comment by serk12** [comment]
Yes you can close it. I was testing the [old 1.91.0 version](https://www.openchemistry.org/downloads/).

**Comment by ghutchis** [comment]
Yes, that version didn't have the "rubber band selection" implemented yet.
