### ISSUE TITLE
[i18n] Fuzzy Entries are Wrong

### ISSUE THREAD

**Issue by e-kwsm** [OpenChemistry/avogadrolibs#619]
For example,
https://github.com/OpenChemistry/avogadrolibs/blob/1c6ea67720d3f33db002d9efe072e6904c53659a/i18n/en_GB.po#L200-L203
and
https://github.com/OpenChemistry/avogadrolibs/blob/1c6ea67720d3f33db002d9efe072e6904c53659a/i18n/en_GB.po#L221-L224

**Comment by e-kwsm** [comment]
The corresponding German messages:
https://github.com/OpenChemistry/avogadrolibs/blob/1c6ea67720d3f33db002d9efe072e6904c53659a/i18n/de.po#L199-L202
https://github.com/OpenChemistry/avogadrolibs/blob/1c6ea67720d3f33db002d9efe072e6904c53659a/i18n/de.po#L220-L223

**Comment by ghutchis** [comment]
If you want to submit a patch that just empties out fuzzy strings, that would be great. I suspect they came over in the migration from 1.2.

**Comment by e-kwsm** [comment]
Some of the entries are wrong, and some of them seem (basically) correct. For example,

https://github.com/OpenChemistry/avogadrolibs/blob/beda0ec61aca005933a903c503ba1c0168243b12/i18n/en_GB.po#L1503-L1509
https://github.com/OpenChemistry/avogadrolibs/blob/beda0ec61aca005933a903c503ba1c0168243b12/i18n/en_GB.po#L3900-L3903

**Comment by ghutchis** [comment]
I think I'd still be okay with eliminating all fuzzy match, but if you want to go through them, that would be extremely helpful.

**Comment by ghutchis** [comment]
Just to check in, since you've checked them.. do you think it's worth review, or should I just script to drop all the fuzzy matches? Thanks.

**Comment by e-kwsm** [comment]
I will create a PR.

**Comment by e-kwsm** [comment]
I just translated to Japanese on weblate, but again there are wrong fuzzy entries, which are annoying. For example,

https://github.com/OpenChemistry/avogadrolibs/blob/a68514a4479fd45b897f87d6d1341099bb3d5c61/i18n/ja.po#L4863-L4867

**Comment by e-kwsm** [comment]
https://github.com/OpenChemistry/avogadrolibs/blob/a68514a4479fd45b897f87d6d1341099bb3d5c61/i18n/bs.po#L4851-L4855

https://github.com/OpenChemistry/avogadrolibs/blob/a68514a4479fd45b897f87d6d1341099bb3d5c61/i18n/bs.po#L4892-L4896

https://github.com/OpenChemistry/avogadrolibs/blob/a68514a4479fd45b897f87d6d1341099bb3d5c61/i18n/bs.po#L8087-L8091

https://github.com/OpenChemistry/avogadrolibs/blob/a68514a4479fd45b897f87d6d1341099bb3d5c61/i18n/bs.po#L8101-L8105

**Comment by ghutchis** [comment]
I saw your message, but please re-open bugs if things happen again - it's much easier for me to track, thanks.

I'm pretty sure I turned off "fuzzy" on Weblate now. As far as I can tell, that's the only part of the infrastructure that's creating the issue.

I _don't_ know if existing "fuzzy" markers remain. If so, please open a new bug and we can clean them out (e.g., a Python script to remove the msgstr when marked fuzzy.
