### ISSUE TITLE
Boost::Python vs PyBind11? Design discussion.

### ISSUE THREAD

**Issue by barrymoo** [OpenChemistry/avogadrolibs#64]
I was curious if you made your mind up on Boost::Python? Versus something like PyBind11? In my, albeit little, experience with Boost::Python it can be a little tedious with Python 3 (compiled part of Boost). I have switched my tools over to PyBind11 and it seems much more flexible.

**Comment by ghutchis** [comment]
Reins had suggested PyBind11 as part of his GSoC project. We hope to hear from him soon about his planned directions.

**Comment by cryos** [comment]
Yes, I would like to keep the minimal Boost.Python support for now as it is used in a web project - I used it with Python 3 without issue but the dependencies are also a concern. I think it should be replaced by PyBind11, and as Geoff said hope to hear from our student soon who proposed this approach.

**Comment by cryos** [comment]
It looks like we are not going to hear from the student, I am actually hoping to explore this further myself as I think it looks like a great approach.

**Comment by barrymoo** [comment]
I am now using it in my CubeFile library (https://github.com/barrymoo/Scripts/blob/master/library/CubeFile/CubeFile-pybind11.cpp), if you're interested.

**Comment by ghutchis** [comment]
I'm closing this - it seems like PyBind11 is working well.
