### ISSUE TITLE
Rotate fragment around atom

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#645]
At the moment (1.9.4), a fragment of a molecule can be selected and moved, keeping the internal geometry within the fragment intact. But the relationship of the fragment to the rest of the molecule is not constrained, apart from maintaining the identity of bonds between fragment and molecule. So those bonds become stretched when the fragment is moved.

It could be a nice enhancement to allow for that bond length to the rest of the molecule to remain fixed (this makes sense only if there is only one connecting bond).  In this cause moving the fragment becomes equivalent to rotating the fragment around the atom that the fragment is connected to.

A different alternative constraint which could also be useful is to fix the position of one of the atoms inside the fragment. In this scenario moving the fragment becomes equivalent to rotating the fragment around that atom. (Perhaps this is just a special case of the first case, obtained by deselecting the atom in question).

**Comment by ghutchis** [comment]
I mean, the current behavior is a direct port from 1.x.

It's possible to do what you're describing in 1.x by editing the torsion or angle involving the fragment.

But I'm having trouble thinking of the user experience with the mouse:
- Avo detects that you're connected by one bond
- Instead of free-form movement, it rotates around that one bond

That sounds like the bond-centric manipulate tool - click on the bond, move it, change torsions, etc.

So how would the "rotate around the atom" be different from the bond-centric manipulate?

**Comment by drew-parsons** [comment]
I see it now, I didn't think of the bond-centric tool.  You're absolutely right, it already does what I'm looking for.

It rotates one bond around another bond, fixing the angle between them.  That gives part of the rotation I'm looking for (changing the torsion angle).

The last part of the rotation, changing the bond angle as well, was a bit less intuitive to find.  Eventually, I found that the trick is to click and hold on the bond, then you can rotate the blue plane passing through the bond, which determines the plane of rotation for the fragment.

I couldn't find documentation for this functionality, has some been written for it?

**Comment by ghutchis** [comment]
While this is for Avo1, it should function the same:
https://avogadro.cc/docs/tools/bond-centric-manipulate-tool/

The files themselves are here:
https://github.com/Avogadro/avogadro.cc/tree/master/_docs

I'll be updating these for Avo2 later this summer.

I'd like to add a "common tasks" set of tutorials, so if you have a suggestion for wording, please let me know. "Rotate part of the  molecule around an atom or bond"?

**Comment by drew-parsons** [comment]
Actually those docs are pretty clear . Perhaps I'd add one more line between the first two lines to explain the plane, e.g.

- To begin using the bond centric manipulate tool, click on a bond within your molecule.
- A plane intersecting the bond is displayed. By clicking on an atom and dragging, the bond is rotated around the plane,  rotating the atom and attached fragments.
- Clicking on a bond and dragging your cursor allows you to adjust the plane.

Can a link to Documentation be added to the Help menu? In the first instance this could be just a url link to https://avogadro.cc/docs/tools/bond-centric-manipulate-tool/ (or its avo2 successor).  But could also be useful to allow for docs to be installed locally (sometimes eduroam is not available!), perhaps by setting up https://github.com/Avogadro/avogadro.cc/tree/master/_docs as an installable package (I'm thinking in the context of debian packaging)

**Comment by drew-parsons** [comment]
There's one point I can't resolve consistently. In some cases rotating the bond with the bond centric tool rotates the whole fragment attached to the atom being moved, which is what I want. But in other cases moving the atom (rotating the bond) only moves the single atom, distorting the fragment. 

I'm attaching screenshots of an artificial diphenyl ether to illustrate the point.
![Screenshot from 2021-07-04 10-19-48](https://user-images.githubusercontent.com/26508288/124378465-b6417f80-dcb1-11eb-9947-192198a64ac7.png)

Suppose I want to rotate a phenyl group. I click on the right-hand O-C bond with the bond-centric tool, the C atom with the phenyl group on the right.  Then I click on the C atom (on the right) and drag.  Only the C atom moves, the rest of the phenyl group stays in place, distorting the fragment as illustrated in this snapshop,
![Screenshot from 2021-07-04 10-20-28](https://user-images.githubusercontent.com/26508288/124378532-218b5180-dcb2-11eb-81be-4d037c458b19.png)

What's also strange is if I've selected the right-hand O-C bond as above, but click and drag the left-hand C atom attached to O, then the left-hand phenyl group does rotate as a whole.

**Comment by ghutchis** [comment]
That's clearly a bug. I have a separate issue to move the "skeleton tree" code (for moving fragments like the bond centric tool) and do some cleanup. So I'll leave this issue open and rename.

**Comment by ghutchis** [comment]
As far as documentation, once I get it ported to Avo2, install sounds like a great idea. It looks like it's fairly easy to generate installable QtHelp as well as HTML from our new Sphinx docs.

**Comment by drew-parsons** [comment]
Thanks Geoff!

**Comment by ghutchis** [comment]
Besides the documentation, this is now fixed by #1006 (it was an issue because it was an atom in a ring). I'm opening a separate issue for user documentation.
