### ISSUE TITLE
Unselected atoms become selected (and vice versa) when other atoms are deleted

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#650]
**Avogadro version: 1.94.0-371-g7479d2e **
 - Avogadrolibs: 1.9.4
 - Qt: 5.15.2

**Desktop version: **
 - OS: Debian GNU/Linux]
 - Version linux 5.10.46 (debian unstable)
 - Compiler  g++ 10.2.1

**Describe the bug**

When some atoms in a molecule are selected, and other atoms are then deleted, some of the selected atoms become deselected.

Conversely if some selected atoms are deleted, then some previously deselected atoms suddenly become selected.

My guess is that the list of selected atoms is a list of indices to the atoms in the molecule, and is not refreshed when the lists of atoms in the molecule changes (e,g, by deletion). 

**To Reproduce**
1. Create a simple ethane molecule
2. Click on Selection Tool and select the right-most methyl
![Screenshot from 2021-07-06 16-41-20](https://user-images.githubusercontent.com/26508288/124619551-09b1fa00-de79-11eb-9d79-31f64a5f2cce.png)

3. Select Build [pencil] tool
4. Delete (right-click) one of the unselected hydrogens on the left. That hydrogen disappears, but one of the hydrogens on the right becomes deselected.
![Screenshot from 2021-07-06 16-38-59](https://user-images.githubusercontent.com/26508288/124619237-c3f53180-de78-11eb-832c-2aa22ee57b0c.png)

Conversely,
2'. Click on Selection Tool and select the left-most methyl
![Screenshot from 2021-07-06 16-31-23](https://user-images.githubusercontent.com/26508288/124618220-e63a7f80-de77-11eb-89f8-0bc7e29bc573.png)

4'. Delete (right-click) one of the selected hydrogens on the left. That hydrogen disappears, but one of the hydrogens on the right becomes selected.
![Screenshot from 2021-07-06 16-31-44](https://user-images.githubusercontent.com/26508288/124618471-1b46d200-de78-11eb-96a1-7797365dd5e6.png)

**Expected behavior**

Previously deselected atoms should not suddenly become selected when atoms are removed (or added).
Previously selected atoms should not suddenly become deselected when atoms are removed (or added) (or alternatively the entire selection should get cleared).

**Comment by ghutchis** [comment]
@drew-parsons @mquevill - as far as I can tell, the patch fixes the problem...

**Comment by drew-parsons** [comment]
The patch looks like it's making the right corrections.  The codebase has diverged from 1.94.0 now so I can't apply and test so easily as a single patch.
