### ISSUE TITLE
Insert SMILES does not generate the requested molecule

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#657]
**Avogadro version: 1.94.0-371-g7479d2e**
 - Avogadrolibs: 1.94.0
 - Qt: 5.15.2

**Desktop version:**
 - OS: Debian GNU/Linux
 - Version: Linux 5.10.46 debian unstable
 - Compiler g++ 10.2.1

**Describe the bug**

The Build->Insert->Smiles function does not generate the requested molecule. No atoms or at most one carbon atom only is generated.

Export Molecule shows the atoms in the output file, but with no coordinates (i.e. all coordinates are 0.0 0.0 0.0).  

Tested with examples from https://archive.epa.gov/med/med_archive_03/web/html/smiles.html
e.g.
 - HC(H)=C(H)(H)
 - CC(O)C
 - CC(C)CC(=O)
 - C1OC1CC

**To Reproduce**
1. Go to 'Build->Insert->Smiles'
2. Enter ethene: HC(H)=C(H)(H)
3. No molecule is generated
4. Go to 'Build->Insert->Smiles' again
5. Enter propanol: CC(O)C
6. Only 1 carbon atom is visible.

The molecular information in Analysis->Properties->Molecular... asserts that all atoms are present.  And in fact all molecules are present in the output file if I export the molecule (I tested .xyz format) but all have coordinate 0.0 0.0 0.0.

**Expected behavior**

The requested molecule should be generated, the coordinates of the atoms should not all be 0.0 0.0 0.0.

**Comment by drew-parsons** [comment]
For comparison, Build-Insert-InChI works fine, generating examples from https://molecularmodelingbasics.blogspot.com/2016/05/a-brief-introduction-to-smiles-and-inchi.html,
- InChI=1S/C2H6/c1-2/h1-2H3
- InChI=1S/C7H8/c1-7-5-3-2-4-6-7/h2-6H,1H3
- InChI=1S/C3H7NO2/c1-2(4)3(5)6/h2H,4H2,1H3,(H,5,6)/t2-/m0/s1

**Comment by ghutchis** [comment]
I'm confused, since the process should be the same. If you have it compiled in Debug, it should print something like this on the terminal:
```
OBProcess::executeObabel: Running "/path/to/openchemistry/prefix/Avogadro2.app/Contents/MacOS/obabel" "-ismi -ocml --gen3d"
OBProcess::executeObabel: Running "/Users/ghutchis/Devel/build/openchemistry/prefix/Avogadro2.app/Contents/MacOS/obabel" "-iinchi -ocml --gen3d"
```

It's that `--gen3d` flag that's crucial. The code looks okay to me (i.e., SMILES and InChI should automatically have --gen3d). And if it's generating 3D coordinates for InChI, I don't know why it wouldn't work for SMILES.

Can you take a look? it would really help with debugging this.

**Comment by drew-parsons** [comment]
Debug gives this message for HC(H)=C(H)(H)
```
OBProcess::executeObabel: Running "obabel" "-ismi -ocml --gen3d"
"obabel"  stderr:
 "==============================\n*** Open Babel Error  in ParseSimple\n  SMILES string contains a character 'H' which is invalid\n0 molecules converted\n"
```

Actually CC(O)C and the other examples are working all of a sudden. Maybe something got activated under the Debug configuration?

I can generate ethene using C=C instead of HC(H)=C(H)(H)

**Comment by drew-parsons** [comment]
Strange, now CC(O)C is again not working.

The difference seems to be whether I launch from the command line, or from the window manager (Gnome).

SMILES works on CC(O)C (and H generates the error message above) if I launch from the command line.

SMILES fails if I launch via the Window Manager (which will make it a lot more difficult to debug)

**Comment by ghutchis** [comment]
I don't know if it's possible to get console messages when you launch that way? On a Mac, you can still get them through a system Console.app.

My guess is the `obabel` is not getting the right configuration / environment variables. It's still weird that InChI works...

There's no "cache" in Avogadro. There's no cache per-se in Open Babel either, although I can imagine that some of the plugins or data files could get cached by the OS.

I'd check the environment when launching via the command-line and via Gnome.

If nothing else here are relevant environment variables
`AVO_OBABEL_EXECUTABLE` = path to `obabel`
`BABEL_DATADIR` = path to data files
`BABEL_LIBDIR` = path to Open Babel plugins

Some relevant code is in `avogadro/qtplugins/openbabel/obprocess.cpp`: https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/qtplugins/openbabel/obprocess.cpp#L29

**Comment by drew-parsons** [comment]
Success or fail seems to be 50:50.  I now have a failure from the command line (trying CC(O)C). Here debug reports
```
OBProcess::executeObabel: Running "obabel" "-ismiles -ocml"
```
so when it does fail, it's trying to launch with `-ismiles -ocml` instead of `-ismi -ocml --gen3d`

**Comment by drew-parsons** [comment]
Affects somewhere around https://github.com/OpenChemistry/avogadrolibs/blob/c6bd9c138d6ef555838fa543c12a27b0f0990846/avogadro/qtplugins/openbabel/obfileformat.cpp#L122 
Is it because `formats2D` contains `smi` but not `smiles`?  But why is the failing case invoking `-ismiles`? Why the inconsistency in the `-i` argument?

**Comment by ghutchis** [comment]
Aha! I think it loads *all* Open Babel extensions, which includes both `.smiles` and `.smi`. Should be an easy fix, thanks.

**Comment by drew-parsons** [comment]
But why would it chop and change between one form of the extension or the other when driving the process?
