### ISSUE TITLE
Zooming with mouse wheel/touchpad is reversed

### ISSUE THREAD

**Issue by mquevill** [OpenChemistry/avogadrolibs#670]
**Avogadro version: 1.94.0-17-gb2b873b**
 - Avogadrolibs: 1.94.0-94-g2d86f8c
 - Qt: 5.12.8

**Desktop version: (please complete the following information):**
 - OS and Version: Linux Mint 20.2 (based on Ubuntu 20.04
 - Compiler: g++ 9.3.0

**Describe the bug**
On default settings, scrolling on a mouse wheel (or track pad) scrolls opposite from the OS settings. I tried reversing scroll direction through the OS and it was still opposite from what I would expect.

**To Reproduce**
Load some atoms and then scroll up/down.

**Expected behavior**
Normally, if the user has "Reverse scrolling" (Windows default), scrolling down would zoom out, but Avogadro zooms in. Similarly, "Natural scrolling" (Mac default) is also reversed from what is expected.

**Additional context**
While I believe the current issue to be a bug, this could also be a feature request to put an **option** in to allow for the scrolling settings to be different from the OS settings.

I was able to get the desired scrolling direction by negating the zoom factor below to be `-e->delta() * 0.1`.

https://github.com/OpenChemistry/avogadrolibs/blob/2d86f8cdb657b7fc5ce900b0f36fb6f93e6a1665/avogadro/qtplugins/navigator/navigator.cpp#L143

**Comment by ghutchis** [comment]
I'll have to look. On my MacBook, I use the "zoom-pinch" gesture and that works as expected. Feel free to submit a pull request with the change.. I'll just have to look for a mouse to test it. 😄

**Comment by ghutchis** [comment]
I just tried with a Mac with scroll-wheel mouse and "scroll direction natural" set.
- Scroll down = zoom out
- Scroll up = zoom in

Maybe we should post this in the forum to see if it's just on Windows or other people are experiencing it?
