### ISSUE TITLE
Error message on 'Optimize Geometry'

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#674]
**Avogadro version:**
 - Avogadrolibs: e.g. 1.94.0
 - Qt: 5.12.1

**Desktop version:**
 - OS: Microsoft Windows
 - Version: 10.0.19043.1083

**Describe the bug**
When to use _Optimize Geometry_ option, _Open Babel_ shows an error message saying 
> Error interpreting Open Babel output.

**To Reproduce**
1. Draw some molecule.
2. Go to `Extensions > Open Babel > Optimize Geometry`
3. See error

**Screenshots**

![Steps to reproduce Optimize Geometry on Avo2 error](https://user-images.githubusercontent.com/56561421/125709006-d8540e0f-58fc-44f3-ab03-d4f1f4a1a61a.gif)

**Comment by ghutchis** [comment]
I'm going to need a specific version. I've fixed a bunch of these recently, so can you try the nightly?
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

**Comment by grsousajunior** [comment]
Avo2 from your link works fine.

**Comment by ghutchis** [comment]
You can call it "nightly" and give a date. We'll have a 1.95 release near the end of July. Most definitely report any weird behaviors you've seen. I'm going to close this issue, but thanks - it's a big help to get users reporting issues. :smile
