### ISSUE TITLE
'Adjust Hydrogens' sometimes fails

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#678]
**Avogadro version: 1.94.0**
- Avogadrolibs: 1.94.0 [nightly][nightly] downloaded at [2021-07-16 10:45 UTC-3](https://time.is/UTC-3)
- Qt: 5.12.10

**Desktop version:**
- OS: Microsoft Windows 64-bit operating system, x64-based processor
- Version: 10.0.19043.1083

**Describe the bug**  
Using the *Pencil Tool* to draw a cyclopropane molecule, when connecting the last and first carbon atoms, the last one appears without hydrogen atoms.

![Odd behavior on a monocyclic molecule](https://user-images.githubusercontent.com/56561421/125966746-cdbbd28f-fceb-4cff-b871-923b114710ad.gif)

This odd behavior happens with any monocyclic and bicyclic molecule.

![Odd behavior on a bicyclic molecule](https://user-images.githubusercontent.com/56561421/125966885-4cee7a65-e8f5-4d5a-8fdb-d8e9856c7e8d.gif)

However, using `Nitrogen` as last atom, everything works fine.

![Odd behavior using Nitrogen as last atom](https://user-images.githubusercontent.com/56561421/125967062-a8cf5c22-4249-429f-8d1d-83f0ff323d05.gif)

[nightly]: https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

**Comment by mquevill** [comment]
I can also confirm this happens on Linux Mint too, built from `master`.

Oddly enough, some bicyclic cases work right...

Starting from incorrect cyclobutane:
![image](https://user-images.githubusercontent.com/17033543/126001879-c5480ad0-8e75-4690-aa08-02b0305ff990.png)
Adding a methyl group (which corrects the hydrogen count):
![image](https://user-images.githubusercontent.com/17033543/126001897-4cde6796-1231-47dc-8e59-01aaf2793bde.png)
Connecting existing atoms (making it bicyclic):
![image](https://user-images.githubusercontent.com/17033543/126001916-90d19876-2662-471c-a7e8-da6bc92bfe60.png)

**Comment by ghutchis** [comment]
If you have a chance to check the latest `master` with #1112 I'd appreciate it. I can confirm it fixed this bug in my testing. Sorry it took a while to track down.

**Comment by mquevill** [comment]
Tested at e4b94fa5dfcf759b6237b991ebb25b60937a6977, and all the test cases shown here act correctly!
