### ISSUE TITLE
PDB Import: crystal box from CRYST1 record is displayed wrongly

### ISSUE THREAD

**Issue by MSoegtropIMC** [OpenChemistry/avogadrolibs#679]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.94.0
 - Qt: 5.12.10

**Desktop version: (please complete the following information):**
 - OS: Win
 - Version 10 64 21H1

**Describe the bug**
When a PDB file with a CRYST1 record is imported and the angles are not 90°, the box is drawn wrongly. I attached a sample file (Graphite created with Avogadro 1.2)

**To Reproduce**
1. Load the attached file (rename .txt to .pdb)
2. Box does not match atoms (see attached screen shot)

**Expected behavior**
Box should match atoms

**Screenshots**

![Screen](https://user-images.githubusercontent.com/7895506/125986634-ac97a8de-bded-41e3-bc19-58cbe867865f.PNG)
[11x11x1.txt](https://github.com/OpenChemistry/avogadrolibs/files/6832455/11x11x1.txt)

**Comment by ghutchis** [comment]
Yes, there's an obvious bug. Could you let me know the Cell Matrix from Avo1 and Avo2?

Avo1:
<img width="417" alt="Screen Shot 2021-07-16 at 2 11 28 PM" src="https://user-images.githubusercontent.com/41128/125991244-d6c261f9-38a8-41a6-a512-cecbeaa038c7.png">

Avo2:
<img width="446" alt="Screen Shot 2021-07-16 at 2 11 59 PM" src="https://user-images.githubusercontent.com/41128/125991263-e4c812c2-10a8-49d2-9f8f-ea0f83317bb8.png">

The code is different and it would help to track down the error, thanks.

**Comment by MSoegtropIMC** [comment]
Sure, please see below. One more observation: the cell is correct when I use OpenBabel PDB import.

Sure. In Avogadro 1.2 I get the cell matrix:
```
   27.01600   0.00000   0.00000
  -13.50800  23.39654   0.00000
    0.00000   0.00000   6.69600
```

In Avogradro 1.94, when I use Avogradro PDB import, I get the cell matrix:
```
   27.01600   0.00000   0.00000
   21.99591  15.68579   0.00000
   -3.00030  -0.96022   5.90869
```

In Avogradro 1.94, when I use OpenBabel PDB import, I get the cell matrix:
```
   27.01600   0.00000   0.00000
  -13.50800  23.39654   0.00000
   -0.00000  -0.00000   6.69600
```

**Comment by ghutchis** [comment]
Thanks, that's very helpful. Yes, Avogadro 1.x uses Open Babel. Let me take a look later this afternoon...

**Comment by MSoegtropIMC** [comment]
One more observation: Even with rectangular cells I see wrong cell outlines. E.g. I created a rectangular graphite cell (2x atoms of the elementary cell) which is all 90° but all length different and this gets imported with all odd angles when I use the Avogadro PDB import - OpenBabel PDB import is fine.

**Comment by ghutchis** [comment]
Yes, it turns out to be a degree vs. radians issue.. Fortunately, an easy fix.
