### ISSUE TITLE
Projection type on 'View' menu don't save on close

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#682]
**Avogadro version: 1.94.0**
- Avogadrolibs: 1.94.0 [nightly][nightly] downloaded at [2021-07-16 10:45 UTC-3](https://time.is/UTC-3)
- Qt: 5.12.10

**Desktop version:**
- OS: Microsoft Windows 64-bit operating system, x64-based processor
- Version: 10.0.19043.1083

**Describe the bug**  
Avo2 "nightly" don't shows up `Reference Axes` until click on screen and don't save `Reference Axes` choice on close.

**To Reproduce**
1. Go to `View > Projection` and choose `Orthographic`.
2. Close the application.
4. Open it again.
5. The projection is `Perspective` again.

**Screenshots**

![2021-07-16-15-44-37-946](https://user-images.githubusercontent.com/56561421/125994702-36805d56-3d96-4c30-b8ef-a04aedca427c.gif)

[nightly]: https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

**Comment by ghutchis** [comment]
Thanks - there's a bunch of "polish" bugs like this - I appreciate the reports to make sure we fix them all.

**Comment by ghutchis** [comment]
This is now fixed by https://github.com/OpenChemistry/avogadroapp/pull/179 for Avogadro 1.95, thanks!
