### ISSUE TITLE
Cannot delete last atom by selection

### ISSUE THREAD

**Issue by mquevill** [OpenChemistry/avogadrolibs#683]
**Avogadro version: 1.94.0-21-g0942bdb**
 - Avogadrolibs: 1.94.0-103-g91db7e7
 - Qt: 5.12.8

**Desktop version:**
 - OS & Version: Linux Mint 20.2 (based on Ubuntu 20.04)
 - Compiler: gcc 9.3.0

**Describe the bug**
Selecting atoms and deleting (by pressing "delete"), works much better due to #672 and #677. However, it still leaves the last atom if it's the only one. When deleting part of a molecule, it works as expected.

**To Reproduce**
Select all atoms and tap "delete". One atom will be remaining and must be deleted by unselecting and pressing "delete". Even if the setup starts with only one atom, it can never be deleted by this method.

**Expected behavior**
All selected atoms would be deleted.

**Screenshots**
All atoms selected:
![image](https://user-images.githubusercontent.com/17033543/126001011-531a5ec8-67ff-45fb-87b2-0e740be35628.png)
After pressing "delete":
![image](https://user-images.githubusercontent.com/17033543/126001061-3a7c35e6-e3e3-42bb-ade1-893f8f24e68b.png)

**Comment by MSoegtropIMC** [comment]
I can confirm this - it seems to be the first atom (#1) btw. which cannot be deleted. Even when there are multiple atoms, one cannot delete atom #1 by selection. One can delete it with edit / right click, though.
