### ISSUE TITLE
Odd behavior on 'Center' and 'Align View to Axes' options on 'View' menu

### ISSUE THREAD

**Issue by grsousajunior** [OpenChemistry/avogadrolibs#684]
**Avogadro version: 1.94.0**
- Avogadrolibs: 1.94.0 [nightly][nightly] downloaded at [2021-07-16 10:45 UTC-3](https://time.is/UTC-3)
- Qt: 5.12.10

**Desktop version:**
- OS: Microsoft Windows 64-bit operating system, x64-based processor
- Version: 10.0.19043.1083

**Describe the bug**  
Avo2 "nightly" will "jump" when `Center` or `Align View to Axes` is used.

**To Reproduce**
1. Using `Pencil Tool` click on screen to draw a methane molecule.
2. Go to `View > Center`. The molecule "jumps" at end of move.  The _reference axes_ "jumps" as well.
3. Go to `View > Align View to Axes`. The molecule "jumps" at beginning of move.

**Screenshots**
![odd behavior on recenter or align molecules](https://user-images.githubusercontent.com/56561421/126005356-ab692080-89d7-48a7-bfe9-72ee1e59cc03.gif)

Also the `Reference Axes` seems non-orthogonal.
![avo2 reference axes](https://user-images.githubusercontent.com/56561421/126007169-cea08081-833f-42f6-bb6c-eafc5cdbbafa.png)

[nightly]: https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Win64.exe.zip

**Comment by TyBalduf** [comment]
I get a similar result from an Ubuntu build. In my case, the C-H bond lengths also appear distorted, but measuring them shows they  all still have the same length.

**Comment by ghutchis** [comment]
If you could take a look at this @serk12 - I'm having trouble reproducing this myself. But usually these bugs come from small shear in the camera matrix over the animation..

**Comment by serk12** [comment]
I create a PR fixing the 'Center' problem, it was incomplete. But the 'Align View to Axes' looks normal. I think all the problem was in 'Center'.
