### ISSUE TITLE
Build failure for Mac wheel

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#701]
There is now a consistent build failure for Python wheels on Mac. I can't make sense of the failure, since it seems to be using Python 3.6 just fine.

Presumably there's now a problem finding the dylib?

[build-wheel.txt](https://github.com/OpenChemistry/avogadrolibs/files/6881823/build-wheel.txt)

@psavery - if you can take a look, I'm happy to do the fix... Perhaps @cryos may have ideas too?

**Comment by psavery** [comment]
Hi @ghutchis, I should be able to look into this soon.

I wonder if it might be caused by a new version of [`delocate`](https://github.com/matthew-brett/delocate). I see previous CI runs that succeeded were using `delocate==0.8.2`, whereas the new ones that are failing are using `delocate==0.9.0`.

**Comment by ghutchis** [comment]
Makes sense. The ChangeLog is here .. looks like `--ignore-missing-dependencies` might be useful...
https://github.com/matthew-brett/delocate/blob/master/Changelog
