### ISSUE TITLE
When loading a cjson file, editing the element type does not change the color

### ISSUE THREAD

**Issue by MSoegtropIMC** [OpenChemistry/avogadrolibs#707]
**Avogadro version: (please complete the following information from the About box):**
  - CI build from issue #680

**Desktop version: (please complete the following information):**
 - OS: Windows
 - Version: 10 64 21H1

**Describe the bug**
- When loading a cjson file, changing an atom e.g. from C to N does not change the color.
- Saving as .cml and relaoding fixes the color.
- When loading a file from CML, editing atoms does change color

**To Reproduce**
1. Load any cjson file with a C atom in it
2. Change the element type from C to N

**Expected behavior**
The atom changes color to blue

**Additional context**
The element type is changed in the cjson file - just the coloris not changed.

**Comment by MSoegtropIMC** [comment]
Hmm - it does not seem to depend on if .cml or .cjson is loaded.

This used to work in Avogadro 2 but now it doesn't any more - it might be an effect of the new version or somethign with the specific files. I will keep an eye open.

**Comment by ghutchis** [comment]
Oh.. Good point. Right now, the CJSON saves possibly custom atom colors.

Let me go fix the code - when changing the element, it should reset colors.

**Comment by ghutchis** [comment]
Some older CJSON files won't have custom colors, so the bug won't happen. The fix will also check if custom colors were set before saving them to the file.

**Comment by MSoegtropIMC** [comment]
> Some older CJSON files won't have custom colors, so the bug won't happen. The fix will also check if custom colors were set before saving them to the file.

Ah this explains why it does work sometimes and sometimes not - depending on if I load an older or newer file. Thanks for the fix! I like the custom color feature - it is very useful to give quick visual feedback from simulators and tools.

Btw.: while in general I appreciate the use of Json since it is easy to process in python, I am not terribly happy with the specific choices made. E.g. that coordinates are just a x,y,z,x,y,z array and colors likewise. I think a much more natural choice would have been to create one dictionary for each atom with all the information which belongs to one atom (element, coordinates, color, name, ...) and at the top level have an array of atoms, an array of bonds and additional information.

**Comment by ghutchis** [comment]
In Avo v1, we had "color plugins" which would show color schemes like these, partial charges, etc. When the partial  charge code is back, I'll add that in. My aim would be to also enable color scripts -- we have a long term project to estimate reactivities, molecular degradation, etc. (It's possible now - you'd write a command and just add/modify colors to the resulting CJSON.)

> I think a much more natural choice would have been to create one dictionary for each atom with all the information which belongs to one atom (element, coordinates, color, name, ...)

This turns out to be slow when you're parsing large molecular trajectories (i.e., lots of atoms * lots of coordinate sets).

Somewhere, I think we have some glue code that interconverts those forms.. I'll add that as a separate issue.
