### ISSUE TITLE
Angle Tools not working in 1.95.1-1

### ISSUE THREAD

**Issue by HideyoshiNakazone** [OpenChemistry/avogadrolibs#754]
**Avogadro version: 1.95.1-1
 - Avogadrolibs: 1.95.1-1
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Arch Linux
 - Version 08.2021
 - Compiler gcc version 11.1.0 (GCC)

**Describe the bug**
When using the angle tool in a bond nothing appears.

**To Reproduce**
1. Click on angle button
2. Click on molecular bond
3. Nothing happens

**Expected behavior**
Show the angle between adjacent bonds on click.

**Screenshot**
![image](https://user-images.githubusercontent.com/60374951/131396573-616e9fc9-8cf9-4c05-ac24-dca0bc7c14d0.png)

**Comment by ghutchis** [comment]
This was fixed by #825
