### ISSUE TITLE
Player feature causes intermittent crash to desktop on Windows

### ISSUE THREAD

**Issue by bapride11** [OpenChemistry/avogadrolibs#762]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.95.1
 - Qt: 5.12.10

**Desktop version: (please complete the following information):**
 - OS: Windows
 - Version: 20H2
 - Compiler: Unknown (Release Version from Github)

**Describe the bug**
Avogadro crashes to desktop with no error message when using the "Player" feature to animate vibrations produced with ORCA's "orca_pltvib" utility (multi-molecule xyz file). The crash is intermittent, and can happen both by dragging the slider and using the "play" button. If one loop of play completes successfully, it seems that it will not crash. I have been able to reproduce just as intermittently with the 1.95.0 release, but the 1.94.0 release does not appear to have this problem.

**To Reproduce**
1. Open multi-xyz file.
2. Open player interface.
3. Click play *or* drag slider.

**Comment by ghutchis** [comment]
One other question - do you have the "dynamic bonding" feature checked in the Player tool? I doubt it's a Windows-only issue, so I'll try to reproduce.

**Comment by bapride11** [comment]
Good catch! I haven't been able to reproduce with dynamic bonding checked. Given that the issue is intermittent, it's hard to be definitive. Here is a file I have been able to occasionally trigger the crash with (note: real extension XYZ, but Github doesn't like that format).

[freq.hess.v006.xyz.txt](https://github.com/OpenChemistry/avogadrolibs/files/7107988/freq.hess.v006.xyz.txt)

**Comment by ghutchis** [comment]
I suspect it's a race condition with the dynamic bonding. The file will help, thanks.

**Comment by ghutchis** [comment]
For what it's worth, I'm getting a backtrace like this on Mac:
```
0   libAvogadroCore.1.95.1.dylib  	0x000000010e9af7ce Avogadro::Core::ConnectedGroup::resetToSize(unsigned long) + 366
1   libAvogadroCore.1.95.1.dylib  	0x000000010e9c7272 Avogadro::Core::Graph::removeEdges() + 18
2   libAvogadroCore.1.95.1.dylib  	0x000000010e9d28c3 Avogadro::Core::Molecule::clearBonds() + 179
```

So yes, it's from the dynamic bonding. For now, I'll probably patch to disable that feature while I find the underlying bug.
