### ISSUE TITLE
Hydrogen atoms are not being adjusted properly

### ISSUE THREAD

**Issue by mquevill** [OpenChemistry/avogadrolibs#780]
**Avogadro version:** 1.95.1-34-g923acb8
 - Avogadrolibs: 1.95.1-67-gb0531363
 - Qt: 5.12.8

**Desktop version: (please complete the following information):**
 - OS: Linux Mint
 - Version: 20.2
 - Compiler: g++

**Describe the bug**
Something is off about the hydrogen-adjusting method, but not sure exactly what.

**To Reproduce**
*All steps are done by clicking and dragging*
1. Draw C-C triple bond 
![step 1](https://user-images.githubusercontent.com/17033543/132870230-6a5247f3-ffda-4d6a-953e-8ffb983b3d79.png)
2. Create new C off one of the triple-bonded C atoms
![Screenshot from 2021-09-10 10-32-51](https://user-images.githubusercontent.com/17033543/132870321-4c273c38-cf4f-44d3-b947-17ae885f3d18.png)
3. Try to create new C off the other triple-bonded C atoms
![Screenshot from 2021-09-10 10-33-23](https://user-images.githubusercontent.com/17033543/132870547-55a1ba55-8063-4581-b5d7-ae2c82937546.png)
4. Try to undo with ctrl+z and it crashes
5. Receive the error message: `avogadro2: .../openchemistry/avogadrolibs/avogadro/qtgui/rwmolecule_undo.h:100: virtual void Avogadro::QtGui::{anonymous}::AddAtomCommand::undo(): Assertion `m_molecule.atomCount() == m_atomId + 1' failed.`

Actually, it seems like it just ended up moving one of the H atoms? But the hydrogens are not adjusted accordingly.
![Screenshot from 2021-09-10 10-33-53](https://user-images.githubusercontent.com/17033543/132870598-dc50ff00-a662-438a-a027-e526d9adc0ce.png)

I was trying to pinpoint this issue, but was having it in other cases, where all bonds were single bonds.

**Comment by mquevill** [comment]
Possibly related to #678, but this is a case without the molecules being cyclic.

**Comment by ghutchis** [comment]
I'm going to close this in favor of #678 - there's clearly a race condition somewhere in the adjust hydrogen code. It's never been limited to rings.

**Comment by ghutchis** [comment]
I appreciate the additional test cases, but I'd rather have one "master issue" on this.

**Comment by ghutchis** [comment]
If you have a chance, please check `HEAD` which includes #1112 - it seems to fix this and #678 in my testing. Sorry it took so long to track down.

**Comment by mquevill** [comment]
Tested at e4b94fa5dfcf759b6237b991ebb25b60937a6977, and undoing new atoms adjusts hydrogens as expected. Thanks for the fix!
