### ISSUE TITLE
Need a GitHub build-bot (CDash / Travis / Appveyor)

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#79]
We need a Travis CI build bot integrated into GitHub so every Pull Request can be tested for build success and test coverage. For example #77 indicates tests are crashing.

**Comment by ghutchis** [comment]
Some useful links:
https://github.com/travis-ci/travis-ci/issues/6503
https://github.com/opencor/opencor/blob/master/.travis.yml

The current block seems to be that spglib (and likely other pre-requisites) aren't detected when you run cmake on avogadrolibs itself.

**Comment by ghutchis** [comment]
I'm fine if there's a CDash solution - even for my own use, it would help to have automatic comments and complaints on pull requests.

**Comment by ghutchis** [comment]
I think this was solved by @psavery correct?

**Comment by psavery** [comment]
Indeed! It can be more extensive (i.e., we can test Windows and Apple also). But there is a build bot for Linux.

**Comment by ghutchis** [comment]
I'm going to close this and open two separate issues for Windows and Mac. Good first tasks for GSoC applicants. :-)
