### ISSUE TITLE
Alchemy / Alloy Build Command

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#795]
It would be great to have a simple "replace element" command - either on the whole molecule or a selection if present:

- Select element: (popup menu)
- Select replacement: (popup menu)

Optionally a % of replacements (e.g., replace 50% of the Au atoms with Ag)

This would be pretty easy to do in Python script too.

(Replace H atoms with F for "perfluorination", alloys, etc.)

**Comment by Kriteja522** [comment]
Hi, @ghutchis I understood that a "replace" command should be added to the build button on the menu bar. I downloaded the code into my VS Code and searched all the files but couldn't find the code where the changes need to be made. I'm new to contributing so I don't know how to move forward....I'm basically stuck. Can you please help me on this? It would really help me!

**Comment by DHRUVJ2003** [comment]
Hello,
I have created a pr for the plugin. so please review the pr and merge it if everything is apt.

**Comment by DHRUVJ2003** [comment]
Hello,
please review the pr ,let me know the necessary changes if required and merge the same if everything is appropriate.

**Comment by ghutchis** [comment]
This is now closed by https://github.com/OpenChemistry/avogadro-commands/pull/1
