### ISSUE TITLE
Molecular surfaces (van der Waals, solvent excluded, solvent accessible)

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#797]
There are several standard isosurface mesh types that we should generate (e.g. to allow mapping electrostatic potential, orbitals, etc.)

- [ ] Van der Waals surface mesh
- [ ] Solvent accessible
- [ ] Solvent excluded

There are multiple approaches to this, but the ETDSurf method is fairly fast and open source.

I have a variety of other approaches, including progressive refinement on GPUs.

**Comment by drew-parsons** [comment]
As an addendum to this, it could be useful if this kind of functionality could also calculate the molecular volume contained inside the surface.

**Comment by ghutchis** [comment]
Ironically, I have the code to calculate the surface area and volume of the mesh.. just not finished surface code.

**Comment by ghutchis** [comment]
For reference, the method for volume calculation is here: https://rosenzweig.io/blog/hilariously-fast-volume-computation-with-the-divergence-theorem.html

Calculating area is just a matter of summing over all triangles in the mesh, e.g. https://gamedev.stackexchange.com/a/165647/153627
