### ISSUE TITLE
Build Broken with Clang

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#81]
The current master is broken on Mac (clang) - confirming need for #79 

<pre>
/Users/ghutchis/Devel/openchemistry/avogadrolibs/avogadro/qtplugins/crystal/importcrystaldialog.cpp:76:51: error: 
      expected '(' for function-style cast or type construction
    OBFileFormat ob("", "", "", "", vector<string>{ext}, vector<string>{""});
                                    ~~~~~~~~~~~~~~^
/Users/ghutchis/Devel/openchemistry/avogadrolibs/avogadro/qtplugins/crystal/importcrystaldialog.cpp:76:72: error: 
      expected '(' for function-style cast or type construction
    OBFileFormat ob("", "", "", "", vector<string>{ext}, vector<string>{""});
</pre>

**Comment by ghutchis** [comment]
I think the work-around is simply to declare vector{ext} and vector{} as temporary variables on the line before. Putting them all on one line is also a bit hard to read, IMHO.

**Comment by psavery** [comment]
Okay. Sorry about that. I sent in another pull request to fix it:

https://github.com/OpenChemistry/avogadrolibs/pull/82
