### ISSUE TITLE
precision of unit test wrapAtomsToUnitCell is too tight for i386

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#812]
**Avogadro version: 1.95.1**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.2

**Desktop version:**
 - OS: Debian GNU/Linux
 - Version 5.14.9-2 (debian unstable)
 - Compiler g++ 10.3.0

**Describe the bug**

Unit test UnitCellTest.wrapAtomsToUnitCell fails on i386 (i686):
```
[ RUN      ] UnitCellTest.wrapAtomsToUnitCell
/tmp/autopkgtest-lxc.w4hysxt4/downtmp/build.1Hw/src/tests/core/unitcelltest.cpp:265: Failure
Expected: (it->y()) >= (static_cast<Real>(0.0)), actual: -1.44334e-18 vs 0
[  FAILED  ] UnitCellTest.wrapAtomsToUnitCell (0 ms)
```
full test log at https://ci.debian.net/data/autopkgtest/testing/i386/a/avogadrolibs/15859508/log.gz

Evidently the precision is too tight for 32-bit i386, such that `it->y()` is "mostly zero" but crosses just below 0, making the test fail.

Assuming it's just a question of machine precision and not actually a true substantial error, I guess some small EPS would need to be brought in to allow for "negative mostly zero". There would be more than one of doing it, avogadrolibs might already have a method used elsewhere that I'm not aware of.
e.g.
```
#include <limits>
it->y()) >= (static_cast<Real>(-std::numeric_limits<Real>::epsilon())
```
(not certain if `<Real>` will work with `limits`, but `<double>` or `<float>` will certainly work)

For reference, test file
```
#include<cfloat>
#include<limits>
#include<iostream>

int main()
{
	std::cout << "min float values are " <<  FLT_MIN << "  " <<  std::numeric_limits<float>::epsilon() << std::endl;
        std::cout << "min double values are "<<  DBL_MIN << "  " <<  std::numeric_limits<double>::epsilon() << std::endl;

}
```
on i386 generates
```
min float values are 1.17549e-38  1.19209e-07
min double values are 2.22507e-308  2.22045e-16
```
so any floating point  `epsilon()` should work, while neither ` FLT_MIN` nor `DBL_MIN` will help.

**To Reproduce**
1. Build avogadrolibs on i386 (i686)
2. Run unit tests: 
3. ???
4. Loss!!

**Expected behavior**

Tests should be able to pass (or else be skipped) on i386.

**Comment by ghutchis** [comment]
Thanks for the patch - I'm closing this one.
