### ISSUE TITLE
Freezes and shutdowns 

### ISSUE THREAD

**Issue by ChrKostaras** [OpenChemistry/avogadrolibs#816]
**Avogadro version: 1.95.1 (Flatpak)
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.3

**Desktop version: 
 - OS: Kubuntu 
 - Version 20.10
 - Plasma ver. 5.19.5
 - Kernel 5.8.0-63

Bug description
Freezes when I try to overwrite a .cjson file during saving and shuts-down when I try to add a 3rd carbon atom. None of this problems occur within the qt version (ver. 1.93.0).

Issue 1
1. Hit ctrl+s
2. Select already saved .cjson file within any folder
3. After hitting the prompt to overwrite the software will freeze and will only be closed through system monitor

Issue 2
1. Go to Draw button and have carbon selected
2. Try to make a 3 carbon atom molecule by dragging
3. The software will immediately shut-down

**Comment by ghutchis** [comment]
This should be fixed in HEAD now, e.g. the AppImage https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage.zip
