### ISSUE TITLE
Bonding atoms manually doesn't work (regression?)

### ISSUE THREAD

**Issue by aerkiaga** [OpenChemistry/avogadrolibs#820]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.3

**Desktop version: (please complete the following information):**
 - OS: Linux Mint
 - Version 20.2

**Describe the bug**
Bonding atoms manually creates a corrupted molecule.

**To Reproduce**
1. Open Avogadro 2.
2. Place two carbon atoms (should create two methane molecules).
3. Click on one of the carbons and drag cursor to the other.
4. Release cursor to create bond.

**Expected behavior**
The two carbon atoms should become bonded, losing each one hydrogen atom around it to yield an ethane molecule.

**Screenshots**
![image](https://user-images.githubusercontent.com/38228836/139921408-c26817f2-81f3-4648-849e-53990003aa04.png)

**Additional context**
Missing hydrogens around the first atom is not the only issue; trying to add another carbon atom instead moves one of the remaining hydrogens to the clicked location. Doing so many times crashes Avogadro 2.

**Comment by ghutchis** [comment]
Thanks for the bisect work. I'll look into it more carefully. I think the problem is that some code expects the start atom to fall before the end atom.
