### ISSUE TITLE
split screen (3D View) is fully transparent

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#826]
**Avogadro version: 1.95.1**
 - Avogadrolibs: 1.95.1
 - Qt: 5.15.2

**Desktop version: (please complete the following information):**
 - OS: Linux (Debian)
 - Version: 5.16.11 (debian unstable)
 - Compiler g++ 11.2.0

**Describe the bug**

Avogadro2 has a split screen functionality (Split Horizontal, Split Vertical).

When I click one of them, the window splits into 2 as expected, the new half-window is blank (grey)  With a button "3D View" in the middle.

When I click on 3D view, the half-window becomes 100% transparent, showing the screen and windows underneath the avogadro app.

**To Reproduce**
1. Open avogadro
2. Click on "Split Horizontal"
3. Click on '3D View'

**Expected behavior**

I'm not actually sure what Split or 3D View should be showing, but for sure they should not be showing the background screen and underlying windows.

**Additional context**

Some different transparency problems were addressed in #653 . On the face of it not related.

**Comment by drew-parsons** [comment]
Seems to fix the windowing display.  Molecule shows up visible straight away with a black background

(i.e. it fixes the bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008719 where the background was black not transparent, but the molecule was not visible until moved or rotated)

For what it's worth, it's a good idea to use a transparent background for the copied image of the molecule (the one copied to clipboard via Edit->Copy Graphics (Ctrl-Alt-C).   Can the alpha channel address in https://github.com/OpenChemistry/avogadroapp/pull/262 be toggled, activated only while Copy Graphics is performed, then switched off again for normal display?

**Comment by ghutchis** [comment]
The change is that I'm not asking for an OpenGL context with alpha support on Linux - because that seems to be the core problem.

I'll investigate creating a new context with alpha, render into that, and close. It just won't be at the top of my todo list.
