### ISSUE TITLE
Error reading Gaussian09 output files still seems to be unfixed

### ISSUE THREAD

**Issue by bennski** [OpenChemistry/avogadrolibs#827]
I'm also having this problem with 1.93.0-1

_Originally posted by @bennski in https://github.com/OpenChemistry/avogadrolibs/issues/571#issuecomment-1059487529_

**Comment by bennski** [comment]
[test_HF_sim.log](https://github.com/OpenChemistry/avogadrolibs/files/8188568/test_HF_sim.log)

The error message in the command prompt when trying to open Gaussian 09 output file is the same as the original bug:

OBProcess::executeObabel: Running "obabel" "-iout -ocml"
"obabel"  stderr:
 "0 molecules converted\n"
Process encountered an error, and did not execute correctly.
	Exit code: 0
	Exit status: QProcess::NormalExit
	Exit output: ""

**Comment by ghutchis** [comment]
Out of curiosity, if you rename it to have ".g09" extension, does it work?

**Comment by bennski** [comment]
> Out of curiosity, if you rename it to have ".g09" extension, does it work?

No it did not. The error message is the same.

**Comment by ghutchis** [comment]
Okay, but you're using 1.93. Can you try one of the build results on the thread? I was able to reproduce your bug and fix it on my Mac. It should work with one of the new builds linked here.

**Comment by bennski** [comment]
> Okay, but you're using 1.93. Can you try one of the build results on the thread? I was able to reproduce your bug and fix it on my Mac. It should work with one of the new builds linked here.

I ran the script for the ubuntu build, but when I run the avogadro executable, I get "./avogadro2: error while loading shared libraries: libMoleQueueServerCore.so: cannot open shared object file: No such file or directory"
Not sure what I'm doing wrong here. I have Ubuntu 20.04.

I also tried grabbing the latest build from git to run the test, but don't have permissions to download the submodules.

Sorry, I got 1.93 easily running with apt-get.

**Comment by ghutchis** [comment]
You're grabbing the raw binary which expects `molequeue` to be installed and it may not be on your system.

You can try the AppImage linked above, which I'm sure will work. 

There's also an `unstable` / `testing` package of 1.95.1 from `debichem`: https://tracker.debian.org/pkg/avogadro

There's also a Flatpak: https://dl.flathub.org/repo/appstream/org.openchemistry.Avogadro2.flatpakref

The latter two don't have the most recent fix (for `.log`) files, but if you use `.g09` as your file extension, IIRC that works with 1.95.1.
