### ISSUE TITLE
Export molecule Error in 1.94.0: Unable to find a suitable writer for the selected format 

### ISSUE THREAD

**Issue by RazzyChen** [OpenChemistry/avogadrolibs#828]
Hi,
I built openchemistry package avgadro2 version is 1.94.0 on my Manjaro x86_64 Linux.

When I try to export the molecule in mol2 XYZ PDB(I have only tested these formats) using avgadro2. I always get the message "Unable to find a suitable writer for the selected format." Even I can use openbabel to optimize the geometry in GUI：（ So...I think openbabel is working.

And I refer to this website to build my application: https://wiki.openchemistry.org/Build

I already saw it in the previous issue(#464), but I still got the error after upgrading to the latest version.

Is there something wrong with me?

**Comment by ghutchis** [comment]
You said "still got the error after upgrading" - do you mean to 1.95.x?

But exporting to XYZ should always work - there's internal code. So if that's not working, there's something really problematic and I'd like to know more.

**Comment by RazzyChen** [comment]
Thank you for your reply : )

I have upgraded the program to version 1.95.1-110. 

I may have solved that problem. When exporting molecule files, I add .xxx after the name, for example, test.mol2 test.xyz and test.pdb, only then Avogadro can successfully export molecule files. 

Instead of selecting the file format from the format list in the save screen. If I do this the Avogadro will report an error： Unable to find a suitable writer....

Is this situation consistent with what the developers expected?

This is my first issue submission and I hope I have described the problem clearly

**Comment by ghutchis** [comment]
It's a little weird, but seems like it's a UI issue that could be fixed. If you pick the file format, does it change the extension automatically? 

Could you send me a screenshot with the save screen when you encounter the error?

Thanks very much!

**Comment by RazzyChen** [comment]
I sent an email to your Gmail, the video of the error is attached to the email, please check it.

**Comment by ghutchis** [comment]
Thanks so much for the video. It seems as if the dialog does not automatically add the extension. I'm going to add some code to check for this before trying to save. Should be an easy fix (fingers crossed).

If I make a patch, would you be able to compile or use an AppImage to check if it works for you?

**Comment by RazzyChen** [comment]
Thank you for your reply : )

Yes, I am very glad to compile a new package. If the patch is available please tell me.

**Comment by ghutchis** [comment]
You can take a look at #835 - I'm not sure it fixes the problem, because I'm seeing other posts with similar complaints for Qt5 on Linux.

Worse case, I'll write in a custom save dialog as a workaround.

**Comment by RazzyChen** [comment]
I see. Thank you very much. This issue is solved.

**Comment by ghutchis** [comment]
Does the patch do what you want?
