### ISSUE TITLE
Revisit MoleculeModel widget

### ISSUE THREAD

**Issue by chiroptical** [OpenChemistry/avogadrolibs#83]
@cryos Wanted to bring this enhancement out of the developer emails. I will try to look at this again soon.

The "Molecules" widget needs to be more central to development. When I open up a molecule it should signal to interfaces that the molecule has changed. This way one can open up an arbitrary number of molecules and the interface updates automagically.

**Comment by cryos** [comment]
I think it is critical we support multiple molecules, there are several holes right now. The scissors were used by mistake, I thought I had replaced it with an X (red cross), and will find that out. You can switch between the molecules, but the interaction seems to be different on each platform (click, double-click, press enter).

Totally agree on adding a signal when the active molecule changes, add a * for color blind users? Sounds like great suggestions.

**Comment by cryos** [comment]
#84 replaces the scissors with a cross, which is a small step in the right direction. Another usability issue @ghutchis brought up is an issue for display types and the molecule list - what constitutes selected and therefore active is quite different on different platforms. Clicking on Linux, but you seem to need to do more on Mac.

One that was on my todo was to add a tick box for whether to render the molecule in a given display, and support rendering more than one molecule. I think we would still need an active molecule to guide where edits/changes are made in the different tools. I have been doing this a lot in Tomviz with multiple volumetric data sources.

If we did that would we be better adding display types/visualization modules to the molecule to show which visualizations a given molecule has, along with eyeballs dictating when they are visible. This would combine molecules with display types in a single view, something like

![image](https://cloud.githubusercontent.com/assets/42214/16160508/975009ca-3496-11e6-95d4-1dcb855a018c.png)

**Comment by ghutchis** [comment]
@cryos I think it would be good to post a discussion to the list about this. There are advantages, but I'd be curious if there are preferences for the old style, this new style, or ideas about other ways of getting it to work.

**Comment by ghutchis** [comment]
@cryos - the other key question is adding display types for particular atoms or subsets (e.g., draw the metal with VdW sphere, the rest with sticks, etc.)

**Comment by barrymoo** [comment]
I am currently working on a mock up for a new molecule interface (there is a lot of nuances I need to understand before working on the real interface). I will try to create an interface similar to the one @cryos showed above so we can discuss pros/cons with a more concrete example.

**Comment by barrymoo** [comment]
@cryos Could you point me to the code you use for the image in https://github.com/OpenChemistry/avogadrolibs/issues/83#issuecomment-226843630 ?

**Comment by cryos** [comment]
It is QAbstractItemModel and QTableView working together, I wrote a fair bit of it, and was thinking about how it might be applied to Avogadro. The nice thing with stuff like this is that is is possible to maintain a simplistic view such as we have now, but I think there is real demand for showing multiple molecules in the same window, having a solid model of an active molecule, display type, etc. It would also offer an opportunity to have one data model panel, and then another properties for whatever is selected.

In building this I have also spotted several of the issues in the Avogadro 2 code, and was going to author a few updates that at least make this work more consistently across Windows, Mac and Linux.

**Comment by cryos** [comment]
https://github.com/OpenChemistry/tomviz/blob/master/tomviz/PipelineModel.cxx is one such file, you can see PipelineView.cxx next to it too.

**Comment by barrymoo** [comment]
@cryos Thanks! I am working on https://github.com/barrymoo/simpletreemodel, which I will try to model similar to the TomViz PipeLine. If everyone likes it, I can work towards full integration.

**Comment by ghutchis** [comment]
@barrymoo - is this still live? Should we close it and re-open a new pull request or set of issues to build this up piece-by-piece?

**Comment by ghutchis** [comment]
I'd consider closing this one, but at a minimum:
- formula should use subscript / superscript
- show / allow cubes to be added under the tree (e.g., that there's a way to "add" a new file to the molecule )

**Comment by ghutchis** [comment]
I'm closing this as mostly solved with the layers feature.
