### ISSUE TITLE
Please add `Hungarian` to https://two.avogadro.cc/

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#843]
At https://two.avogadro.cc/, please add `Hungarian` to:
`International: Translations into Chinese, French, German, Italian, Russian, Spanish, and others, with more languages to come.`
to become:
`International: Translations into Chinese, French, German, Hungarian, Italian, Russian, Spanish, and others, with more languages to come.`

![image](https://user-images.githubusercontent.com/17465872/158037864-e23dc2fb-4063-4169-b032-f87b301ba96b.png)

What do you think?

Thank you

**Comment by ghutchis** [comment]
Of course it would also help if the translations were also working, but I'll add this for the next sync. Thanks for the reminder and the contributions!

**Comment by ovari** [comment]
Do you have an update on an ETA of the release? Thank you once again.

**Comment by ghutchis** [comment]
This (at least) is fixed. Still trying to figure out why the translations aren't loading, but that's on our end.

> Thank you. Do you have an update on an ETA of the release?

Hopefully by the end of May.
