### ISSUE TITLE
Porting to Qt 6.x

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/avogadrolibs#854]
It would be nice to get the code ready for Qt6:
https://doc.qt.io/qt-6/portingguide.html

Step 1 - make sure it works with Qt 5.15 (requires VTK9 #516)

- Compile with -DQT_DISABLE_DEPRECATED_BEFORE=0x050F00
- Port QRegExp to QRegularExpression (https://www.qt.io/blog/porting-from-qt-5-to-qt-6-using-qt5compat-library)
  - #include <QRegExp>
  - Change CMakeLists to include Qt::Core5Compat

There are a few other CMake changes needed too:
https://conf.kde.org/event/1/contributions/19/attachments/17/18/2106-PortingToQt6%20%28Final%20Version%29.pdf

**Comment by ghutchis** [comment]
For now, we'd need to ensure the code works for both Qt 5.15.x and 6.x versions.

**Comment by ghutchis** [comment]
Clazy checks can help with this too:
https://doc.qt.io/qt-6/porting-to-qt6-using-clazy.html

**Comment by arijitsaha123** [comment]
I want to solve this problem. Can you kindly help me with which point I should start? I have installed VTK and Qt 5.15 MinGW in my local environment.

**Comment by ghutchis** [comment]
Well, if you want to solve the problem, the first thing you'll need is Qt 6.x installed (e.g., 6.2 LTS).

Then you'd want to start trying to compile using Qt 6 https://two.avogadro.cc/install/build.html

**Comment by shashwat-chawla** [comment]
Hey, I want to solve this issue, Can you assign me this and guide me through it :)

**Comment by Abhal4140** [comment]
I want to work on this issue, please assign me the problem.

**Comment by ghutchis** [comment]
In this project we generally don't assign issues, unless it's to indicate someone on the core team is already working on it.

As I mentioned above, the first step would be to download and build using the instructions above.

There are general guides to port to Qt6: https://doc.qt.io/qt-6/portingguide.html
And the `clazy` utility has some checks: https://doc.qt.io/qt-6/porting-to-qt6-using-clazy.html

Probably the first step when building is to add the `-DQT_DISABLE_DEPRECATED_BEFORE=0x050F00` to the compile and see if there's anything that pops up.
