### ISSUE TITLE
 1.96.0 Blank screen instead of a molecule. Regression of bug #733?

### ISSUE THREAD

**Issue by uuuu1234** [OpenChemistry/avogadrolibs#933]
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.96.0
 - Qt: 5.15.4

**Desktop version: (please complete the following information):**
 - OS: Arch Linux
 - flatpak version

**Describe the bug**
All menus are displayed correctly, but the section of the screen where the molecule is supposed to be displayed is transparent. Similar to bug #733 .

**To Reproduce**
1. Install the flatpak
2. Start the application

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49108043/172401428-54f069df-8eeb-49a8-a1be-02ce160e1bfe.png)

**Additional context**
Output from the terminal after running "flatpak run org.openchemistry.Avogadro2" seems nominal:

Locale:  "en_US"
Translated quit:  "&Quit"
Extension plugins dynamically found… 39
Checking for  "commands"  scripts in "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/app/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/usr/share/runtime/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/run/host/user-share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/run/host/share/OpenChemistry/Avogadro/commands"
Checking for  "commands"  scripts in "/app/bin/../lib/avogadro2/scripts/commands"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/centroid.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/centroid.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nAdd Centroid for Selection\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/centroid.py\", line 86, in <module>\n    elif args['run_workflow']:\nKeyError: 'run_workflow'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/scale.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/scale.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nScale Coords...\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-commands/scale.py\", line 92, in <module>\n    elif args['run_workflow']:\nKeyError: 'run_workflow'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/etkdg.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/etkdg.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\n/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/etkdg.py:41: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n  if opts['ff'] is 'UFF':\n/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/etkdg.py:43: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n  elif opts['ff'] is 'MMFF94':\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/etkdg.py\", line 13, in <module>\n    from rdkit import Chem\nModuleNotFoundError: No module named 'rdkit'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/uff.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/uff.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/uff.py\", line 9, in <module>\n    from rdkit import Chem\nModuleNotFoundError: No module named 'rdkit'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/mmff94.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/mmff94.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/mmff94.py\", line 9, in <module>\n    from rdkit import Chem\nModuleNotFoundError: No module named 'rdkit'\n"
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/tautomer.py" ; "Error running script '/usr/bin/python3 /home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/tautomer.py --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/commands/avogadro-rdkit/tautomer.py\", line 9, in <module>\n    from rdkit import Chem\nModuleNotFoundError: No module named 'rdkit'\n"
OBProcess::executeObabel: Running "/app/bin/obabel" "-L formats read"
OBProcess::executeObabel: Running "/app/bin/obabel" "-L formats write"
OBProcess::executeObabel: Running "/app/bin/obabel" "-L forcefields"
OBProcess::executeObabel: Running "/app/bin/obabel" "-L charges"
OBProcess::executeObabel: Running "/app/bin/obabel" "-V"
"/app/bin/obabel"  found:  "/app/bin/obabel: Open Babel 3.1.0 -- Jun  4 2022 -- 21:38:39"
Checking for  "inputGenerators"  scripts in "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/app/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/usr/share/runtime/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/run/host/user-share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/run/host/share/OpenChemistry/Avogadro/inputGenerators"
Checking for  "inputGenerators"  scripts in "/app/bin/../lib/avogadro2/scripts/inputGenerators"
Checking for  "formatScripts"  scripts in "/home/user/.var/app/org.openchemistry.Avogadro2/data/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/app/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/usr/share/runtime/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/run/host/user-share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/run/host/share/OpenChemistry/Avogadro/formatScripts"
Checking for  "formatScripts"  scripts in "/app/bin/../lib/avogadro2/scripts/formatScripts"
Open Babel formats ready:  142

**Comment by aerkiaga** [comment]
I can't reproduce this with either the AppImage, Flatpak or AUR versions. @uuuu1234 could you please post the output of `glxinfo | grep OpenGL && echo $XDG_CURRENT_DESKTOP $XDG_SESSION_TYPE`? In the meantime, you could try the [AppImage version](https://github.com/OpenChemistry/avogadrolibs/releases/download/1.96.0/Avogadro2-x86_64.AppImage) and see if it works for you.

**Comment by ghutchis** [comment]
Yes, it won't work with Wayland - see #567. The upcoming switch away from GLEW to the OpenGL core profile should help with that.

**Comment by uuuu1234** [comment]
Okay thanks. So I defaulted back to X11 windowing system using flatseal. Now it works at least.

So the issue can be closed then.

**Comment by ghutchis** [comment]
Yes, although it's good motivation to move away from GLEW sooner, rather than later.
