### ISSUE TITLE
Please allow `Ball and Stick` and `Cartoons` in `Rétegek` (`Layers`) to be translatable

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#950]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145 from https://github.com/OpenChemistry/avogadroapp/issues/207#issuecomment-1156982114

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
Please allow `Layer 1`, `Ball and Stick` and `Cartoons` in `Rétegek` (`Layers`) to be translatable.

**To Reproduce**
Please see image in the Screenshots section.

**Expected behavior**
In `Rétegek` (`Layers`) the following should show in Hungarian:
1. [x] `Layer 1`fixed
2. `Ball and Stick`
3. `Cartoons`

**Screenshots**
![Layers](https://user-images.githubusercontent.com/17465872/174040576-2e9b8667-368e-450f-bf7e-27fad400eaf2.png)

Thank you

**Comment by ghutchis** [comment]
Thanks! I *think* I have solved this, but will need the rest of the translation infrastructure to catch up - might take a few days. I'll keep it open until I can confirm it's fixed.

**Comment by ovari** [comment]
>  I'll keep it open until I can confirm it's fixed.

Can you please re-open this issue as it is not fixed. Thank you

**Comment by ovari** [comment]
Partially fixed as shown in image below:

![kép](https://user-images.githubusercontent.com/17465872/176380233-b1e8f747-6ca5-4402-ae22-5bfb877a3d55.png)

Thank you

**Comment by ghutchis** [comment]
Weird because the upper panel is translated. I'll look into it.

**Comment by ghutchis** [comment]
I had to hack this, but #992 should fix once the translation files update in a few days.

(Better to have a bit of a hack than untranslated strings, for sure.)

**Comment by ovari** [comment]
It seems that now the items are no longer showing.

![kép](https://user-images.githubusercontent.com/17465872/177230675-8554f8a8-0752-465f-b21b-e9fd7252e33b.png)

**Comment by ghutchis** [comment]
😞

**Comment by ghutchis** [comment]
Well, I guess it's at least some sort of progress? I'll check out what's happening. Thanks for your patience.

**Comment by ovari** [comment]
Fixed with recent (~last hour) download. Thank you

![kép](https://user-images.githubusercontent.com/17465872/179660812-0dc08e6b-a0a0-4f01-9c1b-4d5ab89db6fd.png)

**Comment by ghutchis** [comment]
Thanks for all the hard work. Hopefully we can get the remaining i18n bugs fixed and put out a 1.97 release with 100% translation this week or next.

**Comment by ovari** [comment]
That would be great. Hopefully the `File` option multiplicity can be easily reduced from 3 to 1.

**Comment by ghutchis** [comment]
I think this PR should help with that:
https://github.com/OpenChemistry/avogadroapp/pull/296
