### ISSUE TITLE
`Molecular…` option (in the Menu bar) not translated

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#951]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145 from https://github.com/OpenChemistry/avogadroapp/issues/207#issuecomment-1156982114

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
`Molecular…` option not translated.

**To Reproduce**
[Molecular…](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Molecular&sort_by=-priority%2Cposition&checksum=) option not in Weblate and translation not showing in Avogadro.

**Expected behavior**
[Molecular…](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Molecular&sort_by=-priority%2Cposition&checksum=) option translated and showing in Avogadro.

**Screenshots**
![Molecular… option not translated](https://user-images.githubusercontent.com/17465872/174037749-0642429d-e79e-4f8b-94e3-46c137de1851.png)

Thank you

**Comment by ovari** [comment]
Should this issue be re-opened and closed once it is verified fixed?

**Comment by ghutchis** [comment]
Sure - I'm seeing it in the [translation template](https://github.com/OpenChemistry/avogadrolibs/blob/e5d3b4ebf859d60ed148b21f879f2be13daf4147/i18n/avogadrolibs.pot#L2892)
```
#: qtplugins/molecularproperties/molecularproperties.cpp:22
msgid "&Molecular…"
msgstr ""
 
#: qtplugins/molecularproperties/molecularproperties.cpp:32
msgid "View general properties of a molecule."
msgstr ""
```

Looks like you translated it as well - even if it's not in the compiled binary:
https://hosted.weblate.org/translate/avogadro/avogadrolibs/hu/?q=Molecular&sort_by=-priority%2Cposition&offset=7

**Comment by ovari** [comment]
Verified fixed with [Avogadro2.AppImage](https://github.com/OpenChemistry/avogadrolibs/suites/7136137964/artifacts/283509289) from https://github.com/OpenChemistry/avogadrolibs/issues/963#issuecomment-1169490362. Thank you
