### ISSUE TITLE
`Scale Coordinates…` in `Kiterjesztések` (`Extensions`) not shown in Hungarian and dialog box not fully localized

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#953]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145 from https://github.com/OpenChemistry/avogadroapp/issues/207#issuecomment-1156982114

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
1. [x] `Extensions` menu shows twice, once in English and then later in Hungarian (`Kiterjesztések`). Verified fixed with [Avogadro2.AppImage](https://github.com/OpenChemistry/avogadrolibs/suites/7136137964/artifacts/283509289) from https://github.com/OpenChemistry/avogadrolibs/issues/963#issuecomment-1169490362
2. `Scale Coordinates…` option in the `Extensions` menu is not translatable in [Weblate](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Scale+Coordinates&sort_by=-priority%2Cposition&checksum=)
3. `Scale Coordinates…` dialog box not fully translated

**To Reproduce**
Please see image in the Screenshots section.

**Expected behavior**
1. [x] `Extensions` not show in the menu bar, only `Kiterjesztések`. Verified fixed with [Avogadro2.AppImage](https://github.com/OpenChemistry/avogadrolibs/suites/7136137964/artifacts/283509289) from https://github.com/OpenChemistry/avogadrolibs/issues/963#issuecomment-1169490362
2. [Scale Coordinates…](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Scale+Coordinates&sort_by=-priority%2Cposition&checksum=) to be translatable in Weblate
4. `Scale Coordinates…` to show localized in Avogadro
5. `Scale Coordinates…` dialog window title to show localized
6. [X Scale:](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=X+Scale&sort_by=-priority%2Cposition&checksum=), [Y Scale:](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Y+Scale&sort_by=-priority%2Cposition&checksum=) and [Z Scale:](https://hosted.weblate.org/browse/avogadro/avogadroapp/hu/?offset=1&q=Z+Scale&sort_by=-priority%2Cposition&checksum=)

**Screenshots**
1, 2, and 3:
![Scale Coordinates…](https://user-images.githubusercontent.com/17465872/174031008-c33fe7d8-2f42-4907-804a-b11439915eaa.png)

4 and 5:
![kép](https://user-images.githubusercontent.com/17465872/174031408-568a98be-5e4f-43d6-ba10-748c5db28091.png)

Thank you

**Comment by ovari** [comment]
Thank you for removing the English `Extensions` from the menu bar as shown in the image below.

![kép](https://user-images.githubusercontent.com/17465872/176381474-8c303b27-8505-4999-b63c-97edf7cd1703.png)

**Comment by ghutchis** [comment]
As I mentioned, I will merge the "Scale Coordinates" into the code so it can also be translated.

Still not sure why there's a "File" menu, but I'll track it down too.

**Comment by ovari** [comment]
> Still not sure why there's a "File" menu, but I'll track it down too.

Thank you.

There are two `Fájl`'s and one `File`, giving a total of 3 `File` (Hungarian and English).

Please see image below:

![kép](https://user-images.githubusercontent.com/17465872/177231049-81ffa3d0-4c24-4d83-a01f-b99ad88e909c.png)

Thank you once again.

**Comment by ovari** [comment]
Can you please advise where the extension is located to enable translation? Thank you

**Comment by ghutchis** [comment]
The script should no longer be installed. I'm not really sure the best way to handle translation of Python scripts.

If you have it installed, it would have be in something like `/usr/lib/avogadro2/scripts/commands/` or `/usr/local/avogadro2/scripts/commands` and can safely be deleted.

It's not really a useful feature - it was mostly to demonstrate that you can write Python scripts to add commands.
