### ISSUE TITLE
`About` in the `Súgó` (`Help`) menu incorrectly shows in English, not Hungarian

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#955]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145 from https://github.com/OpenChemistry/avogadroapp/issues/207#issuecomment-1156982114

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
`About` in the `Súgó` (`Help`) menu incorrectly shows in English, not Hungarian.

**To Reproduce**
Please see image in Screenshots sections.

**Expected behavior**
`About` in the `Súgó` (`Help`) menu correct show in Hungarian.

**Screenshots**
![About](https://user-images.githubusercontent.com/17465872/174025247-9b9f1e79-a7ea-4380-b39a-4c81b43a7d3f.png)

Thank you

**Comment by ghutchis** [comment]
Thank! I transferred this too fast - it's in `avogadroapp` after all. Should be fixed now.

**Comment by ovari** [comment]
Verified fixed. Thank you
