### ISSUE TITLE
Element list showing incorrectly in English, not Hungarian

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#962]
**Avogadro version:**
 - Avogadrolibs: 1.96.0
 - Qt: 5.12.12
 - https://github.com/OpenChemistry/avogadrolibs/suites/6965951512/artifacts/272132144 from https://github.com/OpenChemistry/avogadrolibs/issues/954#issuecomment-1158008448

**Desktop version:**
 - OS: Linux Mint 20.3 Cinnamon

**Describe the bug**
Elements in the list are showing in English, not the locale of the Avogadro program.

**To Reproduce**
Please see image in the Screenshots section.

`Carbon` (in English) should be written as `Szén` (in Hungarian). This is shown correctly in the periodic table, but not the list.

**Expected behavior**
Elements in the list should show in the locale of Avogadro program. For example, the image in the Screenshots section should show in Hungarian.

If `Egyéb…` (`Other…`) is selected, the periodic table does correctly show in Hungarian.

**Screenshots**
![List incorrectly showing in English, not Hungarian](https://user-images.githubusercontent.com/17465872/174251632-3a7c6067-00df-457d-b183-2f9376925824.png)

![Periodic table showing correctly in Hungarian](https://user-images.githubusercontent.com/17465872/174251594-6882cc0a-bf46-4911-9ea9-88166bf3a4e9.png)

Thank you

**Comment by ghutchis** [comment]
Ugh. Thanks for these reports - I'm working through them.
