### ISSUE TITLE
Periodic table control with the keyboard

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadrolibs#963]
Please allow using the keyboard to navigate the periodic table.
1. Allow arrow keys (`→`, `←`, `↑`, `↓`) to move around the periodic table
2. `Esc` to close the periodic table
3. `Enter` to select the current element and close the periodic table
4. Add `_OK` and `_Cancel` buttons

![Periodic Table in Hungarian](https://user-images.githubusercontent.com/17465872/174252617-0e2e6937-3936-42bb-a8dc-9d87b47bc5f3.png)

What do you think?

Thank you

**Comment by ghutchis** [comment]
It's a good idea. I'd also add in typing numbers to match the element number, or typing letters to match the symbol.
