### ISSUE TITLE
 An error occurred while retrieving the list of supported forcefields

### ISSUE THREAD

**Issue by craldaz** [OpenChemistry/avogadrolibs#98]
Downloaded and installed prebuilt executable (Avogadro2.0.8.0-Darwin).
When I click on optimize geometry or any button in extensions I get an error like this.
An error occurred while retrieving the list of supported forcefields. (using '/Applications/Avogadro2.app/Contents/MacOS/obabel').

I did install openbabel via Brew and qt 5, and my OS is MacOS el Capitan. 

I also tried building following the instructions on openchemistry. 

When I set the DYLD_LIBRARY_PATH to prefix/lib and open avogardoapp/bin/Avogadro2.app I get the following error message and output:

LSOpenURLsWithRole() failed with error -10810 for the file /Users/codyaldaz/openchemistry/avogadroapp/bin/Avogadro2.app.

[output.txt](https://github.com/OpenChemistry/avogadrolibs/files/400009/output.txt)

**Comment by ghutchis** [comment]
Can you try the latest binary?
http://sourceforge.net/projects/avogadro/files/avogadro2/0.9.0/Avogadro2-0.9.0-Darwin.dmg/download

Not sure why you're getting that error, but try:
`% /Users/codyaldaz/openchemistry/avogadroapp/bin/Avogadro2.app/Contents/MacOS/Avogadro2`

**Comment by ghutchis** [comment]
I'd like to follow up on this. Otherwise, I'm going to mark this as resolved.

Are you still having problems with 0.9.0?

**Comment by ghutchis** [comment]
I'm marking this closed. If you have problems with future versions, please open a new issue, thanks!
